(function(){var a=typeof process!=="undefined"&&process.versions&&process.versions.node?global:window;if(typeof a.Ooyala=="undefined")a.Ooyala={};Ooyala.Util={};var b=function(c){if(typeof c!="string")throw"The namespace name must be a string.";var d=c.split(".");if(!(d.length>0))throw"The namespace '"+c+"' is not valid.";for(var g=a,e=0;e<d.length;e++){var h=d[e];if(!(h.length>0))throw"The namespace '"+c+"' is not valid.";if(g[h]){var i=d.slice(0,e).join(".");if(typeof g[h]!="object")throw"Namespace error: the name '"+
i+"' already exists and is not a namespace.";}else g[h]={};g=g[h]}};b("Ooyala.Util");Ooyala.Util.createNamespace=b})();Ooyala.Util.getOwnProperties=function(a){var b=[];for(var c in a)a.hasOwnProperty(c)&&b.push(c);return b};Ooyala.Util.extend=function(a,b){for(var c in b)if(b.hasOwnProperty(c)&&a[c]==undefined)a[c]=b[c]};Ooyala.Util.createNamespace("Ooyala.Util");Ooyala.Util.bind=function(a,b){var c=Array.prototype.slice.call(arguments,2);return function(){return a.apply(b,c.concat(Array.prototype.slice.call(arguments)))}};Ooyala.Util.createNamespace("Ooyala.Util.Http");Ooyala.Util.Http._XMLHttpRequestFactories=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Microsoft.XMLHTTP")},function(){return new ActiveXObject("MSXML2.XMLHTTP.3.0")},function(){return new ActiveXObject("MSXML2.XMLHTTP")}];Ooyala.Util.Http._XMLHttpRequestFactory=null;
Ooyala.Util.Http.createXMLHttpRequest=function(){if(Ooyala.Util.Http._XMLHttpRequestFactory!=null)return Ooyala.Util.Http._XMLHttpRequestFactory();for(var a=0;a<Ooyala.Util.Http._XMLHttpRequestFactories.length;a++)try{var b=Ooyala.Util.Http._XMLHttpRequestFactories[a],c=b();if(c!=null){Ooyala.Util.Http._XMLHttpRequestFactory=b;return c}}catch(d){}Ooyala.Util.Http._XMLHttpRequestFactory=function(){throw"XMLHttpRequest not supported.";};Ooyala.Util.Http._XMLHttpRequestFactory()};Ooyala.Util.createNamespace("Ooyala.Util.Enumerable");
Ooyala.Util.extend(Ooyala.Util.Enumerable,{_checkFunction:function(a){if(typeof a!="function")throw new TypeError;},foreach:function(a,b){this._checkFunction(b);for(var c=0;c<a.length;c++)b.call(undefined,a[c])},map:function(a,b){this._checkFunction(b);var c=[];Ooyala.Util.Enumerable.foreach(a,function(d){c.push(b.call(undefined,d))});return c},select:function(a,b){this._checkFunction(b);var c=[];Ooyala.Util.Enumerable.foreach(a,function(d){b.call(undefined,d)&&c.push(d)});return c},reject:function(a,
b){return this.select(a,function(c){return!b.call(undefined,c)})}});Ooyala.Util.CookieManager=function(a,b,c){this._cookieName=a;this._daysToLive=b;this._compareFn=c;this._keysValuesHash={};this._cookiesEnabled=window.navigator.cookieEnabled;Ooyala.Util.CookieManager.cookieNames.push(a)};Ooyala.Util.CookieManager.MAX_COOKIE_SIZE=2048;Ooyala.Util.CookieManager.cookieNames=[];
Ooyala.Util.CookieManager.prototype={deDupe:function(){for(var a=this._readAllCookies(this._cookieName),b=0;b<a.length;b++)this._updateHashFromString(a[b]);this._writeCookie(this._cookieName,this._updateStringFromHash());this._destroyCookies(this._cookieName)},get:function(a){if(!this._cookiesEnabled)return null;this._updateHashFromString(this._readCookie(this._cookieName));return(a=this._keysValuesHash[a])?a:null},set:function(a,b){if(this._cookiesEnabled){this._keysValuesHash[a]=b.toString();this._writeCookie(this._cookieName,
this._updateStringFromHash())}},_compare:function(a,b){return this._compareFn(this._keysValuesHash[b],this._keysValuesHash[a])},_updateHashFromString:function(a){if(a){a=a.split("&");for(var b=0;b<a.length;b++){var c=a[b],d=c.indexOf(":");if(d!=-1){var g=c.substring(0,d);c=c.substring(d+1);if(this._compareFn(this._keysValuesHash[g],c)<0)this._keysValuesHash[g]=c}}}},_updateStringFromHash:function(){for(var a=Ooyala.Util.getOwnProperties(this._keysValuesHash).sort(Ooyala.Util.bind(this._compare,this)),
b="",c=this._cookieOverhead(this._cookieName),d=0;d<Ooyala.Util.CookieManager.cookieNames.length;d++){var g=Ooyala.Util.CookieManager.cookieNames[d];if(g!=this._cookieName)c+=this._cookieOverhead(g)+(this._readCookie(g)||"").length}for(d=0;d<a.length;d++){g=a[d];var e=this._keysValuesHash[g];if(c+b.length+g.length+e.length+(d==0?1:2)>Ooyala.Util.CookieManager.MAX_COOKIE_SIZE)break;b+=(d==0?"":"&")+g+":"+e}return b},_writeCookie:function(a,b){document.cookie=a+"="+b+"; expires="+this._getExpiryDate()+
"; path=/;"},_readCookie:function(a){var b=document.cookie;if(!b)return null;a=a+"=";b=b.split(";");for(var c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1);if(d.indexOf(a)==0){a=d.substring(a.length,d.length);return a.length>0?a:null}}return null},_readAllCookies:function(a){var b=document.cookie,c=[];if(!b)return c;a=a+"=";b=b.split(";");for(var d=0;d<b.length;d++){for(var g=b[d];g.charAt(0)==" ";)g=g.substring(1);if(g.indexOf(a)==0){g=g.substring(a.length,g.length);g.length>
0&&c.push(g)}}return c},_destroyCookies:function(a,b){if(a){b||(b=false);for(var c=document.location.pathname;;){var d=c.lastIndexOf("/");if(d===-1)break;if(d===0&&c.length===1)break;document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path="+c+";";c=c.substring(0,d)}if(b)document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;"}},_cookieOverhead:function(a){return a.length+this._getExpiryDate().length+10+9},_getExpiryDate:function(){var a=(new Date).getTime();return(new Date(a+
this._daysToLive*24*60*60*1E3)).toGMTString()}};Ooyala.Util.createNamespace("Ooyala.ThirdParty.SHA256");
(function(){function a(e,h){var i=(e&65535)+(h&65535);return(e>>16)+(h>>16)+(i>>16)<<16|i&65535}function b(e,h){return e>>>h|e<<32-h}function c(e,h){var i=Array(1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,
666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298),f=Array(1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225),k=Array(64),l,n,o,r,m,p,q,s,t,j,u,v;e[h>>5]|=128<<24-h%32;e[(h+
64>>9<<4)+15]=h;for(t=0;t<e.length;t+=16){l=f[0];n=f[1];o=f[2];r=f[3];m=f[4];p=f[5];q=f[6];s=f[7];for(j=0;j<64;j++){k[j]=j<16?e[j+t]:a(a(a(b(k[j-2],17)^b(k[j-2],19)^k[j-2]>>>10,k[j-7]),b(k[j-15],7)^b(k[j-15],18)^k[j-15]>>>3),k[j-16]);u=a(a(a(a(s,b(m,6)^b(m,11)^b(m,25)),m&p^~m&q),i[j]),k[j]);v=a(b(l,2)^b(l,13)^b(l,22),l&n^l&o^n&o);s=q;q=p;p=m;m=a(r,u);r=o;o=n;n=l;l=a(u,v)}f[0]=a(l,f[0]);f[1]=a(n,f[1]);f[2]=a(o,f[2]);f[3]=a(r,f[3]);f[4]=a(m,f[4]);f[5]=a(p,f[5]);f[6]=a(q,f[6]);f[7]=a(s,f[7])}return f}
function d(e){for(var h=[],i=(1<<g)-1,f=0;f<e.length*g;f+=g)h[f>>5]|=(e.charCodeAt(f/g)&i)<<24-f%32;return h}var g=8;Ooyala.ThirdParty.SHA256.sha256ToHexString=function(e){e=c(d(e),e.length*g);for(var h="",i=0;i<e.length*4;i++)h+="0123456789abcdef".charAt(e[i>>2]>>(3-i%4)*8+4&15)+"0123456789abcdef".charAt(e[i>>2]>>(3-i%4)*8&15);return h};Ooyala.ThirdParty.SHA256.sha256ToBase64String=function(e){e=c(d(e),e.length*g);for(var h="",i=0;i<e.length*4;i+=3)for(var f=(e[i>>2]>>8*(3-i%4)&255)<<16|(e[i+1>>
2]>>8*(3-(i+1)%4)&255)<<8|e[i+2>>2]>>8*(3-(i+2)%4)&255,k=0;k<4;k++)h+=i*8+k*6>e.length*32?"":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(f>>6*(3-k)&63);return h};Ooyala.ThirdParty.SHA256.sha256ToString=function(e){e=c(d(e),e.length*g);for(var h="",i=(1<<g)-1,f=0;f<e.length*32;f+=g)h+=String.fromCharCode(e[f>>5]>>>24-f%32&i);return h}})();Ooyala.Constants={LOGGING_SERVER_DOMAIN:(window.location.protocol=="https:"?"https:":"http:")+"//l.ooyala.com",IFRAME_PINGER_PATH:"/analytics/iframe.html",SAS_URL:(window.location.protocol=="https:"?"https:":"http:")+"//player.ooyala.com/sas/analytics",HIGH_PRIORITY_EVENT:0,LOW_PRIORITY_EVENT:1,HIGH_PRIORITY_EVENT_FLUSH_INTERVAL_MS:1E3,LOW_PRIORITY_EVENT_FLUSH_INTERVAL_MS:1E4,MIN_DURATION_FOR_STEP_BACKOFF:24E4};Ooyala.Util.createNamespace("Ooyala.Pinger");Ooyala.Pinger.ALIVE_MESSAGE="&handshake!";Ooyala.Pinger.COOKIE_NAME="gi";Ooyala.Pinger.DAYS_TO_LIVE=7300;Ooyala.Pinger._numCompare=function(){return-1};Ooyala.Pinger.RegisterMessageListener=function(a){window.addEventListener?window.addEventListener("message",a,false):window.attachEvent("onmessage",a)};Ooyala.Pinger.RemoveMessageListener=function(a){window.removeEventListener?window.removeEventListener("message",a):window.detachEvent("onmessage",a)};
Ooyala.Pinger._createAndSetGuid=function(){var a=(new Date).getTime(),b=window.navigator.userAgent,c=Math.random();c=c>0?c.toString(16).split(".")[1]:"00000000";a=Ooyala.ThirdParty.SHA256.sha256ToBase64String(a+b+c);(new Ooyala.Util.CookieManager(Ooyala.Pinger.COOKIE_NAME,Ooyala.Pinger.DAYS_TO_LIVE,Ooyala.Pinger._numCompare)).set("guid",a);return a};
Ooyala.Pinger.getOrCreateGuid=function(){var a=(new Ooyala.Util.CookieManager(Ooyala.Pinger.COOKIE_NAME,Ooyala.Pinger.DAYS_TO_LIVE,Ooyala.Pinger._numCompare)).get("guid");if(a==null)a=Ooyala.Pinger._createAndSetGuid();return a};Ooyala.Pinger.Listener=function(a){this._reconstructor=new Ooyala.Pinger.ChunkReconstructor(a)};Ooyala.Pinger.Listener.POLL_INTERVAL=500;
Ooyala.Pinger.Listener.prototype={_pollAndSend:function(){var a=window.location.hash;if(a.length>1){window.location.hash="";this._reconstructor.push(a.substring(1))}window.setTimeout(Ooyala.Util.bind(this._pollAndSend,this),Ooyala.Pinger.Listener.POLL_INTERVAL)},_messageHandler:function(a){this._reconstructor.push(a.data)},start:function(){if(window.postMessage){try{parent.postMessage(Ooyala.Pinger.ALIVE_MESSAGE+";"+Ooyala.Pinger.getOrCreateGuid(),"*")}catch(a){}Ooyala.Pinger.RegisterMessageListener(Ooyala.Util.bind(this._messageHandler,
this))}else this._pollAndSend()}};Ooyala.Pinger.ChunkReconstructor=function(a){this._receiver=a;this._reset()};
Ooyala.Pinger.ChunkReconstructor.prototype={_parseChunk:function(a){var b=a.split("~");if(b.length!=3)throw"Bad chunk: "+a;a={};a.data=b[0];a.id=parseInt(b[1]);a.count=parseInt(b[2]);if(a.id<=0||a.count<=0||a.id>a.count)throw"Bad chunk ID or total chunk count in ping chunk.";return a},_reset:function(){this._data="";this._totalChunks=this._chunksSeen=0},_handleChunk:function(a){if(this._totalChunks==0){if(!(a.id>1))if(a.count==1)this._receiver.sendPing(a.data);else{this._chunksSeen=1;this._totalChunks=
a.count;this._data=a.data}}else if(a.count==this._totalChunks&&a.id==this._chunksSeen+1)if(a.count==a.id){a=this._data+a.data;this._reset();this._receiver.sendPing(a)}else{this._chunksSeen+=1;this._data+=a.data}else{this._reset();this._handleChunk(a)}},push:function(a){this._handleChunk(this._parseChunk(a))}};Ooyala.Pinger.ServerPinger=function(a){this._pingUrl=a};Ooyala.Pinger.MAX_XVERIFY_HEADER_LENGTH=7500;
Ooyala.Pinger.ServerPinger.prototype={sendPing:function(a){if(a.length>Ooyala.Pinger.MAX_XVERIFY_HEADER_LENGTH)throw"Ping (length = "+a.length+") is too long.";var b=Ooyala.Util.Http.createXMLHttpRequest();b.open("POST",this._pingUrl,true);b.setRequestHeader("X-Verify",a);b.send(null)}};(function(){(new Ooyala.Pinger.Listener(new Ooyala.Pinger.ServerPinger(Ooyala.Constants.LOGGING_SERVER_DOMAIN+"/verify"))).start()})();
