/*{"k":"0.13.0","created":"2012-04-24T10:53:22Z","mac":"1:3d87b299cc33726460991fd2946debd23bc63eff103fa54f5715b5a2b80462d6","version":"10691278"}*/
;(function(window,document,undefined){
var j=true,o=null,q=false;function r(a){return function(c){this[a]=c}}function s(a){return function(){return this[a]}}var t;function u(a,c){var b=arguments.length>2?Array.prototype.slice.call(arguments,2):[];return function(){b.push.apply(b,arguments);return c.apply(a,b)}}function v(a,c){this.p=a;this.j=c}t=v.prototype;
t.createElement=function(a,c,b){a=this.p.createElement(a);if(c)for(var d in c)if(c.hasOwnProperty(d))if(d=="style"){var f=a,g=c[d];if(this.j.getName()=="MSIE")f.style.cssText=g;else f.setAttribute("style",g)}else a.setAttribute(d,c[d]);b&&a.appendChild(this.p.createTextNode(b));return a};t.insertInto=function(a,c){var b=this.p.getElementsByTagName(a)[0];if(!b)b=document.documentElement;if(b&&b.lastChild){b.insertBefore(c,b.lastChild);return j}return q};
t.whenBodyExists=function(a){function c(){document.body?a():setTimeout(c,0)}c()};t.removeElement=function(a){if(a.parentNode){a.parentNode.removeChild(a);return j}return q};t.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};t.appendClassName=function(a,c){for(var b=a.className.split(/\s+/),d=0,f=b.length;d<f;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")};
t.removeClassName=function(a,c){for(var b=a.className.split(/\s+/),d=[],f=0,g=b.length;f<g;f++)b[f]!=c&&d.push(b[f]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};t.hasClassName=function(a,c){for(var b=a.className.split(/\s+/),d=0,f=b.length;d<f;d++)if(b[d]==c)return j;return q};function w(a,c,b,d,f,g,k,h){this.S=a;this.Sa=c;this.Ba=b;this.Aa=d;this.Ma=f;this.La=g;this.za=k;this.Wa=h}t=w.prototype;t.getName=s("S");t.getVersion=s("Sa");t.getEngine=s("Ba");t.getEngineVersion=s("Aa");
t.getPlatform=s("Ma");t.getPlatformVersion=s("La");t.getDocumentMode=s("za");function x(a,c){this.j=a;this.v=c}var aa=new w("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",undefined,q);
x.prototype.parse=function(){var a;if(this.j.indexOf("MSIE")!=-1){a=y(this,this.j,/(MSIE [\d\w\.]+)/,1);if(a!=""){var c=a.split(" ");a=c[0];c=c[1];a=new w(a,c,a,c,z(this),A(this),B(this,this.v),C(this,c)>=6)}else a=new w("MSIE","Unknown","MSIE","Unknown",z(this),A(this),B(this,this.v),q)}else{if(this.j.indexOf("Opera")!=-1)a:{c=a="Unknown";var b=y(this,this.j,/(Presto\/[\d\w\.]+)/,1);if(b!=""){c=b.split("/");a=c[0];c=c[1]}else{if(this.j.indexOf("Gecko")!=-1)a="Gecko";b=y(this,this.j,/rv:([^\)]+)/,
1);if(b!="")c=b}if(this.j.indexOf("Version/")!=-1){b=y(this,this.j,/Version\/([\d\.]+)/,1);if(b!=""){a=new w("Opera",b,a,c,z(this),A(this),B(this,this.v),C(this,b)>=10);break a}}b=y(this,this.j,/Opera[\/ ]([\d\.]+)/,1);a=b!=""?new w("Opera",b,a,c,z(this),A(this),B(this,this.v),C(this,b)>=10):new w("Opera","Unknown",a,c,z(this),A(this),B(this,this.v),q)}else{if(this.j.indexOf("AppleWebKit")!=-1){a=z(this);c=A(this);b=y(this,this.j,/AppleWebKit\/([\d\.]+)/,1);if(b=="")b="Unknown";var d="Unknown";
if(this.j.indexOf("Chrome")!=-1||this.j.indexOf("CrMo")!=-1)d="Chrome";else if(this.j.indexOf("Safari")!=-1)d="Safari";else if(this.j.indexOf("AdobeAIR")!=-1)d="AdobeAIR";var f="Unknown";if(this.j.indexOf("Version/")!=-1)f=y(this,this.j,/Version\/([\d\.\w]+)/,1);else if(d=="Chrome")f=y(this,this.j,/(Chrome|CrMo)\/([\d\.]+)/,2);else if(d=="AdobeAIR")f=y(this,this.j,/AdobeAIR\/([\d\.]+)/,1);var g=q;if(d=="AdobeAIR"){g=y(this,f,/\d+\.(\d+)/,1);g=C(this,f)>2||C(this,f)==2&&parseInt(g,10)>=5}else{g=y(this,
b,/\d+\.(\d+)/,1);g=C(this,b)>=526||C(this,b)>=525&&parseInt(g,10)>=13}a=new w(d,f,"AppleWebKit",b,a,c,B(this,this.v),g)}else{if(this.j.indexOf("Gecko")!=-1){c=a="Unknown";d=q;if(this.j.indexOf("Firefox")!=-1){a="Firefox";b=y(this,this.j,/Firefox\/([\d\w\.]+)/,1);if(b!=""){d=y(this,b,/\d+\.(\d+)/,1);c=b;d=b!=""&&C(this,b)>=3&&parseInt(d,10)>=5}}else if(this.j.indexOf("Mozilla")!=-1)a="Mozilla";b=y(this,this.j,/rv:([^\)]+)/,1);if(b=="")b="Unknown";else if(!d){d=C(this,b);f=parseInt(y(this,b,/\d+\.(\d+)/,
1),10);g=parseInt(y(this,b,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&f>9||d==1&&f==9&&g>=2||b.match(/1\.9\.1b[123]/)!=o||b.match(/1\.9\.1\.[\d\.]+/)!=o}a=new w(a,c,"Gecko",b,z(this),A(this),B(this,this.v),d)}else a=aa;a=a}a=a}a=a}return a};function z(a){var c=y(a,a.j,/(iPod|iPad|iPhone|Android)/,1);if(c!="")return c;a=y(a,a.j,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}
function A(a){var c=y(a,a.j,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(c)return c;if(c=y(a,a.j,/(iPhone )?OS ([\d_]+)/,2))return c;if(a=y(a,a.j,/Linux ([i\d]+)/,1))return a;return"Unknown"}function C(a,c){var b=y(a,c,/(\d+)/,1);if(b!="")return parseInt(b,10);return-1}function y(a,c,b,d){if((a=c.match(b))&&a[d])return a[d];return""}function B(a,c){if(c.documentMode)return c.documentMode}function ba(a,c,b,d){this.c=a;this.l=c;this.W=b;this.o=d||"wf";this.m=new D("-")}
function E(a){a.c.removeClassName(a.l,a.m.k(a.o,"loading"));a.c.hasClassName(a.l,a.m.k(a.o,"active"))||a.c.appendClassName(a.l,a.m.k(a.o,"inactive"));G(a,"inactive")}function G(a,c,b,d){a.W[c]&&a.W[c](b,d)}function H(a,c,b,d,f){this.c=a;this.C=c;this.F=b;this.t=d;this.K=f;this.Z=0;this.ta=this.ha=q}
H.prototype.watch=function(a,c,b,d,f){for(var g=a.length,k=0;k<g;k++){var h=a[k];c[h]||(c[h]=["n4"]);this.Z+=c[h].length}if(f)this.ha=f;for(k=0;k<g;k++){h=a[k];f=c[h];for(var e=b[h],m=0,n=f.length;m<n;m++){var p=f[m],i=this.C,l=h,F=p;i.c.appendClassName(i.l,i.m.k(i.o,l,F,"loading"));G(i,"fontloading",l,F);i=u(this,this.Ca);l=u(this,this.Da);(new d(i,l,this.c,this.F,this.t,this.K,h,p,e)).start()}}};
H.prototype.Ca=function(a,c){var b=this.C;b.c.removeClassName(b.l,b.m.k(b.o,a,c,"loading"));b.c.removeClassName(b.l,b.m.k(b.o,a,c,"inactive"));b.c.appendClassName(b.l,b.m.k(b.o,a,c,"active"));G(b,"fontactive",a,c);this.ta=j;I(this)};H.prototype.Da=function(a,c){var b=this.C;b.c.removeClassName(b.l,b.m.k(b.o,a,c,"loading"));b.c.hasClassName(b.l,b.m.k(b.o,a,c,"active"))||b.c.appendClassName(b.l,b.m.k(b.o,a,c,"inactive"));G(b,"fontinactive",a,c);I(this)};
function I(a){if(--a.Z==0&&a.ha)if(a.ta){a=a.C;a.c.removeClassName(a.l,a.m.k(a.o,"loading"));a.c.removeClassName(a.l,a.m.k(a.o,"inactive"));a.c.appendClassName(a.l,a.m.k(a.o,"active"));G(a,"active")}else E(a.C)}
function J(a,c,b,d,f,g,k,h,e){this.va=a;this.Ga=c;this.c=b;this.F=d;this.t=f;this.K=g;this.Ka=new ca;this.Fa=new da;this.ca=k;this.ba=h;this.Ea=e||"BESbswy";this.ja=ea(this,"arial,'URW Gothic L',sans-serif");this.ka=ea(this,"Georgia,'Century Schoolbook L',serif");this.fa=this.ja;this.ga=this.ka;this.oa=K(this,"arial,'URW Gothic L',sans-serif");this.pa=K(this,"Georgia,'Century Schoolbook L',serif")}J.prototype.start=function(){this.Qa=this.K();this.X()};
J.prototype.X=function(){var a=this.F.P(this.oa),c=this.F.P(this.pa);if((this.ja!=a||this.ka!=c)&&this.fa==a&&this.ga==c)fa(this,this.va);else if(this.K()-this.Qa>=5E3)fa(this,this.Ga);else{this.fa=a;this.ga=c;ga(this)}};function ga(a){a.t(function(c,b){return function(){b.call(c)}}(a,a.X),25)}function fa(a,c){a.c.removeElement(a.oa);a.c.removeElement(a.pa);c(a.ca,a.ba)}function ea(a,c){var b=K(a,c,j),d=a.F.P(b);a.c.removeElement(b);return d}
function K(a,c,b){c=a.c.createElement("span",{style:ha(a,c,a.ba,b)},a.Ea);a.c.insertInto("body",c);return c}function ha(a,c,b,d){b=a.Fa.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(d?"":a.Ka.quote(a.ca)+",")+c+";"+b}function D(a){this.Ia=a||"-"}D.prototype.k=function(){for(var a=[],c=0;c<arguments.length;c++)a.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.Ia)};
function ca(){this.na="'"}ca.prototype.quote=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");d.indexOf(" ")==-1?c.push(d):c.push(this.na+d+this.na)}return c.join(",")};function da(){this.la=ia;this.G=ja}var ia=["font-style","font-weight"],ja={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function ka(a,c,b){this.Ha=a;this.Na=c;this.G=b}ka.prototype.expand=function(a,c){for(var b=0;b<this.G.length;b++)if(c==this.G[b][0]){a[this.Ha]=this.Na+":"+this.G[b][1];break}};da.prototype.expand=function(a){if(a.length!=2)return o;for(var c=[o,o],b=0,d=this.la.length;b<d;b++){var f=this.la[b];(new ka(b,f,this.G[f])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":o};function L(a,c){this.p=a;this.j=c}L.prototype=v.prototype;
L.prototype.isHttps=function(){return this.p.location.protocol=="https:"};L.prototype.getHostName=function(){return this.p.location.hostname};L.prototype.loadScript=function(a,c){var b=this.p.getElementsByTagName("head")[0];if(b){var d=this.p.createElement("script");d.src=a;var f=q;d.onload=d.onreadystatechange=function(){if(!f&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){f=j;c&&c();d.onload=d.onreadystatechange=o;d.parentNode.tagName=="HEAD"&&b.removeChild(d)}};b.appendChild(d)}};
L.prototype.createStyle=function(a){var c=this.p.createElement("style");c.setAttribute("type","text/css");if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));return c};function la(a,c){this.Oa=a;this.$=c}function ma(a){for(var c=a.Oa.join(","),b=[],d=0;d<a.$.length;d++){var f=a.$[d];b.push(f.name+":"+f.value+";")}return c+"{"+b.join("")+"}"}function M(a,c,b,d){this.D=a;this.J=c;this.w=b;this.Va=d;this.da={};this.aa={}}
M.prototype.z=function(a){return a?(this.da[a.getStylesheetFormatId()]||this.J).slice(0):this.J.slice(0)};M.prototype.getId=s("w");function na(a,c,b){for(var d=[],f=a.D.split(",")[0].replace(/"|'/g,""),g=a.z(),k,h=[],e={},m=0;m<g.length;m++){k=g[m];if(k.length>0&&!e[k]){e[k]=j;h.push(k)}}b=b.ma?b.ma(f,h,d):h;c=c.getStylesheetFormatId();a.da[c]=b;a.aa[c]=d}M.prototype.watch=function(a,c,b){var d=[],f={};oa(this,c,d,f);a(d,f,b)};
function oa(a,c,b,d){b.push(a.D);d[a.D]=a.z(c);a=a.aa[c.getStylesheetFormatId()]||[];for(c=0;c<a.length;c++){for(var f=a[c],g=f.D,k=q,h=0;h<b.length;h++)if(b[h]==g)k=j;if(!k){b.push(g);d[g]=f.z()}}}function pa(a,c){this.D=a;this.J=c}pa.prototype.z=s("J");function N(a,c,b){this.Pa=a;this.Q=c;this.qa=b}N.prototype.buildUrl=function(a,c){var b=this.Pa&&a?"https:":"http:",d=typeof this.Q=="function"?this.Q(b):this.Q;return b+"//"+d+(this.qa=="/"?"":this.qa)+c};
function qa(a,c){var b=new Image(1,1);b.src=c;b.onload=function(){b.onload=o}}function O(a,c,b){this.w=a;this.sa=c;this.ea=b}O.prototype.getId=s("w");O.prototype.getStylesheetFormatId=s("sa");O.prototype.isUserAgent=function(a){return this.ea?this.ea(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion(),a.getDocumentMode()):q};O.prototype.buildCssUrl=function(a,c,b,d){b="/"+b+"-"+this.sa+".css";if(d)b+="?"+d;return c.buildUrl(a,b)};
function P(){this.u=[]}P.prototype.addBrowser=function(a){this.getBrowserById(a.getId())||this.u.push(a)};P.prototype.getBrowserById=function(a){for(var c=0;c<this.u.length;c++){var b=this.u[c];if(a===b.getId())return b}return o};P.prototype.findBrowser=function(a){for(var c=0;c<this.u.length;c++){var b=this.u[c];if(b.isUserAgent(a))return b}return o};P.prototype.addBrowsersToBrowserSet=function(a){for(var c=0;c<this.u.length;c++)a.addBrowser(this.u[c])};
function ra(a){this.w=a;this.M=new P;this.n=[];this.N=[];this.O=this.Y=this.B=o}t=ra.prototype;t.getId=s("w");t.setSecurityToken=r("ra");t.setNestedUrl=r("ia");t.setFontFilterSet=r("O");t.setKitOptions=r("R");t.addBrowser=function(a){this.M.addBrowser(a)};t.addFontFamily=function(a){this.n.push(a)};t.addCssRule=function(a){this.N.push(a)};t.supportsBrowser=function(a){return!!this.M.getBrowserById(a.getId())};t.addBrowsersToBrowserSet=function(a){this.M.addBrowsersToBrowserSet(a)};
t.init=function(a){for(var c=[],b=0;b<this.N.length;b++)c.push(ma(this.N[b]));a.insertInto("head",a.createStyle(c.join("")))};
t.load=function(a,c,b,d){if(this.O)for(var f=sa(this.O,b.getStylesheetFormatId()),g=0;g<this.n.length;g++)na(this.n[g],b,f);if(this.B&&this.Y){this.B.wa(new ta(b.getStylesheetFormatId()));g=new ua(a,this.H,this.n);f=va(this.Y,b.getStylesheetFormatId(),g);for(g=0;g<f.length;g++)this.B.wa(f[g]);this.B.Ua(this.ra);g=this.B.buildUrl(a.isHttps(),this.ia)}else g=b.buildCssUrl(a.isHttps(),this.ia,this.w,this.ra);a.insertInto("head",a.createCssLink(g));c&&a.whenBodyExists(function(k,h,e,m){return function(){for(var n=
0;n<k.n.length;n++)k.n[n].watch(h,e,m&&n==k.n.length-1)}}(this,c,b,d))};t.collectFontFamilies=function(a,c,b){for(var d=0;d<this.n.length;d++)oa(this.n[d],a,c,b)};t.performOptionalActions=function(a,c,b){this.R&&b.whenBodyExists(function(d,f,g,k){return function(){var h=d.R;if(h.T){var e=h.T.Ta(window,k.getHostName());qa(h,h.T.k(k.isHttps(),e))}e=d.R;h=d.w;if(e.V){e=e.V.k(h,g,k);e.setAttribute("id","typekit-badge-"+h);k.insertInto("body",e)}}}(this,a,c,b))};
function Q(a,c,b,d,f){this.Ja=a;this.c=c;this.j=b;this.l=d;this.t=f;this.q=[]}Q.prototype.L=function(a){this.q.push(a)};Q.prototype.load=function(a,c){var b=a,d=c||{};if(typeof b=="string")b=[b];else if(b&&b.length)b=b;else{d=b||{};b=[]}if(b.length)for(var f=this,g=b.length,k=0;k<b.length;k++)this.ua(b[k],function(){--g==0&&f.U(d)});else this.U(d)};Q.prototype.ua=function(a,c){this.c.loadScript(this.Ja.buildUrl(this.c.isHttps(),"/"+a+".js"),c)};
Q.prototype.U=function(a){if(a.userAgent)this.j=(new x(a.userAgent,document)).parse();a=new ba(this.c,this.l,a);for(var c=new P,b=0;b<this.q.length;b++)this.q[b].addBrowsersToBrowserSet(c);c=c.findBrowser(this.j);for(b=0;b<this.q.length;b++)this.q[b].init(this.c);if(c){a.c.appendClassName(a.l,a.m.k(a.o,"loading"));G(a,"loading");wa(this,c,a)}else E(a);this.q=[]};
function wa(a,c,b){function d(k,h,e){f.watch(k,h,{},J,e)}var f=new H(a.c,b,{P:function(k){return k.offsetWidth}},a.t,function(){return+new Date});for(b=0;b<a.q.length;b++){var g=a.q[b];if(g.supportsBrowser(c)){g.load(a.c,d,c,b==a.q.length-1);g.performOptionalActions(window,a.j,a.c)}}}function R(a,c,b){this.A=a;this.c=c;this.t=b;this.q=[]}R.prototype.L=function(a){this.q.push(a)};
R.prototype.load=function(){var a=this.A.__webfonttypekitmodule__;if(a)for(var c=0;c<this.q.length;c++){var b=this.q[c],d=a[b.getId()];if(d){var f=this.c,g=this.t;d(function(k,h,e){var m=new P;b.addBrowsersToBrowserSet(m);h=[];var n={};if(m=m.findBrowser(k)){b.init(f);b.load(f,o,m,g);b.collectFontFamilies(m,h,n);b.performOptionalActions(window,k,f,g)}e(!!m,h,n)})}}};function S(a,c){this.S=a;this.ma=c}S.prototype.getName=s("S");
function T(a,c){for(var b=0;b<a.I.length;b++){var d=a.I[b];if(c===d.getName())return d}return o}function sa(a,c){var b=a.r[c];return b?T(a,b):o}function va(a,c,b){var d=[];a=a.s[c]||[];for(c=0;c<a.length;c++){var f;a:switch(a[c]){case "observeddomain":f=new xa(b.c);break a;case "fontmask":f=new ya(b.H,b.n);break a;default:f=o}f&&d.push(f)}return d}function ua(a,c,b){this.c=a;this.H=c;this.n=b}function ta(a){this.Ra=a}ta.prototype.toString=s("Ra");function xa(a){this.c=a}
xa.prototype.toString=function(){var a;a=this.c.getHostName?this.c.getHostName():document.location.hostname;return encodeURIComponent(a)};function ya(a,c){this.H=a;this.n=c}ya.prototype.toString=function(){for(var a=[],c=0;c<this.n.length;c++){var b=this.n[c],d=b.z();b=b.z(this.H);for(var f=0;f<d.length;f++){var g;a:{for(g=0;g<b.length;g++)if(d[f]===b[g]){g=j;break a}g=q}a.push(g?1:0)}}a=a.join("");a=a.replace(/^0+/,"");c=[];for(d=a.length;d>0;d-=4){b=a.slice(d-4<0?0:d-4,d);c.unshift(parseInt(b,2).toString(16))}return c.join("")};
function za(a,c,b,d){this.A=a;this.p=c;this.xa=b;this.ya=d}
za.prototype.k=function(a,c,b){var d=this.p.createElement("img");d.setAttribute("width",62);d.setAttribute("height",25);d.setAttribute("src",this.xa.buildUrl(b.isHttps(),"/default.gif"));d.setAttribute("class","typekit-badge");d.setAttribute("alt","Fonts by Typekit");d.setAttribute("title","Information about the fonts used on this site");d.style.position="fixed";d.style.zIndex=2E9;d.style.right=0;d.style.bottom=0;d.style.cursor="pointer";d.style.border=0;if(c.getName()!="Opera")d.style.content="none";
d.style.display="inline";d.style["float"]="none";d.style.height="25px";d.style.left="auto";d.style.margin=0;d.style.maxHeight="25px";d.style.maxWidth="62px";d.style.minHeight="25px";d.style.minWidth="62px";d.style.orphans=2;d.style.outline="none";d.style.overflow="visible";d.style.padding=0;d.style.pageBreakAfter="auto";d.style.pageBreakBefore="auto";d.style.pageBreakInside="auto";d.style.tableLayout="auto";d.style.textIndent=0;d.style.top="auto";d.style.unicodeBidi="normal";d.style.verticalAlign=
"baseline";d.style.visibility="visible";d.style.widows=2;d.style.width="65px";var f=this.p,g=this.ya.buildUrl(q,"/"+a);U(this,d,"click",function(){f.location.href=g});if(c.getName()=="MSIE"){d.style.position="absolute";var k=this;a=function(){var h=Aa(k,"scrollLeft","scrollTop"),e=Aa(k,"clientWidth","clientHeight");d.style.bottom="auto";d.style.right="auto";d.style.top=h[1]+e[1]-25+"px";d.style.left=h[0]+e[0]-3-62+"px"};U(this,this.A,"scroll",a);U(this,this.A,"resize",a)}c=c.getPlatform();if(c=="iPhone"||
c=="iPod"||c=="iPad"||c=="Android")d.style.display="none";return d};function Aa(a,c,b){var d=0,f=0;a=a.p;if(a.documentElement&&(a.documentElement[c]||a.documentElement[b])){d=a.documentElement[c];f=a.documentElement[b]}else if(a.body&&(a.body[c]||a.body[b])){d=a.body[c];f=a.body[b]}return[d,f]}function U(a,c,b,d){if(c.attachEvent){var f=a.A;c["e"+b+d]=d;c[b+d]=function(){c["e"+b+d](f.event)};c.attachEvent("on"+b,c[b+d])}else c.addEventListener(b,d,q)}var V=new P;
V.addBrowser(new O("ff35-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||(f=="Ubuntu"||f=="Linux"?j:q);if(!h)return q;return function(e,m,n,p){if(n=="Gecko"){e=/1.9.1b[1-3]{1}/;return/1.9.1/.test(p)&&
!e.test(p)}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("safari5plus-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],10);
return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m,n,p){if(e=="Safari"&&n=="AppleWebKit")if(e=/([0-9]+.[0-9]+)/.exec(p))return parseFloat(e[1])>=534.5;return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("ff36plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],
10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k))||(f=="Ubuntu"||f=="Linux"?j:q);if(!h)return q;return function(e,m,n,p){if(n=="Gecko")if(m=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(p)){e=parseFloat(m[1]);m=parseInt(m[3],10);return e>1.9||e>=1.9&&m>1}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("ie6to8-win2003-win7plus-winvista-winxp","i",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m,n,p,i,l,F){if(e=="MSIE"){if(e=/([0-9]+.[0-9]+)/.exec(m))return parseFloat(e[1])>=6&&(F===undefined||
F<9);return q}}(a,c,b,d,f,g,k)}));V.addBrowser(new O("air-osx","b",function(a,c,b,d,f,g,k){var h=q;h=h||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m){if(e=="AdobeAIR"){var n=/([0-9]+.[0-9]+)/.exec(m);if(n)return parseFloat(n[1])>=2.5}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("safariany-android2to3-ipad4-iphone4","a",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=h||function(e,m,n,p,i,l){e=/([0-9]+).([0-9]+)/.exec(l);if(i=="Android"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i==2&&e>=2||i==3&&e<1}else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){if(i=="iPad")if(e=/^([0-9]+)_([0-9]+)/.exec(l)){m=parseInt(e[2],10);return parseInt(e[1],10)==4&&m>=2}else return q;else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){if(i=="iPhone"||i=="iPod")if(e=/^([0-9]+)_([0-9]+)/.exec(l)){m=
parseInt(e[2],10);return parseInt(e[1],10)==4&&m>=2}else return q;else return q}(a,c,b,d,f,g,k);if(!h)return q;a=a=="Safari"&&b=="AppleWebKit"||a=="Unknown"&&b=="AppleWebKit"&&(f=="iPhone"||f=="iPad")?j:q;return a}));
V.addBrowser(new O("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],
10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k))||(f=="Ubuntu"||f=="Linux"?j:q);if(!h)return q;return function(e,m){if(e=="Chrome"){var n=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(m);if(n){var p=parseFloat(n[1]),i=parseInt(n[2],10);n=parseInt(n[3],10);if(p>=6)return q;else if(p>4)return j;else if(p==4&&i>249)return j;else if(p==4&&i==249&&n>=4)return j}}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("safariany-android3plus","f",function(a,c,b,d,f,g,k){var h=q;h=h||function(e,m,n,p,i,l){e=/([0-9]+).([0-9]+)/.exec(l);if(i=="Android"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i==3&&e>=1||i>3}else return q}(a,c,b,d,f,g,k);if(!h)return q;a=a=="Safari"&&b=="AppleWebKit"||a=="Unknown"&&b=="AppleWebKit"&&(f=="iPhone"||f=="iPad")?j:q;return a}));
V.addBrowser(new O("ie9plus-win7plus-winvista","d",function(a,c,b,d,f,g,k){var h=q;h=(h=h||function(m,n,p,i,l,F){m=/^([0-9]+).([0-9]+)/.exec(F);if(l=="Windows"&&m){l=parseInt(m[1],10);m=parseInt(m[2],10);return l>6||l==6&&m>=1}else return q}(a,c,b,d,f,g,k))||(f=="Windows"&&g=="6.0"?j:q);if(!h)return q;var e;if(a=="MSIE")e=k>=9;return e}));
V.addBrowser(new O("ff35-osx","b",function(a,c,b,d,f,g,k){var h=q;h=h||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m,n,p){if(n=="Gecko"){e=/1.9.1b[1-3]{1}/;return/1.9.1/.test(p)&&!e.test(p)}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("opera10-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||(f=="Ubuntu"||f=="Linux"?j:q);if(!h)return q;return function(e,m){if(e=="Opera"){var n=parseFloat(m);return n>=10.54&&n<
11.1}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("safariany-ipad5plus-iphone5plus","d",function(a,c,b,d,f,g,k){var h=q;h=(h=h||function(e,m,n,p,i,l){if(i=="iPad")return(e=/^([0-9]+)_([0-9]+)/.exec(l))?parseInt(e[1],10)>=5:q;else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){if(i=="iPhone"||i=="iPod")return(e=/^([0-9]+)_([0-9]+)/.exec(l))?parseInt(e[1],10)>=5:q;else return q}(a,c,b,d,f,g,k);if(!h)return q;a=a=="Safari"&&b=="AppleWebKit"||a=="Unknown"&&b=="AppleWebKit"&&(f=="iPhone"||f=="iPad")?j:q;return a}));
V.addBrowser(new O("safari3to5-osx","b",function(a,c,b,d,f,g,k){var h=q;h=h||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m,n,p){if(e=="Safari"&&n=="AppleWebKit")if(e=/([0-9]+.[0-9]+)/.exec(p)){e=parseFloat(e[1]);return e>=525.13&&e<534.5}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("air-linux-win","a",function(a,c,b,d,f,g,k){var h=q;h=(h=h||(f=="Windows"&&g=="Unknown"?j:q))||(f=="Ubuntu"||f=="Linux"?j:q);if(!h)return q;return function(e,m){if(e=="AdobeAIR"){var n=/([0-9]+.[0-9]+)/.exec(m);if(n)return parseFloat(n[1])>=2.5}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("chrome6plus-android3plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],
10);l=parseInt(e[3],10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k))||(f=="Ubuntu"||f=="Linux"?j:q))||function(e,m,n,p,i,l){e=/([0-9]+).([0-9]+)/.exec(l);if(i=="Android"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i==3&&e>=1||i>3}else return q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m){if(e=="Chrome"){var n=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(m);if(n)if(parseFloat(n[1])>=6)return j}}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("opera11plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k))||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],
10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k))||(f=="Ubuntu"||f=="Linux"?j:q);if(!h)return q;a=a=="Opera"?parseFloat(c)>=11.1:q;return a}));
V.addBrowser(new O("opera10-osx","b",function(a,c,b,d,f,g,k){var h=q;h=h||function(e,m,n,p,i,l){e=/^([0-9]+)(_|.)([0-9]+)/.exec(l);if(i=="Macintosh"&&e){i=parseInt(e[1],10);l=parseInt(e[3],10);return i>10||i==10&&l>=4}else return i=="Macintosh"&&l=="Unknown"?j:q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m){if(e=="Opera"){var n=parseFloat(m);return n>=10.54&&n<11.1}return q}(a,c,b,d,f,g,k)}));
V.addBrowser(new O("safari3to5-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,f,g,k){var h=q;h=(h=(h=(h=h||(f=="Windows"&&g=="5.1"?j:q))||(f=="Windows"&&g=="5.2"?j:q))||(f=="Windows"&&g=="6.0"?j:q))||function(e,m,n,p,i,l){e=/^([0-9]+).([0-9]+)/.exec(l);if(i=="Windows"&&e){i=parseInt(e[1],10);e=parseInt(e[2],10);return i>6||i==6&&e>=1}else return q}(a,c,b,d,f,g,k);if(!h)return q;return function(e,m,n,p){if(e=="Safari"&&n=="AppleWebKit")if(e=/([0-9]+.[0-9]+)/.exec(p)){e=parseFloat(e[1]);return e>=
525.13&&e<534.5}return q}(a,c,b,d,f,g,k)}));var W=new function(){this.I=[];this.r={}},Ba=new S("AllFonts",function(a,c){return c});T(W,Ba.getName())||W.I.push(Ba);
var Ca=new S("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var d=0;d<c.length;d++){var f=c[d],g=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+f;b.push(new pa(g,[f]))}a={};for(f=0;f<c.length;f++){b=c[f];d=b.charAt(1);(a[d]||(a[d]=[])).push(b)}b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(f=0;f<b.length;f++){g=b[f];for(var k=0;k<g.length;k++){var h=g[k];if(a[h]){d=d.concat(a[h]);break}}}b=d;d={};a=[];for(f=0;f<b.length;f++){g=b[f];if(!d[g]){d[g]=j;a.push(g)}}b=[];for(d=0;d<c.length;d++){f=
c[d];for(g=0;g<a.length;g++){k=a[g];k==f&&b.push(k)}}return b});T(W,Ca.getName())||W.I.push(Ca);W.r.a="AllFonts";W.r.b="AllFonts";W.r.d="AllFonts";W.r.e="AllFonts";W.r.f="AllFonts";W.r.g="AllFonts";W.r.h="AllFonts";W.r.i="DefaultFourFontsWithSingleFvdFamilies";var X=new function(){this.s={}};X.s.a=[];X.s.b=[];X.s.d=[];X.s.e=[];X.s.f=["observeddomain"];X.s.g=["observeddomain"];X.s.h=["observeddomain"];X.s.i=["observeddomain","fontmask"];
if(!window.Typekit){var Da=new N(j,"use.typekit.com","/"),Ea=(new x(navigator.userAgent,document)).parse(),Fa=new L(document,Ea),Ga=function(a,c){setTimeout(a,c)},Y=new Q(Da,Fa,Ea,document.documentElement,Ga),Z=new R(window,Fa,Ga);window.Typekit=Y;window.Typekit.load=Y.load;window.Typekit.addKit=Y.L}var Ha,Ia=o,Ja=o,Ka=o,La,$;Ha=new N(j,"use.typekit.com","/k");Ia=new N(j,"use.typekit.com","/badges");Ja=new N(j,"typekit.com","/colophons");Ka=new za(window,document,Ia,Ja);
La=new function(a,c){this.V=a;this.T=c}(Ka,o);$=new ra("sgg4mvr");$.setSecurityToken("3bb2a6e53c9684ffdc9a9aff1f5b2a628abf9b77fd94669c7b4f1a79b31fcb5328bd20895ae46aac785ee4ffcb9899177b25d9dafb4e0cf977d94b3a142e7477e06c03f78066cbc57d8875c30298c6e60ef5baf4eecd8ec7d32e07d13d5421");$.setNestedUrl(Ha);$.setKitOptions(La);$.addFontFamily(new M("nimbus-sans",["n4","i4","n7","i7"]));$.addFontFamily(new M("museo",["n3","i3","n7","n9"]));
$.addCssRule(new la([".tk-nimbus-sans"],[{value:'"nimbus-sans",sans-serif',name:"font-family"}]));$.addCssRule(new la([".tk-museo"],[{value:'"museo",serif',name:"font-family"}]));$.addBrowser(V.getBrowserById("air-linux-win"));$.addBrowser(V.getBrowserById("air-osx"));$.addBrowser(V.getBrowserById("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("chrome6plus-android3plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("ff35-linux-win2003-win7plus-winvista-winxp"));
$.addBrowser(V.getBrowserById("ff35-osx"));$.addBrowser(V.getBrowserById("ff36plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("ie6to8-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("ie9plus-win7plus-winvista"));$.addBrowser(V.getBrowserById("opera10-linux-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("opera10-osx"));$.addBrowser(V.getBrowserById("opera11plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("safari3to5-osx"));
$.addBrowser(V.getBrowserById("safari3to5-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("safari5plus-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("safariany-android2to3-ipad4-iphone4"));$.addBrowser(V.getBrowserById("safariany-android3plus"));$.addBrowser(V.getBrowserById("safariany-ipad5plus-iphone5plus"));$.setFontFilterSet(W);if(Z&&Z.A.__webfonttypekitmodule__){Z.L($);Z.load()}else window.Typekit.addKit($);
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=sgg4mvr&ht=tk&h={host}&f=10794.10796.10793.10795.1983.1981.8542.1984&a=564892&_={_}"};
;(function(window,document,undefined){
function g(a,b){this.q=a;this.f=b||a;this.c=this.f.document}g.prototype.createElement=function(a,b,d){a=this.c.createElement(a);if(b)for(var c in b)b.hasOwnProperty(c)&&("style"==c?a.style.cssText=b[c]:a.setAttribute(c,b[c]));d&&a.appendChild(this.c.createTextNode(d));return a};function k(a){return a.f.location.hostname||a.q.location.hostname}function m(a){this.n=a}m.prototype.toString=function(){return encodeURIComponent(k(this.n))};function p(a,b){this.e=b}
p.prototype.toString=function(){for(var a=[],b=0;b<this.e.length;b++)for(var d=this.e[b],c=d.o,d=d.o,f=0;f<c.length;f++){var e;a:{for(e=0;e<d.length;e++)if(c[f]===d[e]){e=!0;break a}e=!1}a.push(e?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(c=a.length;0<c;c-=4)b.unshift(parseInt(a.slice(0>c-4?0:c-4,c),2).toString(16));return b.join("")};function q(a){this.t=a}
q.prototype.m=function(a){var b=a||{};a=this.t.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,f){return f&&b[c]?"/"+b[c].join("/"):b[c]||""});a.match(/^\/\//)&&(a="https:"+a);return a.replace(/\/*\?*($|\?)/,"$1")};function r(a,b,d,c,f,e,h){this.r=a;this.p=b;this.b=d||[];this.g=c||null;this.s=f||null;this.version=e||null;this.h=h||null}
r.prototype.send=function(a,b,d){var c=new q("//p.typekit.net/p.gif?s={service}&k={token}&app={app}&ht={hosting}&h={host}&f={variations}&a={account}&sl={stylesheetLoadTime}&fl={fontLoadTime}&js={version}&_={_}"),f=encodeURIComponent((window.__adobewebfontsappname__||this.h||"").toString().substr(0,20));a=encodeURIComponent(k(a));var e=[],h=[];window.Typekit.fonts||(window.Typekit.fonts=[]);for(var h=window.Typekit.fonts,l=0;l<this.b.length;l++){for(var u=!1,n=0;n<h.length;n++)if(this.b[l]===h[n]){u=
!0;break}u||(e.push(this.b[l]),h.push(this.b[l]))}e.length&&s(c.m({service:this.r,token:this.s,app:f,hosting:this.p,host:a,variations:e.join("."),account:this.g,stylesheetLoadTime:b,fontLoadTime:d,version:this.version,_:(+new Date).toString()}))};function s(a){var b=new Image(1,1),d=!1;b.src=a;b.onload=function(){d=!0;b.onload=null};setTimeout(function(){d||(b.src="about:blank",b.onload=null)},3E3)}var t={};t.a=t.d=t.l=t.j=function(){return[]};t.i=function(a,b,d){return[new m(a),new p(0,d)]};
t.k=function(a){return[new m(a)]};window.Typekit||(window.Typekit={});var v=window.Typekit.config,w=new g(window),x=new r(v.ps,v.ht,v.fi,v.a,v.kt,v.js,v.l),y=!1,z=window.Typekit.load;window.Typekit.load=function(){z&&z.apply(window.Typekit,arguments);if(!y)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var d=a[b].getAttribute("href");if(d&&0<=d.indexOf("use.typekit")){x.send(w);y=!0;break}}};
})(this,document);
