/*!CK:1095506353!*//*1444813538,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["sVqQk"]); }

__d("ImageExtensions",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={GIF:"gif",JPG:"jpg",PNG:"png",ICO:"ico",BMP:"bmp",WEBP:"webp",BEST:"best"};},null,{});
__d("VideoCreatorProductType",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={LEGACY:0,UNSPECIFIED:1,CORE_VIDEOS:2,LOOPS:3,ANIMATED_GIFS:4,SLIDESHOW:5,PROFILE_VIDEO:6,SPHERICAL:7};},null,{});
__d('NotificationPhotoThumbnail',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(j){if(!j.media||!j.style_list||!j.style_list.length)return null;switch(j.style_list[0]){case 'new_album':case 'album':case 'application':case 'photo':case 'video':case 'video_autoplay':case 'video_inline':return j.media.image;default:return null;}}var i={getThumbnail:function(j,k,l){var m;if(j&&j.length){j.some(function(q){m=h(q);if(m)return true;return false;});if(m)return m;}if(l){var n=l.relevant_comments;if(n&&n.length){var o=n[0].attachments;if(o&&o.length){m=h(o[0]);if(m)return m;}}}if(k){var p=k.attachments;if(p&&p.length)return h(p[0]);}return null;}};f.exports=i;},null);
__d('NotificationListPropTypes',['React'],function a(b,c,d,e,f,g,h){'use strict';if(c.__markCompiled)c.__markCompiled();var i=h.PropTypes,j={negativeTracking:i.object,tracking:i.string,useChevron:i.bool,chevronType:i.string,notifs:i.object,afterScroll:i.func,onChevronShow:i.func,onChevronHide:i.func,canFetchMore:i.bool,hiddenState:i.object,readState:i.object,showingChevron:i.bool,paused:i.bool,maxHeight:i.number,shouldScroll:i.bool,upsell:i.object};f.exports=j;},null);
__d('BanzaiNectar',['Banzai'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(k){return {log:function(l,m,n){var o={e:m,a:n};h.post('nectar:'+l,o,k);}};}var j=i();j.create=i;f.exports=j;},null);
__d('whitelistObjectKeys',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i,j){var k={},l=Array.isArray(j)?j:Object.keys(j);for(var m=0;m<l.length;m++)if(typeof i[l[m]]!=='undefined')k[l[m]]=i[l[m]];return k;}f.exports=h;},null);
__d('ModalMask',['DOM'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=null,j=0,k={show:function(){j++;if(!i){i=h.create('div',{id:'modalMaskOverlay'});h.appendContent(document.body,i);}},hide:function(){if(j){j--;if(!j&&i){h.remove(i);i=null;}}},getNode:function(){return i;}};f.exports=k;},null);
__d('AccessibilityLogger',['AsyncSignal','Cookie'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j={COOKIE:'a11y',DECAY_MS:6*60*60*1000,DEFAULT:{sr:0,'sr-ts':Date.now(),jk:0,'jk-ts':Date.now(),kb:0,'kb-ts':Date.now(),hcm:0,'hcm-ts':Date.now()},getCookie:function(){var k=j.DEFAULT,l=i.get(j.COOKIE);if(l){l=JSON.parse(l);for(var m in k)if(m in l)k[m]=l[m];}return k;},logKey:function(k,l){var m=j.getCookie();m[k]++;var n=Date.now();if(n-m[k+'-ts']>j.DECAY_MS){new h('/ajax/accessibilitylogging',{eventName:l,times_pressed:m[k]}).send();m[k+'-ts']=n;m[k]=0;}i.set(j.COOKIE,JSON.stringify(m));},logHCM:function(){j.logKey('hcm','hcm_users');},logSRKey:function(){j.logKey('sr','sr_users');},logJKKey:function(){j.logKey('jk','jk_users');},logFocusIn:function(){j.logKey('kb','kb_users');}};f.exports=j;},null);
__d('XUIBadge',['CSS','DOM','cx','invariant'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();function l(n){return parseInt(n,10)===n;}function m(n){'use strict';this.target=n.target;this.count=n.count;this.maxcount=n.maxcount;}m.prototype.getCount=function(){'use strict';return this.count;};m.prototype.setCount=function(n){'use strict';!l(n)?k(0):undefined;!(n>=0)?k(0):undefined;this.count=n;h.conditionClass(this.target,'hidden_elem',this.count===0);if(n>this.maxcount){i.setContent(this.target,this.maxcount+'+');h.addClass(this.target,"_5ugi");}else{i.setContent(this.target,n);h.removeClass(this.target,"_5ugi");}};m.prototype.setLegacyContent=function(n){'use strict';if(typeof n==='string'){h.conditionClass(this.target,'hidden_elem',n==0);i.setContent(this.target,n);h.removeClass(this.target,"_5ugi");}else this.setCount(n);};m.prototype.increment=function(){'use strict';this.setCount(this.getCount()+1);};f.exports=m;},null);
__d('VideoUploadFile',['fileSlice','ImageExtensions','VideoCreatorProductType','VideoUploadFeatureDetector'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();function l(m,n,o,p){'use strict';this.$VideoUploadFile1=m;this.$VideoUploadFile2=n;this.$VideoUploadFile3=o;this.$VideoUploadFile4=p;}l.fromFile=function(m){'use strict';var n=l.getExtensionFromFileName(m.name);return new this(null,m,m.size,n);};l.fromFileInput=function(m){'use strict';var n=null,o=null,p=l.getExtensionFromFileInput(m);if(k.supportsFileAPI()&&m.files.length){n=m.files[0];o=n.size;}return new this(m,n,o,p);};l.prototype.getFileInput=function(){'use strict';return this.$VideoUploadFile1;};l.prototype.getFile=function(){'use strict';return this.$VideoUploadFile2;};l.prototype.getSize=function(){'use strict';return this.$VideoUploadFile3;};l.prototype.getExtension=function(){'use strict';return this.$VideoUploadFile4;};l.prototype.getCreatorProduct=function(){'use strict';if(this.$VideoUploadFile4===i.GIF)return j.ANIMATED_GIFS;return j.CORE_VIDEOS;};l.prototype.getChunk=function(m,n){'use strict';return this.$VideoUploadFile2?h.call(this.$VideoUploadFile2,m,n):null;};l.getExtensionFromFileInput=function(m){'use strict';return this.getExtensionFromFileName(m.value);};l.getExtensionFromFileName=function(m){'use strict';return m.indexOf('.')!=-1?m.split('.').pop().toLowerCase():'';};f.exports=l;},null);
__d("XPrivacyRemindersDismissController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/privacy\/reminders\/dismiss\/",{type:{type:"String",required:true},log_plite:{type:"Bool",defaultValue:false}});},null,{});