var e=window.FT=function(){function a(a){e.include("http://cdn.flashtalking.com/frameworks/js/api/2/4/testing.js",function(){var c={method:"init",msg:e.testing(a)};b.receiveMessages({data:JSON.stringify(c)})})}var b=this,c;b.version=2.4;b.placementProperties={};b.manifestProperties={};b.firedStandardEvents={};b.hasLoaded=!1;b.testMode=!1;b.notTop=window!==window.top;b.politeloadFired=!1;var d={};try{d=window.localStorage}catch(f){}try{b.placementProperties=JSON.parse(window.name),window.name=""}catch(g){}e.makeDispatcher(this);
window!==window.top&&-1===location.search.indexOf("test")||e.preventFTTestMode?e.addListener(window,"message",function(a){b.receiveMessages(a)}):b.testMode=!0;/^http:\/\/www\.flashtalking\.net\/uploads\//.test(location.href)&&(b.tia=!0);e.addListener(window,"click",function(a){b.clickManager.call(b,a)},!1);e.listen(window,"touchstart",function(){b.send("interaction")});b.testMode?b.addEventListener("load",function(){b.dispatchEvent("politeload");b.politeloadFired=!0}):b.addEventListener("politeload",
function(){b.politeloadFired=!0});"loading"!==document.readyState?(b.dispatchEvent("DOMLoaded"),"complete"===document.readyState||"loaded"===document.readyState?b.dispatchEvent("load"):e.addListener(window,"load",function(a){b.dispatchEvent("load",a)})):e.addListener(document,"readystatechange",function(){"interactive"===document.readyState?b.dispatchEvent("DOMLoaded"):b.dispatchEvent("load")});for(c in e.initialisation)e.initialisation[c].call(this);e.addEventListener("manifest",function(c){var f=
{location:location.href,guid:d&&d.ftGUID?d.ftGUID:!1};b.manifestProperties=c;b.testMode?a(c):b.send("ready",f)});e.include("manifest.js")};e.query=function(a){var b=null;return b=a.match(/#[a-z0-9_\-]+$/i)?document.querySelector(a):document.querySelectorAll(a)};
e.include=function(a,b){var c=document.createElement("script");switch(a.toLowerCase()){case "storelocator":a="http://cdn.flashtalking.com/frameworks/js/storeLocator/storeLocator.js";break;case "touch":a="http://cdn.flashtalking.com/frameworks/js/touch/1/touch.js";break;case "carousel":a="http://cdn.flashtalking.com/frameworks/js/carousel/FTcarousel.js";break;case "preloader":case "subloader":a="http://cdn.flashtalking.com/frameworks/js/subloader/subloader.js"}c.src=a;document.getElementsByTagName("head")[0].appendChild(c);
c.onload=function(){"function"===typeof b&&b()}};e.addListener=function(a){return"undefined"!==typeof a.addEventListener?function(b,a,d){b.addEventListener(a,d,!1)}:function(b,a,d){b.attachEvent("on"+a,d,!1)}}(window);e.listen=e.addListener;e.removeListener=function(a){return"undefined"!==typeof a.removeEventListener?function(b,a,d){b.removeEventListener(a,d,!1)}:function(b,a,d){b.detachEvent("on"+a,d,!1)}}(window);e.manifest=e.manifest=function(a){e.dispatchEvent("manifest",a)};
e.initialisation={};e.ajaxDefaults={async:!0,method:"GET",context:window,complete:function(){},params:null,test:function(){}};e.ajax=function(a,b){var c=new XMLHttpRequest,d=window.FT.ajaxDefaults,f;for(f in b)d[f]=b[f];c.onreadystatechange=function(b){4===c.readyState&&d.complete.call(d.context,c,b,d.params)};!0!==d.context.testMode?(c.open(d.method,a,d.async),c.send()):d.test.call(d.context,d.params)};var q=document.getElementsByTagName("head")[0],r=document.createElement("link");r.type="text/css";
r.rel="stylesheet";r.href=/^http:\/\/www\.flashtalking\.net\/uploads\//.test(location.href)||window===window.top?"http://cdn.flashtalking.com/frameworks/css/base.css":"/frameworks/css/base.css";q?q.appendChild(r):document.body.insertAdjacentHTML("beforeBegin","<head>"+r.outerHTML+"</head>");
e.prototype.receiveMessages=function(a){var b={method:"",msg:""},c=[];try{b=JSON.parse(a.data)}catch(d){}if("init"!==b.method||this.hasLoaded)this[b.method]&&this.hasLoaded&&(c=b.msg?"Array"===b.msg.constructor.name?b.msg:[b.msg]:null,this[b.method].apply(this,c));else{this.hasLoaded=!0;for(var f in b.msg)this.placementProperties[f]=b.msg[f];b.msg.newGUID&&this.newGUID(b.msg);this.dispatchEvent("ready",b)}};e.prototype.dispatch=function(a){this.dispatchEvent(a.ev||a,a.msg)};
e.prototype.send=function(a,b){var c={method:a,msg:b};this.notTop&&window.parent.postMessage(JSON.stringify(c),"*")};e.prototype.get=function(a){var b="";"undefined"!==typeof this.placementProperties[a]&&(b=this.placementProperties[a]);return b};e.prototype.getManifest=function(a){var b="";"undefined"!==typeof this.manifestProperties[a]&&(b=this.manifestProperties[a]);return b};e.prototype.checkLoaded=function(){return this.hasLoaded};
e.prototype.tracker=function(a,b,c){for(var d=this.manifestProperties.trackingEvents,f=d.length||[],g=null;f--;)if(a===d[f].name){g=101+f;if("standard"===d[f].type){if(this.firedStandardEvents[g])return;this.firedStandardEvents[g]=!0}break}g&&this.send("tracker",{type:"custom",num:g,value:b,string:c})};e.prototype.clickManager=function(a){this.send("tracker",{type:"clickmap",x:a.pageX,y:a.pageY})};
e.prototype.getClickTag=function(a,b){var c="clickTag"+(a||""),d=this.get("clicks"),f="",f=/^(http|https|sms|tel|mailto|smsto):/;if(this.hasLoaded)return f=b?f.test(b)?this.tia||this.testMode?d[c]+"&APPEND=false&DYNCTTEST="+b:d[c].substr(0,d[c].lastIndexOf("http"))+b:this.tia||this.testMode?d[c]+"&APPEND=true&DYNCTTEST="+b:d[c]+b:d[c];this.error("getClickTag","get ClickTag was called before the myFT.hasLoaded == true")};
e.prototype.clickTag=function(a,b){var c="";this.hasLoaded?(c=this.getClickTag(a,b),this.send("interactionComplete"),"ft"===this.get("api")?/((sms|tel|mailto|spotify|facetime):|https?:\/\/maps\.)/i.test(c)&&/ip(ad|hone|od)/i.test(navigator.userAgent)?window.open(c,"_top"):window.open(c,"_blank"):this.send("open",c)):this.error("clickTag","clickTag method called before hasLoaded === true")};
e.prototype.applyClickTag=function(a,b,c){function d(a){f.clickTag(b,c);f.clickManager(a);a.stopPropagation?a.stopPropagation():"undefined"!==typeof a.cancelBubble&&(a.cancelBubble=!0)}var f=this;f.hasLoaded?(a.style.cursor="pointer",this.constructor.addListener(a,"click",d,!1)):f.addEventListener("ready",function(){f.applyClickTag(a,b,c)})};
e.prototype.applyButton=function(a,b){function c(a){d.clickManager(a);a.stopPropagation?a.stopPropagation():"undefined"!==typeof a.cancelBubble&&(a.cancelBubble=!0);b.call(d,a)}var d=this;d.hasLoaded?(this.constructor.addListener(a,"click",c,!1),a.style.cursor="pointer"):d.addEventListener("ready",function(){d.applyButton(a,b)})};
e.prototype.absorbSwipes=function(a){function b(b){b.preventDefault&&b.preventDefault()}this.send("preventSwipes",!!a);!this.absorbSwipesSet&&a?e.addListener(window,"touchmove",b):a||e.removeListener(window,"touchmove",b)};e.prototype.newGUID=function(a){var b=document.createElement("iframe");a.a&&(b.src=a.d,b.style.cssText="display:none",document.body.appendChild(b));a.a&&"undefined"!==typeof localStorage&&(localStorage.j=a.c)};
e.prototype.error=function(a,b){var c="ftError in method "+a+": "+b;if(!window.mocha&&!window.sinon&&!window.chai)return"ft"!==this.get("api")&&((new Image).src="http://a.b.FTerrorIMG/"+c),this.send("error",c),!1};
e.initialisation.communicate=function(){function a(a){b.linkedAds[a.name]=!0;for(var d in b.linkedAds)if(!b.linkedAds[d])return;b.dispatchEvent("linkready")}var b=this;e.addEventListener("manifest",function(c){if(c.communication){var d=c.communication.linked,f=d.length;for(b.linkedAds={};f--;)b.linkedAds[d[f]]=!1;b.send("communicate",{type:"register",name:c.communication.name});b.addEventListener("linkedad",a)}})};e.prototype.talk=function(a,b){this.send("communicate",{type:"talk",name:a,msg:b})};
e.prototype.communicate=function(a){var b=a.type?{type:a.type}:null;"talk"===a.type?(b.from=a.name,b.msg=a.msg):(b.type="linkedad",b.name=a.name);this.dispatchEvent(b.type,b)};
e.prototype.expand=function(a){var b=a&&"undefined"===typeof a.type?a:this.getManifest("expand");!a||a.type||a.customClosePosition?(this.expandProperties||a&&!a.type||this.setExpandProperties(this.getManifest("expand")),b=this.expandProperties):this.setExpandProperties(a)&&(b=this.expandProperties);b&&(this.getManifest("expand")?(this.send("expand",b),this.dispatchEvent("expand",b)):this.error("expand","No expand component detailed in the manifest"))};
e.prototype.resize=function(a){var b;a&&!a.type?this.setResizeProperties(a)&&(b=this.resizeProperties):(this.resizeProperties||a||this.setResizeProperties(this.getManifest("expand")),b=this.resizeProperties);b?this.expand(b):this.error("resize","resize method not successfully executed - invalid argument or setResizeProperties not previously called")};e.prototype.contract=function(){this.send("contract",{});this.dispatchEvent("contract");document.body.style.margin=0};
e.prototype.setExpandProperties=function(a){var b,c=/(width|height|offsetX|offsetY|indentDown|indentAcross)/,d=[];if(a&&"object"===typeof a){for(b in a)if(c.test(b))d.push(b);else if("fullscreen"===b&&a[b]){d.length=4;break}if(4<=d.length)return void 0===a.useCustomClose&&(a.useCustomClose=void 0===this.customClose?this.expandProperties&&this.expandProperties.useCustomClose||!1:this.customClose),void 0!==a.offsetX&&(a.indentAcross=a.offsetX,a.indentDown=a.offsetY),this.expandProperties=a,!0;this.error("setExpandProperties",
"the properties object lacked the minimum requirements to set the expandProperties object {width: number, height: number, offsetX: number, offsetY: number}");return!1}this.error("setExpandProperties","the properties object was not present or not a valid object")};
e.prototype.setResizeProperties=function(a){var b,c=/(width|height|offsetX|offsetY|indentDown|indentAcross)/,d=[];if(a&&"object"===typeof a){for(b in a)c.test(b)&&d.push(b);if(4<=d.length)return a.customClosePosition||(a.customClosePosition="top-right"),"undefined"!==typeof a.offsetX&&(a.indentAcross=a.offsetX,a.indentDown=a.offsetY),this.resizeProperties=a,!0;this.error("setResizeProperties","the argument passed in lacked the minimum requirements to set the resizeProperties object {width: number, height: number, offsetX: number, offsetY: number}")}};
e.initialisation.instant=function(){function a(){var a=b.get("testConf"),d=b.get("confID"),f="../"+b.get("creativeID")+".json",g=b.get("serveDOM"),m=b.get("mvt");a?f=a+d:m&&(f="../mv"+d+".json");e.ajax(f,{context:b,complete:function(a){var c={},d,f="";if(200===a.status){try{c=JSON.parse(a.responseText)}catch(h){}for(d in c)"string"===typeof c[d].value&&(b.instantAds[d]=c[d].value),"string"!==typeof c[d].type||"image"!==c[d].type.toLowerCase()&&"richload"!==c[d].type.toLowerCase()||(f="image"===c[d].type.toLowerCase()?
"instantAssets":"richLoads",b.instantAds[d]=""===g?"../../"+f+"/"+c[d].value:g+"/"+b.get("cID")+"/"+f+"/"+c[d].value)}b.instantAdsLoaded=!0;b.dispatchEvent("instantads")},test:function(){b.instantAdsLoaded=!0;b.dispatchEvent("instantads")}})}var b=this;b.instantAdsLoaded=!1;e.addEventListener("manifest",function(c){if(c.instantAds){var d=c.instantAds,f=c.videos;c=c.instantAds.length;var g=0;for(b.instantAds={};c--;)if(b.instantAds[d[c].name]=d[c]["default"],"video"===d[c].type.toLowerCase())for(g=
f.length;g--;)b.instantAds[d[c].name]=d[c].name===f[g].name?f[g].ref:b.instantAds[d[c].name];b.addEventListener("ready",a)}})};e.makeDispatcher=function(a){a.callbacks={};a.addEventListener=e.makeDispatcher.addEventListener;a.removeEventListener=e.makeDispatcher.removeEventListener;a.dispatchEvent=e.makeDispatcher.dispatchEvent;a.clearEvent=e.makeDispatcher.clearEvent;a.once=e.makeDispatcher.once};
e.makeDispatcher.addEventListener=function(a,b){this.callbacks[a]=this.callbacks[a]||[];this.callbacks[a].unshift(b);if(this instanceof e)switch(a){case "instantads":this.instantAdsLoaded&&b(this.instantAds);break;case "richload":this.richLoadsLoaded&&b(this.richLoads);break;case "load":"complete"!==document.readyState&&"loaded"!==document.readyState||b();break;case "DOMLoaded":"loading"!==document.readyState&&b();break;case "politeload":this.politeloadFired&&b()}};
e.makeDispatcher.once=function(a,b){function c(){b.apply(this,arguments);this.removeEventListener(a,c)}this.addEventListener(a,c)};e.makeDispatcher.removeEventListener=function(a,b){for(var c=this.callbacks[a]||[],d=c.length;d--;)if(c[d].toString()===b.toString()){c.splice(d,1);break}};e.makeDispatcher.dispatchEvent=function(){var a;a=arguments;for(var b=a.length,c=[];b--;)c[b]=a[b];a=c;b=a.shift();b=this.callbacks[b]||[];for(c=b.length;c--;)b[c].apply(this,a)};e.makeDispatcher.clearEvent=function(a){delete this.callbacks[a]};
e.initialisation.richLoad=function(){function a(){function a(b){var c;return window.attachEvent&&!window.addEventListener?(c=document.createElement("div"),c.id=b.id,c.className=b.className,c.style.cssText=b.style.cssText,b.replaceNode(c),document.querySelector("#"+b.id)):b}function d(a,c){function d(){var a,c=0,f=0;for(a in k)c++,k[a].loaded?(g[a]=k[a].loaded,f++):g[a]=!1;f===c&&(b.richLoadsLoaded=!0)}function f(){b.dispatchEvent("richload",g)}var g={};"loading"===c.readyState?e.addListener(c,"DOMContentLoaded",
function(){b.richLoads[a].loaded=!0;d();f()}):(b.richLoads[a].loaded=!0,d(),f())}function f(a){e.addListener(k[a].frame.contentWindow.document,"click",function(c){c={pageX:c.pageX,pageY:c.pageY};c.pageX+=p[a].x;c.pageY+=p[a].y;b.clickManager(c)})}function g(b,a){for(var c=b.offsetLeft,d=b.offsetTop;null!==b.offsetParent;)b=b.offsetParent,c+=b.offsetLeft,d+=b.offsetTop;p[a]={x:c,y:d}}function m(b){return function(a){var c=null;return c=a.match(/^#\w+$/)?b.document.querySelector(a):b.document.querySelectorAll(a)}}
var k=b.richLoads,l=null,n=b.get("serveDOM"),p={},h;for(h in k)document.querySelector("#"+h)&&/richload/i.test(document.querySelector("#"+h).tagName)?(l=a(document.querySelector("#"+h)),k[h].frame.src=n?n+"/"+b.get("cID")+"/"+k[h].src:"../../richLoads/"+k[h].src,k[h].frame.name=h,k[h].loaded=!1,l.appendChild(k[h].frame),d(h,k[h].frame.contentWindow.document),k[h].frame.contentWindow.myFT=this,k[h].frame.contentWindow.FT=new e.Instance,k[h].frame.contentWindow.FT.query=m(k[h].frame.contentWindow),
g(l,h),f(h)):b.error("initialisation.richLoad","no richload container with id '"+h+"' available to insert content into")}var b=this;b.richLoadsLoaded=!1;e.Instance=function(){};e.Instance.prototype=e;e.addEventListener("manifest",function(c){if(c.richLoads||c.instantAds){var d=c.richLoads,f=c.instantAds;c=Math.max(d?d.length:0,f?f.length:0);var g="";for(b.richLoads={};c--;)d&&d[c]&&(b.richLoads[d[c].name]={src:d[c].src},g="basic"),f&&f[c]&&"richload"===f[c].type.toLowerCase()&&(b.richLoads[f[c].name]=
{src:f[c]["default"]},g="dynamic");for(c in b.richLoads)d=document.createElement("iframe"),d.style.width="100%",d.style.height="100%",d.frameBorder=0,d.scrolling="no",d.setAttribute("margin","0"),d.setAttribute("allowTransparency","true"),d.name=c,b.richLoads[c].frame=d;"basic"===g?b.addEventListener("ready",a):"dynamic"===g&&b.addEventListener("instantads",a)}})};
e.testing=function(a){a=a.clickTagCount;for(var b=1,c={b:{g:"http://www.flashtalking.net/helpSystem/TiA/?n=0"},h:"0",i:"0",f:"0",l:"",e:"ft",k:!1,c:"0",a:!1,d:""};20>=b;b++)c.b["clickTag"+b]="http://www.flashtalking.net/helpSystem/TiA/?n="+(b<=a?b:"error");return c};e.Video=function(){this.filepath=this.video=null;this.hasPlayedThrough=this.hasPlayed=!1};e.Video.prototype.play=function(a){this.video.play(a)};e.Video.prototype.stop=e.Video.prototype.pause=function(a){this.video.pause(a)};
e.Video.prototype.restart=function(a){this.pause(a);try{this.video.currentTime=0}catch(b){}this.play(a)};e.Video.prototype.mute=function(){this.savedVolume=0<this.video.volume?this.video.volume:this.savedVolume||1;this.video.volume=0;this.video.muted=!0};e.Video.prototype.unmute=function(){this.video.muted=!1;this.video.volume=this.savedVolume||1};
e.Video.prototype.loadVid=function(){var a=document.createElement("source"),b=document.createElement("source"),c=("https:"===location.protocol?"https://secure":"http://cdn")+".flashtalking.com/"+this.filepath;a.src=c+".mp4";a.type="video/mp4";b.src=c+".webm";b.type="video/webm";this.video.appendChild(a);this.video.appendChild(b)};e.prototype.videos={};
e.prototype.insertVideo=function(a){var b=this,c={video:"video1",preload:"metadata",poster:"",controls:!1,autoplay:!1,clickTag:!1,muted:!1},d=document.createElement("video"),f;if(a)if(a.video)if(a.parent)if("object"!==typeof a.parent)b.error("insertVideo","The parent, defined in the settings argument, should be an HTML Div Element");else{if(d.canPlayType||/phantomjs/i.test(navigator.userAgent)){for(f in a)c[f]=a[f];c.width&&(d.width=c.width);c.height&&(d.height=c.height);c.parent.appendChild(d);a.clickTag?
d.addEventListener("click",function(c){c.stopPropagation&&c.stopPropagation();b.clickManager(c);b.clickTag("true"===a.clickTag.toString()?0:a.clickTag)}):d.addEventListener("click",function(a){a.stopPropagation&&a.stopPropagation();b.clickManager(a)});try{d.setAttribute("preload",c.preload),d.setAttribute("autobuffer","false"),d.setAttribute("muted",c.muted),d.setAttribute("poster",c.poster),c.autoplay&&d.setAttribute("autoplay",c.autoplay),c.controls&&d.setAttribute("controls",c.controls)}catch(g){}return b.applyVideo(d,
c.video)}b.dispatchEvent("videofail")}else b.error("insertVideo","There was no parent element defined in the settings argument");else b.error("insertVideo","The settings argument did not contain a video name for referencing against the manifest or it was falsey");else b.error("insertVideo","No settings object was passed to the insertVideo method")};
e.prototype.applyVideo=function(a,b){function c(){if(f.getManifest("filename")&&!m){var a=f.getManifest("instantAds"),l=f.getManifest("videos"),n=a?a.length:null,p;if(a)if(f.instantAdsLoaded){for(;n--;)if("video"===a[n].type.toLowerCase()&&a[n].name===b){for(p=l.length;p--;)if(l[p].name===b){g.filepath=f.instantAds[b];m=!0;g.loadVid();return}f.error("applyVideo","Instant video name '"+b+"' has no matching item in the Video component of the manifest")}g.filepath||(g.filepath=d(l),m=!0,g.loadVid())}else f.addEventListener("instantads",
c);else g.filepath=d(l),m=!0,g.loadVid()}else e.addEventListener("manifest",c),m||f.addEventListener("instantads",c)}function d(a){for(var c=a.length;c--;)if(a[c].name===b)return a[c].ref}var f=this,g=new e.Video,m=!1;g.video=a;c();f.getManifest("filename")?f.registerVideo(a,b):e.addEventListener("manifest",function(){f.registerVideo(a,b)});return f.videos[b]=g};
e.prototype.registerVideo=function(a,b){function c(a){g.send("tracker",{type:"video",id:n,event:a,duration:p});g.dispatchEvent("video",{m:b,id:n,event:a})}function d(){var d=a.currentTime,f=a.duration;p=Math.floor(10*f);if(0!==a.currentTime)switch(l){case 0:c("starts");g.videos[b].hasPlayed=!0;l++;break;case 1:d>0.25*f&&(c("25%"),l++);break;case 2:d>0.5*f&&(c("50%"),l++);break;case 3:d>0.75*f&&(c("75%"),l++);break;case 4:d>=f&&(c("100%"),g.videos[b].hasPlayedThrough=!0,l++)}}function f(){k||c(m?"replay":
"init");m&&(k=!0);m=!0}var g=this,m=!1,k=!1,l=0,n=function(a){var b=g.getManifest("videos"),c=b.length;if(c){for(;c--;)if(a===b[c].name)return c+1;return"No matching video name in the manifest's Video array"}return"No videos included in the manifest's Video array"}(b),p;"number"===typeof n?(a.addEventListener("play",f),a.addEventListener("timeupdate",d)):g.error("registerVideo",n)};e.makeDispatcher(e);
