FT.manifest({
	"filename":"main.html",
	"width":728,
	"height":90,
	"clickTagCount":1,
	"instantAds":[
		{"name":"IA_clickTag_url", "type":"text", "default":"http://www.telstra.com.au/"},
		{"name":"IA_bg_grad", "type":"text", "default":"#5A1992,#00B9FF"},
		{"name":"IA_logo", "type":"image", "default":"logo_728x90.png"},
		{"name":"IA_cta_text", "type":"text", "default":""},
		{"name":"IA_cta_textColor", "type":"text", "default":"#004592"},
		{"name":"IA_cta_arrowColor", "type":"text", "default":"#004592"},
		{"name":"IA_prodImgFr1", "type":"image", "default":"1x1.png"},
		{"name":"IA_headlineFr1_fontSize", "type":"text", "default":"19"},
		{"name":"IA_headlineFr1_letterSpacing", "type":"text", "default":"0"},
		{"name":"IA_headlineFr1_lineHeight", "type":"text", "default":"16"},
		{"name":"IA_headlineFr1_text", "type":"text", "default":""},
		{"name":"IA_subHeadlineFr1_fontSize", "type":"text", "default":"12"},
		{"name":"IA_subHeadlineFr1_letterSpacing", "type":"text", "default":"0"},
		{"name":"IA_subHeadlineFr1_lineHeight", "type":"text", "default":"11"},
		{"name":"IA_subHeadlineFr1_text", "type":"text", "default":""},
		{"name":"IA_legalFr1_text", "type":"text", "default":""},
		{"name":"IA_prodImgFr2", "type":"image", "default":"1x1.png"},
		{"name":"IA_headlineFr2_fontSize", "type":"text", "default":"19"},
		{"name":"IA_headlineFr2_letterSpacing", "type":"text", "default":"0"},
		{"name":"IA_headlineFr2_lineHeight", "type":"text", "default":"16"},
		{"name":"IA_headlineFr2_text", "type":"text", "default":""},
		{"name":"IA_subHeadlineFr2_fontSize", "type":"text", "default":"12"},
		{"name":"IA_subHeadlineFr2_letterSpacing", "type":"text", "default":"0"},
		{"name":"IA_subHeadlineFr2_lineHeight", "type":"text", "default":"11"},
		{"name":"IA_subHeadlineFr2_text", "type":"text", "default":""},
		{"name":"IA_legalFr2_text", "type":"text", "default":""},
		{"name":"IA_prodImgFr3", "type":"image", "default":"1x1.png"},
		{"name":"IA_headlineFr3_fontSize", "type":"text", "default":"19"},
		{"name":"IA_headlineFr3_letterSpacing", "type":"text", "default":"0"},
		{"name":"IA_headlineFr3_lineHeight", "type":"text", "default":"16"},
		{"name":"IA_headlineFr3_text", "type":"text", "default":""},
		{"name":"IA_valStackFr3_pricePoint", "type":"text", "default":""},
		{"name":"IA_valStackFr3_description_fontSize", "type":"text", "default":"11"},
		{"name":"IA_valStackFr3_description_letterSpacing", "type":"text", "default":"0"},
		{"name":"IA_valStackFr3_description_lineHeight", "type":"text", "default":"12"},
		{"name":"IA_valStackFr3_description_per", "type":"text", "default":""},
		{"name":"IA_valStackFr3_description_text", "type":"text", "default":""},
		{"name":"IA_legalFr3_text", "type":"text", "default":""}
	]
});