// v:12.1.4
var skimlinks_domain = 'wordpress.redirectingat.com';
var skimlinks_legacy_support = true;
var skimlinks_cookie_sync_optout = true;
var skimlinks_audience_optout = true;
var skimlinks_dwell_tracking = false;
var skimwords_instant = true;
var skimlinks_first_party_na = false;
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var skimlinks_replace_timeout = 300;
var skimlinks_legacy_click_handlers = false;
var skimlinks_affiliate_unknown_links = true;
var noskimproducts = true;
if (typeof noskimwords === "undefined") {
var noskimwords = true;
}
var noskoupon = true;
var skimlinks_pub_id = '725X1342';

(function(f){var Ec,Fc,Ka,V;V=function(){var a,b,c,d,e,g,f,i,I,h,k,s,j,u,m,n;if(V)return V;m={lotame:{url:"//bcp.crwdcntrl.net/5/c=7507/pe=y?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:432E6},blue_kai:{url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",resyncAfter:3456E5},mediamath:{url:"//pixel.mathtag.com/sync/img?redir=http%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",
resyncAfter:2592E5},app_nexus:{url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",resyncAfter:1728E5},krux:{url:"//x.skimresources.com/?provider=krux",resyncAfter:1728E5},add_this:{url:"https://su.addthis.com/red/usync?pid=11179&url=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%7B%7Buid%7D%7D%26provider%3Dadd_this%26skim_mapping%3Dtrue",resyncAfter:1728E5}};g={};b=function(a,b){var c,d,e,g;if(a.filter)return null!=
(c=a.filter)?"function"===typeof c.call?c.call(a,b):void 0:void 0;d=[];for(c=e=0,g=a.length;0<=g?e<g:e>g;c=0<=g?++e:--e)b(a[c])&&d.push(a[c]);return d};j=function(a){var b;if(!(b="function"===typeof Object.keys?Object.keys(a):void 0)){var c,d,e;e=[];for(c=0,d=a.length;c<d;c++)b=a[c],e.push(b);b=[e]}return b};i=function(a){g.syncCheck=a[0];g.getCookieSyncInfo=a[1];g.getServerTime=a[2];return g};s=function(a,b,c){return Boolean(a.timestamp+b.resyncAfter<=c)};n=function(a){return g.getServerTime(function(b){if(b=
f(a,b))return e(m[b])})};f=function(a,c){return b(j(m),function(b){var d;return(d=a[b])?s(d,m[b],c):!0}).shift()};I=function(a){return n(u(a))};u=function(a){var b,c,d,e,g;d={};g=(a||"").split("|");for(a=0,e=g.length;a<e;a++)b=g[a],b=b.split(":"),c=b[0],d[c]={label:c,timestamp:parseInt(b[1])};return d};k=function(a){return h(a.target)};h=function(a){a.width=0;a.height=0;return a.style.display="none"};c=function(a,b){var c;null==b&&(b=document);c=b.createElement("img");c.src=a;c.width=1;c.height=1;
c.onerror=k;return c};a=function(a,b){var c;null==b&&(b=document);null!=(c=b.getElementsByTagName("body")[0])&&c.appendChild(a);return a};d=function(){var b;b=a(document.createElement("iframe"));h(b);return b.contentDocument||b.contentWindow.document};e=function(b){var e;e=d();return a(c(b.url,e),e)};return{init:function(){i(arguments);if(g.syncCheck())return g.getCookieSyncInfo(I)}}}();var S,Gc,Hc,X,Ic,Jc,Lb,h,p,Mb,ta,Nb,Ob,Pb,Qb,La,Kc,fb,Lc,Mc,Rb,Sb,l,Ma,Tb,gb,Ub,r,n,v,Vb,N,fa,ua,ga,hb,va,Y,wa,
xa,Nc,q,ya,Na,Wb,Z,$,Oc,Pc,Qc,ib,jb,T,Rc,Sc,Oa,ha,Xb,Tc,Uc,Vc,Wc,Pa,C,Xc,kb,ia,Yb,lb,Qa,ja,ka,la,Zb,mb,Ra,Yc,Sa,za,Zc,Ta,$b,Ua,ac,$c,o,ad,bc,bd,nb,Va,cd,Wa,Xa,ob,dd,cc,pb,ed,dc,ec,fd,qb,fc,F,gc,hc,ic,O,jc,rb,kc,sb,lc,mc,ma,tb,nc,G,Ya,ub,P,da,Aa,vb,oc,Za,wb,xb,yb,zb,Ab,ca,$a,Ba,Bb,H,Ca,D,J,na,pc,K,gd,Cb,hd,ab,id,A,qc,rc,jd,Db,sc,tc,Q,t,x,Eb,uc,vc,Da,oa,aa,U,bb,pa,Ea,qa,E,y,wc,L,kd,B,ld,ba,xc,z={}.hasOwnProperty,Fa=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;
return-1};ga=hb=null;va=/http:/g;n=function(){return function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}}(this)();Z=[];$=[];q={};Wb=(new Date).getTime();ya=[];Nc=["buy.itunes.apple.com","itunes.apple.com","itunes.com"];Y=N=null;Na=ua=!1;wa=[];fa=[];xa=[];v={domains:[]};
r={};Ca=H=$a=Ya=G=ca=J=Vb=null;ma=[];da=[];P=Bb=sb=tb=Za=null;Aa=!1;oc="beginning";vb=[];D=na=!1;lc="skimlinksApplyHandlers";rb=Ba=!1;wb=300;mc=nc=zb=yb=xb=Ab=kc=!1;rc=[];qa=pa=Ea=bb=E=null;L=y=t="";U=x=0;Da=vc=oa=tc=wc=!1;Q=[];aa=!0;uc=sc=!1;Eb=[];B=f.location;ba="";S=!1;ab=null;Xa={};Db=[];Ec=["noskim","norewrite"];Fc="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");ub=function(){return!0};Ka=[];
ib=function(a){var b;b=document.createElement("a");b.href=a;return K(b.hostname)};ed=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};Oc=function(){var a,b;a="";for(b=0;8>b;++b)a+=ed();return a};Ic=function(){var a,b,c,d,e,g,w,i,I,h,k,s,W,u,n,l,q,o,p,t,r,v,y,z,A,C,F,K,M,N,O,Q,R,S,T,V,X,Y,Z,$;L=Oc();hb=null!=(a=document.getElementsByTagName("html"))?a[0]:void 0;wa=null!=(b=f.skimlinks_included_classes)?b:[];fa=null!=(W=f.skimlinks_excluded_classes)?W:[];xa=null!=(y=
f.skimlinks_included_ids)?y:[];ga=f.force_location?ib(f.force_location):B.hostname;J=null!=(R=f.skimlinks_tracking)?R:!1;ca=f.skimlinks_site||f.skimlinks_sitename||!1;G=f.skimlinks_domain?"http://"+f.skimlinks_domain:"//go.redirectingat.com";Ya=null!=(X=f.skimlinks_google)?X:!1;$a=null!=Ya?Ya:"skimout";H=null!=(Y=f.skimlinks_target)?Y:!1;Ca=null!=(Z=f.sl_test)?Z:!1;ma=null!=($=f.skimlinks_exclude)?$:[];da=null!=(c=f.skimlinks_include)?c:[];Za=null!=(d=f.skimlinks_noright)?d:!1;tb=null!=(e=f.skimlinks_exrel)?
e:!1;sb=null!=(g=f.skimlinks_byrel)?g:!1;Bb=null!=(w=f.skimlinks_blocked_tag)?w:!1;na=null!=(i=f.skimlinks_revenue_forecast)?i:!1;Ba=null!=(I=f.skimlinks_strip_attribute)?I:!1;rb=null!=(h=f.skimlinks_ad_images)?h:!1;"number"===typeof f.skimlinks_replace_timeout&&(wb=f.skimlinks_replace_timeout);"boolean"===typeof f.skimlinks_before_click_handler&&(kc=f.skimlinks_before_click_handler);P=0;D=Uc();Ab=null!=(k=f.skimlinks_retargetting_trigger)?k:!1;xb=null!=(s=f.skimlinks_retargetting_adv_id)?s:!1;yb=
null!=(u=f.skimlinks_retargetting_pix_id)?u:!1;zb=!1;nc=null!=(n=f.skimlinks_first_party_na)?n:!1;"undefined"!==typeof skimlinks_cookie_sync_optout&&null!==skimlinks_cookie_sync_optout&&(mc=skimlinks_cookie_sync_optout);f.skimlinks_revenue_forecast=!1;E=null!=(l=f.skimlinks_pub_id)?l:"";if(f.skimlinks_legacy_support)f.skimlinks=function(){return!0},f.mugicPopWin&&(f._mugicPopWin=f.mugicPopWin),f.mugicPopWin=function(){return!0},f.mugicRight=function(){return!0},f.mugicRightClick=function(){return!0};
x=null!=(q=f.skimlinks_dnt)?q:0;U=null!=(o=window.skimlinks_nocookie)?o:!1;U=null!=(p=window.skimlinks_nocookie)?p:!1;bb=null!=(t=f.noimpressions)?t:!1;pa=null!=(r=f.noskimlinks||f.noskim)?r:!1;aa=null!=(v=f.skimlinks_legacy_click_handlers)?v:!0;sc=null!=(z=f.skimlinks_affiliate_unknown_links)?z:!1;pa&&(ea.skimlinks=!1);(Ea=null!=(A=f.noskimwords||f.noskim)?A:!1)&&(ea.skimwords=!1);qa=null!=(C=f.nounlinked||f.noskim)?C:!1;rc=f.unlinked_excludes||[];qa&&(ea.unlinked=!1);wc=null!=(F=f.skim_toolbar)?
F:!1;tc=null!=(K=f.skimlinks_ajax_rerun)?K:!1;vc=null!=(M=f.skimlinks_ipc)?M:!1;Da=null!=(N=f.skimlinks_ipc_diy)?N:!1;uc=null!=(O=f.skimlinks_dwell_tracking)?O:!1;Eb=null!=(Q=f.skimlinks_dwell_allowed_urls)?Q:[];f._merchantSettings&&"undefined"===typeof replace_url_field?(oa=!0,lc="skimlinksApplyHandlersAlt"):oa=!1;Aa=null!=(S=f.skimlinks_ipc_decoration)?S:!1;oc=null!=(T=f.skimlinks_ipc_position)?T:"beginning";vb=null!=(V=f.skimlinks_ipc_domain_whitelist)?V:[];if(f.document&&f.document.referrer)ba=
f.document.referrer;Zc(ga)&&(Ea=pa=!0);J&&!/^[a-z0-9_\\|]+$/i.test(J)&&(J=!1);if("undefined"!==typeof m&&null!==m)m.pag=j.pag=f.force_location||B.href,m.pub=j.pub=E,m.uc=j.uc=J;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();fa.push("noskimlinks");fa.push("noskim");ab=document.createTextNode("").nodeName;return!0};ld=function(){return!mc};kd=function(a,b){return a.hasOwnProperty(b)};Uc=function(){var a;return"function"===typeof(a=new Date).getTimezoneOffset?
a.getTimezoneOffset():void 0};Zc=function(a){var b,c,d,e;if(f.noskim_domains){e=f.noskim_domains;for(c=0,d=e.length;c<d;c++)if(b=e[c],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0}return!1};K=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();p=function(){return function(){return document.addEventListener?function(a,b,c){if(a&&(a.nodeName||a===f))return a.addEventListener(b,c,!1)}:function(a,b,c){if(a&&(a.nodeName||a===f))return a.attachEvent("on"+
b,function(){return 7>n.version&&!window.event?(setTimeout(function(){return c.call(a,window.event)},100),!0):c.call(a,window.event)})}}}(this)();(function(){return function(){return document.createElement("div").getElementsByClassName?function(a,b){return C(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=Qb(b);return Tb(a,c)}}})(this)();l=function(){return function(){var a,b;b=[function(){var b,d,e,g;e=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~",
"%7E"]];g=[];for(b=0,d=e.length;b<d;b++)a=e[b],g.push([RegExp(a[0],"g"),a[1]]);return g}()];return function(c){var d,e,c=encodeURIComponent(c);for(d=0,e=b.length;d<e;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();Ra=function(){return function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!ga||-1===c.indexOf(ga))&&(!ga||-1===ga.indexOf("."+c))}}}(this)();h=function(a,b,c){var d;3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);
try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(e){return null}};La=function(a,b,c){arguments[1]="data-"+b;return h.apply(this,arguments)};hd=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};kb=function(a){return(""+a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};A=function(){return function(){var a,b;if(String.prototype.trim)return function(a){return null===
a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();Gc=function(a,b){return!C(a,b)?(a.className+=" "+b,!0):!1};bd=function(a){var b,c,d,e,g;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(g in a)z.call(a,g)&&(b=a[g],0<d&&(e+=","),c?e+=o(b):(b=o(b),e+='"'+g+'":'+b),d++);return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=
a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};o=function(){return function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):bd}}(this)();Ma=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();pb={topics:{},on:function(a,b){var c;if(null==(c=this.topics)[a])c[a]=[];return this.topics[a].push(b)},
off:function(a,b){var c;c=this.topics[a].indexOf(b);if(-1<c)return this.topics[a].splice(c,1)},once:function(a,b){var c;c=function(d){return function(){b.apply(d,arguments);return d.off(a,c)}}(this);return this.on(a,c)},publish:function(a,b){var c,d,e,g,f,i;c={topic:a,extra:b};if(this.topics[a]){f=this.topics[a];i=[];for(e=0,g=f.length;e<g;e++)d=f[e],i.push(d(c));return i}}};Qb=function(a){a=Ma(a);return RegExp("\\b"+a+"\\b","i")};C=function(a,b){return a.className?Qb(b).test(a.className):!1};Tb=
function(a,b){var c,d,e,g,f;d=[];a.className&&b.test(a.className)&&d.push(a);f=a.childNodes;for(e=0,g=f.length;e<g;e++)c=f[e],d=d.concat(Tb(c,b));return d};Nb=function(a){return-1!==encodeURIComponent(a).indexOf("%C3%82%C2%A3")};Ub=function(a){a=a.innerHTML.slice(0,4);if("http"===a||"www."===a)a.innerHTML="<span style='display:none!important;'>&nbsp;</span>";return!0};Ta=function(a){for(var b,c,d,e;a&&a!==hb;){c=a.id;for(d=0,e=wa.length;d<e;d++)if(b=wa[d],C(a,b))return!1;for(d=0,e=xa.length;d<e;d++)if(b=
xa[d],c===b)return!1;for(c=0,d=fa.length;c<d;c++)if(b=fa[c],C(a,b))return!0;a=a.parentNode}return wa.length||xa.length?!0:!1};la=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+Ma(b)+")|(?:noskim))\\b","i");null!=a&&a!==hb;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};Ob=function(a,b){var c,d,e,g,w,i,I;E||(E=null!=(c=f.skimlinks_pub_id)?c:"");i=ba?"&pref="+l(ba):"";c=!1;0<b.indexOf("#slm-")&&(d=b.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1])===
10*d[1]&&(b=d[0],c=d[1]));e=h(a,"data-skimlinks-editor")&&1===parseInt(h(a,"data-skimlinks-editor"))?1:0;G||(G=f.skimlinks_domain?"http://"+f.skimlinks_domain:"//go.redirectingat.com");C(a,"skimwords-link")?(I=h(a,"data-skimwords-word"),d=h(a,"data-skim-creative"),g=h(a,"data-skim-product"),w=f.skimlinks_domain?"http://"+f.skimlinks_domain:"//go.redirectingat.com","undefined"!==typeof settings&&null!==settings&&(w=settings.sw_domain||w),b=""+w+"/?id="+E+""+(J?"&xcust="+J:"")+""+(!1!==c?"&xs=9":"&xs=2")+
"&url="+l(b)+"&xguid="+t+"&xuuid="+L+"&xsessid="+y+"&isjs=1&xword="+(I?I:"")+"&xcreo="+(d?d:"")+"&xpid="+(g?g:"")+"&xed="+e+"&sref="+l(B)+""+i+""+(x?"&dnt="+x:"")+""+(U?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==D?"&xtz="+D:"")):C(a,"skimlinks-inline")?(d=h(a,"data-skim-creative"),b=""+G+"/?id="+E+""+(ca?"&site="+ca:"")+""+(Ca?"&test="+Ca:"")+""+(J?"&xcust="+J:"")+""+(!1!==c?"&xs=9":"&xs=8")+"&isjs=1&url="+l(b)+"&xguid="+t+"&xuuid="+L+"&xsessid="+y+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+
l(B)+"&pref="+l(ba)+""+(x?"&dnt="+x:"")+""+(U?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==D?"&xtz="+D:"")):la(a,"noskimlinks")||(d=h(a,"data-skim-creative"),b=""+G+"/?id="+E+""+(ca?"&site="+ca:"")+""+(Ca?"&test="+Ca:"")+""+(J?"&xcust="+J:"")+""+(!1!==c?"&xs=9":"&xs=1")+"&isjs=1&url="+l(b)+"&xguid="+t+"&xuuid="+L+"&xsessid="+y+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+l(B)+""+i+""+(x?"&dnt="+x:"")+""+(U?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==D?"&xtz="+D:""));S&&!la(a,"noskimlinks")&&
(b+="&abp=1");return b};Pa=function(a){var b,c,d;if(rb)return!1;if(a.hasChildNodes()){d=a.childNodes;for(a=0,c=d.length;a<c;a++)if(b=d[a],b=Pa(b))return!0}else return Qa(a);return!1};Qa=function(a){var b,c,d,e,g;if(rb)return!1;b=[[300,250],[302,252],[304,254],[300,300],[302,302],[304,304],[468,60],[470,62],[472,64],[728,90],[730,92],[732,94]];if(a&&a.nodeName&&"IMG"===a.nodeName.toUpperCase()){d=a.offsetWidth||0;c=a.offsetHeight||0;for(e=0,g=b.length;e<g;e++)if(a=b[e],d===a[0]&&c===a[1])return!0}return!1};
jb=function(a){var b;b=a.target||a.srcElement;if(aa&&b&&!b.href&&a.currentTarget)b=a.currentTarget;for(;b&&"A"!==b.nodeName.toUpperCase()&&"AREA"!==b.nodeName.toUpperCase();){if(Qa(b))return null;b=Oa(b)}return b};F=function(a){var b;b=jb(a);if(!b||Pa(b))return!0;ec(b);if(f.vglnk&&C(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=f.event,a.cancelBubble=!0);return!0};Oa=function(a){for(;a.parentNode;){a=a.parentNode;if(Qa(a))break;if("A"===(null!=a?a.nodeName.toUpperCase():void 0)||
"AREA"===(null!=a?a.nodeName.toUpperCase():void 0))return a}return null};gd=function(a){return a=t?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,"$1xguid="+t):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};Pb=function(a,b){return function(c){var d;d=a();return null!=d?c(d):pb.once(b,function(){return c(a())})}};Qc=Pb(function(){var a;return null!=(a=Ka[0])?a.csp:void 0},"beacon");Vc=Pb(function(){var a;return null!=(a=Ka[0])?a.ts:void 0},"beacon");ec=function(a){var b,c,d,e;d=!1;b=Ya;a&&a.nodeName&&
"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Oa(a));if(a){e=a.href;G||(G=f.skimlinks_domain?"http://"+f.skimlinks_domain:"//go.redirectingat.com");c=G;if(e.length>=c.length&&e.substr(0,c.length)===c)return!0;if("msie"===n.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==e.indexOf(c)?e:Ob(a,e);b&&md(e);fc(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),wb)}return!0};Ua=function(a){return G&&
-1!==G.indexOf(a)||-1!==a.indexOf("go.redirectingat.com")};Zb=function(a){return!0===r[a]||(null===r[a]||void 0===r[a])&&sc&&!Ua(a)};za=function(a){return na?(Zb(a)&&(P+=1),!1):Zb(a)};ac=function(a){var b,c;if(!Bb)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+Bb+"]").toLowerCase();c=hd(b);if(!c)return!1;c=c.toLowerCase();c=A(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};ka=function(a){return!a||sb&&a===sb||!Xc(a)};Xc=function(a){var b,c,d,e;if(!a)return!1;b=a.toLowerCase().split(/\s+/);
a=tb?[tb.toLowerCase()]:[];a=a.concat(Ec);for(d=0,e=b.length;d<e;d++)if(c=b[d],0<=Fa.call(a,c))return!0;return!1};Mb=function(){var a,b,c,d;N={};Y={};ca&&ma.push(ca);d=ma.concat(Fc);for(b=0,c=d.length;b<c;b++)a=d[b],N[a]=a.length;for(b=0,c=da.length;b<c;b++)a=da[b],Y[a]=a.length;return N};mb=function(a){var b,c,d;(null===N||null===Y)&&Mb();if(!a)return!1;for(b in N)if(z.call(N,b))if(c=N[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-c)return!0}else if(a===b)return!0;
return!1};Yc=function(a){var b,c,d;(null===N||null===Y)&&Mb();if(!a)return!1;if(0===da.length)return!0;for(b in Y)if(z.call(Y,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===a.indexOf(b))return!0}else if(a===b)return!0;return!1};ja=function(a,b){return Ra(a,b)&&!mb(b)&&Yc(b)};qb=function(a){if(aa&&10>a)return ya=fd(),setTimeout(function(){return qb(a+
1)},2E3*a)};fd=function(){var a,b,c,d,e,g,f;if(aa){b={};d=[];c=[];for(e=0,g=ya.length;e<g;e++)a=ya[e],a.parentNode?c.push(a):b[a.href]=1;f=T();for(e=0,g=f.length;e<g;e++)a=f[e],b[a.href]&&d.push(a);Lb(d,!1);return d.concat(c)}};Hc=function(a,b){var c,d,e;d=[];na&&(a.xrf=1);for(c in a)z.call(a,c)&&(e=a[c],"data"!==c&&d.push(""+c+"="+e));a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};id=function(a){var b,c;if(-1<a.indexOf("go.redirectingat.com")||G&&-1<a.indexOf(G))return!0;b="";0<a.indexOf("#slm-")&&
(c=a.split("#slm-"),2===c.length&&!isNaN(c[1])&&10*parseInt(c[1])===10*c[1]&&(a=c[0],b=c[1]));a={call:"track",data:l('{"pubcode":"'+E+'", "referrer":"'+B+'", "pref":"'+ba+'", "site":"'+ca+'", "url":"'+a+'", "custom":"'+J+'", "xtz":'+D+', "uuid":"'+L+'", "slmcid":"'+b+'", "product":"1"}')};x&&(a.dnt=x);U&&(a.fdnt=1);a=Hc(a,"//t.skimresources.com/api/");a=a+"&rnd="+Math.random();Rc(a);return!0};fc=function(a){var b,c;if(!(null!==a&&a.sl_href_restore_scheduled))return b=a.href,c="msie"===n.browser&&
7>n.version?1E4:wb,a.sl_href_restore_scheduled=!0,setTimeout(function(){return function(){a.href=b;a.href=b;return delete a.sl_href_restore_scheduled}}(this),c)};Wc=function(a,b){var c,d;d=!1;c=gd(b);if(c!==b&&(a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Oa(a)),a)){if("msie"===n.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;fc(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),
300)}return c};gc=function(a,b){var c,d;pc(a);H&&h(a,"target",H);d=h(a,"onclick");c="click"===b.type||"contextmenu"===b.type;if("msie"===n.browser){if(Nb(url))return!0;Ub(a)}if(null!=d&&-1!==d.toString().indexOf("return false")){if(c)return ub(a),cc(b)}else return ub(a),F(b)};ob=function(a){var b,c;b=jb(a);c=b.href;-1<c.indexOf(G)&&(c=Wc(b,c));""===t&&nc?gc(b,a):id(c);return!0};Rc=function(a){var b,c;b=document.getElementsByTagName("body")[0];c=document.createElement("img");c.src=a;c.width=1;c.height=
1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};ha=function(a,b,c,d,e){var k;var g,f,i,h,j;null==c&&(c={});g=c.charset||null;j=c.target||null;k=null!=(f=c.async)?f:!0,c=k;f=null!=j&&j.document?j.document:document;i=f.getElementsByTagName("head")[0];h=f.createElement("script");h.type="text/javascript";if(g)h.charset=g;if(b)h.onload=h.onreadystatechange=function(a){return function(){var c;c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===d||"loaded"===
d))return h.onload=h.onreadystatechange=null,c=!0,b.call(j),!0}}}(this)();h.onerror=function(){if(null!=d)return null!=e?d(e):d(!1)};h.async=!1!==c;h.src=a;i.appendChild(h);return h};T=function(a,b){var c,d,e,g,f,i;e=null;a&&(e=RegExp("\\b"+Ma(a)+"\\b","i"));i=[];b||(b=document);d=b.getElementsByTagName("a");for(g=0,f=d.length;g<f;g++){c=d[g];try{c.href&&(!e||c.className&&e.test(c.className))&&i.push(c)}catch(h){}}d=b.getElementsByTagName("area");for(g=0,f=d.length;g<f;g++){c=d[g];try{c.href&&(!e||
c.className&&e.test(c.className))&&i.push(c)}catch(j){}}return i};Sa=function(a){return-1!==a.indexOf("itunes.apple.com")||-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?!0:!1};pc=function(a){var b,c,d;if(!Ba)return!1;for(c in Ba)if(kd(Ba,c)&&(d=Ba[c],(b=h(a,c))&&0===b.indexOf(d)))b=b.substr(d.length),h(a,c,b);return!0};$b=function(a){return a&&Ab&&!zb&&ia(""+a,Ab)};Lb=function(a,b){var c,d,e,g,f,i,I,j,k,s,W;null==b&&(b=!0);g=wa.length||xa.length||fa.length;i=[];d=0;for(s=0,W=a.length;s<
W;s++)if(c=a[s],f=K(c.hostname),c.sl_hidden_domain&&(f=K(c.sl_hidden_domain)),k=A(c.href),Ra(k,f)){j=h(c,"rel");I=h(c,"onclick");h(c,"sl-processed",1);c["sl-processed"]=1;e=Xb(k);$b(e)&&Sb(xb,yb);if(b&&ja(k,f)&&(za(f)?(d++,q.hasOwnProperty(k)?q[k].ae=1:q[k]={count:0,ae:1}):q.hasOwnProperty(k)||(q[k]={count:0,ae:0}),q[k].count++,e))q[k].slmcid=e,0>Fa.call(Q,e)&&Q.push(e);P=d;if(!oa||!Sa(k))if((!g||!Ta(c))&&!ac(c))if(za(f)||Sa(k)){if(q.hasOwnProperty(k)&&(q[k].ae=1),ka(j)){pc(c);H&&h(c,"target",H);
if("msie"===n.browser){if(Nb(k))continue;Ub(c)}null!=I&&-1!==I.toString().indexOf("return false")?p(c,"click",cc):p(c,"click",F);Cb(c,!1);lb(c);i.push(c);Za||p(c,"contextmenu",F);ub(c)}}else Ra(k,f)&&!mb(f)&&ka(j)&&(H&&h(c,"target",H),p(c,"click",ob),Za||p(c,"contextmenu",ob))}return i};cc=function(a){var b;b=jb(a);if(f._mugicPopWin)return f._mugicPopWin(b);F(a);return(H?window.open(b.href):window.open(b.href,H)).focus()};lb=function(a,b){var c,d,e,g,w;if(f.link_icon||0<a.getAttribute("data-skim-product")&&
f.skimwords_product_icon){if(0<a.getElementsByTagName("img").length)return!0;if("msie"===n.browser&&8>n.version)a.style.display="inline-block";d=c="";null!=b&&(c=f.skimwords_icon_class||"",d=f.skimwords_icon_link_class||"");w=h(a,"title").replace("'","&#39;");e=f.link_icon||f.skimwords_product_icon;g=document.createElement("a");h(g,"href",h(a,"href"));h(g,"title",w);h(g,"style","border:0px;padding:0;margin:0");h(g,"skimlinked","skimlinked");h(g,"target","_blank");C(a,"skimlinks-unlinked")||C(a,"skimwords-link")?
(h(g,"data-skim-creative",La(a,"skim-creative")),h(g,"data-group-id",La(a,"group-id")),h(g,"data-skimwords-word",La(a,"skimwords-word")),h(g,"data-skimwords-id",La(a,"skimwords-id")),C(a,"skimlinks-unlinked")?h(g,"class","skimlinks-icon-link "+d+" skimlinks-unlinked"):h(g,"class","skimlinks-icon-link "+d+" skimwords-link")):(h(g,"data-skim-creative",""),h(g,"data-group-id",""),h(g,"data-skimwords-word",""),h(g,"data-skimwords-id",""),h(g,"class","skimlinks-icon-link "+d));d=document.createElement("img");
h(d,"src",e);h(d,"class",c);h(d,"skimlinked","skimlinked");h(d,"style","margin: 0px 0px -3px 2px !important; float:none !important; border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;");g.appendChild(d);c=document.createElement("div");c.appendChild=g;c=c.childNodes[0];p(c,"mousedown",F);a.appendChild(g)}return!0};Tc=function(a,b){return null!=a.currentStyle?a.currentStyle[b]:window.getComputedStyle?document.defaultView.getComputedStyle(a,
null).getPropertyValue(b):!1};ia=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],c===a)return!0;return!1};ic=function(a){var b,c,d,e;f.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(Ka.push(a),pb.publish("beacon",a));null!=f.skimlinks_runner&&(f.skimlinks_runner.skimlinks=1);a.guid&&""===t&&(t=a.guid);a.sessid&&""===y&&(y=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<d;c++)b=e[c],Ua(b)||(r[b]=!0);for(b in r)null===r[b]&&(r[b]=!1);aa&&(b=T(),ya=Lb(b),P+=ya.length,
!Na&&"undefined"!==typeof ra&&null!==ra&&null!=v&&null!=v.domains&&(Na=!0,ra(v.domains)),jc());qa||yc(a);return!0};Xb=function(a){return-1!==a.indexOf("#slm-")&&(a=a.split("#slm-"),2===a.length&&!isNaN(a[1])&&10*parseInt(a[1])===10*a[1])?parseInt(a[1]):null};Rb=function(a){var b,c,d,e,g,w,i;a||(a=0);if(f.skimlinks_requests_in_flight&&5>a)setTimeout(function(){return Rb(a+1)},400*a);else{e=T();c=0;for(w=0,i=e.length;w<i;w++)if(b=e[w],g=A(b.href),d=K(b.hostname),b=h(b,"class"),(!b||!(-1!==b.indexOf("skimwords-link")||
-1!==b.indexOf("skimlinks-unlinked")))&&ja(g,d))if(b=Xb(g),$b(b)&&Sb(xb,yb),za(d)?(c++,q.hasOwnProperty(g)?q[g].ae=1:q[g]={count:0,ae:1}):q.hasOwnProperty(g)||(q[g]={count:0,ae:0}),q[g].count++,b)q[g].slmcid=b,0>Fa.call(Q,b)&&Q.push(b);P=c;!Na&&"undefined"!==typeof ra&&null!==ra&&null!=v&&null!=v.domains&&(Na=!0,ra(v.domains));jc()}return!0};jc=function(){"undefined"!==typeof cb&&null!==cb&&(vc||Da)&&r.length&&cb();"undefined"!==typeof Ga&&null!==Ga&&Ga("skimlinks");return!0};Sb=function(a,b){var c;
if(!a||!b)return!1;zb=!0;f.adroll_adv_id=a;f.adroll_pix_id=b;f.__adroll_loaded=!0;c=document.createElement("script");c.setAttribute("async","true");c.type="text/javascript";c.src="//s.adroll.com/j/roundtrip.js";return document.getElementsByTagName("head").length?document.getElementsByTagName("head")[0].appendChild(c):document.getElementsByTagName("script")[0].parentNode.appendChild(c)};gb=function(){var a,b,c,d,e,g,f;d=T();c=[];for(g=0,f=d.length;g<f;g++)a=d[g],b=K(a.hostname),e=A(a.href),a=h(a,"rel"),
b&&ja(e,b)&&ka(a)&&!Ua(b)&&void 0===r[b]&&(c.push(b),v.domains.push(b),r[b]=null);return c};Jc=function(){var a;a=document.getElementsByTagName("body");if(0<a.length)return p(a[0],"click",X),p(a[0],"contextmenu",X)};X=function(a){var b,c,d;if(f.event)a=f.event;c=a.originalTarget||a.srcElement||a.target;try{if("A"!==(null!=c?c.nodeName.toUpperCase():void 0)&&c.parentNode)c=Oa(c)}catch(e){c=null}if(!c||Pa(c)||Ta(c)||!ka(h(c,"rel")))return!0;try{b=h(c,"sl-processed")||0,null==c["sl-processed"]&&(b=0)}catch(g){b=
0}if((d=h(c,"class"))&&(-1!==d.indexOf("skimwords-link")||-1!==d.indexOf("skimlinks-inline")||-1!==d.indexOf("skimlinks-unlinked")))b=!0;if("A"===(null!=c?c.nodeName.toUpperCase():void 0)&&0===b)if(b=c,c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&(c=!1),c&&ja(b.href,K(b.hostname))){ec(b);if(f.vglnk&&C(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=f.event,a.cancelBubble=!0);return!0}};qc=function(a,b,c){if(0===b)return c;
try{return a()}catch(d){return qc(a,b-1,c)}};Sc=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=qc(function(){return a.parentNode},3,null),null==a||Qa(a))return null;return a};$c=function(a){return!a||!a.href||0!==a.href.indexOf("http://")&&0!==a.href.indexOf("https://")&&0!==a.href.indexOf("//")?!1:!0};fb=function(a){var b,c,d,e;if(f.event)a=f.event;b=a.originalTarget||a.srcElement||a.target;c=null!=b?b.nodeName.toUpperCase():void 0;"A"!==c&&"AREA"!==c&&(b=Sc(b));if(!b||
Pa(b)||Ta(b)||!ka(h(b,"rel"))||ac(b))return!0;e=A(b.href);c=K(b.hostname);d="click"===a.type||"contextmenu"===a.type;if($c(b)&&ja(b.href,c)){b.sl_hidden_domain&&(c=K(b.sl_hidden_domain));if(oa&&Sa(e))return!0;if(za(c)||Sa(e))gc(b,a);else if(d&&Ra(e,c)&&!mb(c))return H&&h(b,"target",H),ob(a);return!0}};cd=function(a,b){var c,d,e,g,w,i;null==b&&(b=lc);f.skimlinks_requests_in_flight=(null!=(c=f.skimlinks_requests_in_flight)?c:0)+1;if(!(null!=a&&a.length))return f[b](),!1;c=l('{"pubcode":"'+E+'","domains":_DOMAIN_LIST_,"page":"'+
B.href+'"}');g="//r.skimresources.com/api/?callback="+b+(x?"&dnt="+x:"")+(U?"&fdnt=1":"")+(wc?"&call=toolbar":"")+"&data="+c;c="msie"===n.browser?2E3:8E3;e=[];for(w=0,i=a.length;w<i;w++)d=a[w],e.push(d),g.replace("_DOMAIN_LIST_",l(o(e))).length>c&&(e=e.slice(0,-1));g=g.replace("_DOMAIN_LIST_",l(o(e)));return ha(g,!1,{})};ta=function(a){var b,c;b=[];na&&(a.xrf=1);for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+l(a[c]));return b.join("&")};Va=function(a,b,c){var d,e,g;if("msie"!==n.browser)e=!1,g=new XMLHttpRequest,
g.open("POST",a,!0),g.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=Fa.call(g,"withCredentials")&&(g.withCredentials=!0),g.async="true",g.onreadystatechange=function(){var a;if(e)return!0;if(4===g.readyState){e=!0;if(200===g.status){a={};try{a=JSON.parse(g.responseText)}catch(b){try{a=eval("("+g.responseText+")")}catch(d){a={}}}c(a);return!0}return!1}},g.send(b);else if(f.XDomainRequest){if(d=new XDomainRequest,0<=Fa.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",
a,!0);d.onload=function(){var a;a={};if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){a={}}else try{a=eval("("+d.responseText+")")}catch(e){a={}}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=function(){return!1};d.async=!0;try{d.send(b)}catch(w){return!1}}}else return!1;return!0};Wa=function(a,b){var c;c={data:o({pubcode:E,domains:a,page:B.href})};ta(c);cd(a,b);return!0};nb=function(a){var b,c,d,e;c=[];for(d=
0,e=a.length;d<e;d++)b=a[d],(null===r[b]||void 0===r[b])&&c.push(b);return c.length?Wa(c):!0};dc=function(){var a,b,c,d,e,g;c=T();g=[];for(d=0,e=c.length;d<e;d++)(a=c[d])&&a.href?(b=ib(a.href),0>Fa.call(Nc,b)?(h(a,"sl-processed",0),g.push(a["sl-processed"]=0)):g.push(void 0)):g.push(void 0);return g};Yb=function(){return"undefined"!==typeof V&&null!==V?"function"===typeof V.init?V.init(ld,Qc,Vc):void 0:void 0};xc=function(){if(window.skimlinksInitialized&&"function"!==typeof post_skimwords_hook)return!0;
window.skimlinksInitialized=!0;bc();Yb();oa&&dc();tc&&!pa&&Jc();pa||(gb(),qa&&Wa(v.domains));"undefined"!==typeof sa&&null!==sa&&!qa&&sa();"undefined"!==typeof skimwords&&null!==skimwords&&!Ea&&skimwords();return!0};ad=function(){if(ua)return!1;ua=!0;return xc()};dd=function(a){var b,c;b=0;for(c in a)z.call(a,c)&&(b+=1);return b};Cb=function(a,b){var c,d;d=a.style.cssText;""!==d&&(d+=" ");if(f.link_background)c=f.link_background,-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ";
if(null!=f.link_tooltip)a.title=f.link_tooltip;if(b){if(f.skimwords_color)c=f.skimwords_color,-1===c.indexOf("#")&&(c="#"+c),d+="color: "+c+" !important; ";f.skimwords_weight&&(d+="font-weight: "+f.skimwords_weight+" !important; ");if(f.skimwords_decoration)c=f.skimwords_decoration,d="double"===c?d+"border-bottom: 1px double !important; ":"dashed"===c?d+"border-bottom: 1px dashed !important; ":d+("text-decoration: "+c+" !important; ");if(f.skimwords_style)c=f.skimwords_style,d+="font-style: "+c+" !important; ";
if(f.skimwords_link_style)c=f.skimwords_link_style,d+=c+"; ";c=" "+a.className;if(f.skimwords_link_class)c+=" "+f.skimwords_link_class,a.className=c.substring(1);if(null!=f.skimwords_title)a.title=f.skimwords_title;if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%10,1===c||2===c))a.title=""}a.style.cssText=d;return!0};O=function(){return aa?ad():Mc()};Lc=function(){var a;window.skimlinksInitialized=
!0;Yb();oa&&dc();pa||(a=gb(),Wa(a),kc&&p(document,"mouseup",fb),p(document,"click",fb),p(document,"contextmenu",fb));return bc()};jd=function(a,b){var c,d,e,g,f;e=!1;if(Eb){d=Pc(a);0===d.length&&(e=!0);for(g=0,f=d.length;g<f;g++)if(c=d[g],0<=c.indexOf(b)){e=!0;break}}return e};Pc=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],b=b.replace(/https?\:\/\//,""),b=b.split("?")[0],c.push(b.split("#")[0]);return c};bc=function(){var a;a=jd(Eb,location.host+location.pathname);if(uc&&a&&"function"===
typeof SkimPageIntelligence)return a="undefined"!==typeof M&&null!==M?M:"//t.skimresources.com/api/",Vb=SkimPageIntelligence({dataCollectionUrl:a+"dwelltime",pub:E,guid:t,uuid:L,sessid:y}),Vb.start()};Mc=function(){if(ua)return!1;ua=!0;return Wa(gb(),"skimlinksApplySecondaryHandlers")};hc=function(){return function(){return function(){var a,b,c;Ic();Wd.detect(function(a){return S=a});if(window.skimlinks_revenue_forecast&&window.skimlinks||window.skimInitAlreadyCalled)return!1;aa||Lc();b=function(){if(ua)return!0;
try{document.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return O()};a=function(){return function(){return document.addEventListener?function(){document.removeEventListener("DOMContentLoaded",a,!1);O();return!0}:document.attachEvent?function(){document.detachEvent("onreadystatechange",a);O();return!0}:function(){O();return!0}}}(this)();if("complete"===document.readyState)setTimeout(O,1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1),f.addEventListener("load",
O,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",a);f.attachEvent("onload",O);c=!1;try{c=null===f.frameElement}catch(d){}document.documentElement.doScroll&&c&&b()}return window.skimInitAlreadyCalled=!0}}}(this)();Kc=function(a,b){return setTimeout(b,a)};f.skimlinksApplyHandlers=ic;f.skimlinksApplySecondaryHandlers=function(a){var b,c,d,e;f.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(Ka.push(a),pb.publish("beacon",a));null!=f.skimlinks_runner&&(f.skimlinks_runner.skimlinks=
1);a.guid&&""===t&&(t=a.guid);a.sessid&&""===y&&(y=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<d;c++)b=e[c],Ua(b)||(r[b]=!0);for(b in r)null===r[b]&&(r[b]=!1);"undefined"!==typeof sa&&null!==sa&&!qa&&sa();"undefined"!==typeof skimwords&&null!==skimwords&&!Ea&&skimwords();return Rb()};f.skimlinksApplyHandlersAlt=ic;f.skimlinksAjaxHandlerByClass=function(a){var b,c,d;if(aa&&"function"===typeof document.getElementsByClassName){b=document.getElementsByClassName(a);for(c=0,d=b.length;c<d;c++)a=
b[c],p(a,"click",X),p(a,"contextmenu",X);return!0}return!1};f.skimlinksAjaxHandlerById=function(a){return aa&&(a=document.getElementById(a))?(p(a,"click",X),p(a,"contextmenu",X),!0):!1};f.skimlinksRewriteUrl=Ob;window.skim_init=hc;!f.mugicPopWin&&!f.skimlinks_legacy_support&&!f.skimlinks_revenue_forecast&&(f.mugicPopWin=F);!f.mugicRight&&!f.skimlinks_legacy_support&&!f.skimlinks_revenue_forecast&&(f.mugicRight=F);f.skimlinksReload=function(){O();return!0};!f.skimlinks_legacy_support&&!f.skimlinks_revenue_forecast&&
(f.skimlinks=xc);var nd,od,Fb,zc,db,pd,qd,rd,sd,td,Ac,Gb,ud,vd,Ha,wd,xd,R,Bc,z={}.hasOwnProperty;Bc=R=0;db=!1;zc=function(a){var b;return a&&-1!==a.indexOf("class=")?(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:a};rd=function(a){Xa[a]=Xa[a]||0;Xa[a]++;return a+"_"+Xa[a]};Fb=function(a){var b,c,d;b=c=null;-1!==a.indexOf(".")?(a=a.split("."),d=a[0],b=a[1]):-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),
d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],c=a[1].split("]"),c=c[0]):d=a;return{tag:d,id:c,"class":b}};Gb=function(a,b){var c,d,e,g,f,i;e=b.split(",");for(f=0,i=e.length;f<i;f++){b=e[f];b=A(b);b=Fb(b);g=!0;c=a.className||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";d=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";if(b.tag&&(!a.nodeName||a.nodeName.toLowerCase()!==b.tag))g=!1;if(b["class"]&&(!c||c!==b["class"]&&
0!==c.indexOf(b["class"])))g=!1;if(b.id&&(!d||d!==b.id&&-1===d.indexOf(b.id)))g=!1;if(g)return!0}return!1};qd=function(a){var b,c,d,e,g,f;if("undefined"!==typeof document.querySelectorAll)return document.querySelectorAll(a);e=[];a=Fb(a);if(a.tag&&a["class"]){d=document.getElementsByTagName(a.tag);for(g=0,f=d.length;g<f;g++)b=d[g],(c=b.className||b.getAttribute("class"))&&0===c.indexOf(a["class"])&&e.push(b)}else a.tag&&a.id?(b=document.getElementById(a.id))&&b.nodeName.toLowerCase()===a.tag&&e.push(b):
(a=a.tag,e=document.getElementsByTagName(a));return e};sd=function(a,b,c){var d,e,g,f,i;d=[];if("undefined"!==typeof a.querySelectorAll)d=a.querySelectorAll(b);else if(b=Fb(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;g=a.getElementsByTagName(b.tag);for(f=0,i=g.length;f<i;f++)if(a=g[f],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)d.push(a);else return!0}else if(b.tag&&b.id){if((a=document.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===
b.tag)if(c)d.push(a);else return!0}else b=b.tag,d=a.getElementsByTagName(b);return c?d:0<d.length};Ac=function(a,b){return 0===b.length?!1:Gb(a,b.join(","))?!0:a.parentNode?Ac(a.parentNode,b):!1};td=function(a){var b;b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};pd=function(){var a;a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");
a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==B.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==
B.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==B.href.indexOf(".aol.")?(a.push("div.sllLink"),a.push("div.n")):-1!==B.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};vd=function(a){var b,c,d,e;c={};for(d=0,e=a.length;d<e;d++)b=a[d],c[b]=!0;return c};Ha=function(){var a;a={};return{traverse:function(b,
c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,g,f,i,h,j,k,s;if(db)return a;db=!0;g=this.get_exclude_selector(c);e=this.get_exclude_selector([]);c=g.selector;g=g.needed;e=e.selector;0===b.length&&b.push("body");b=b.concat(d);for(h=0,k=b.length;h<k;h++){f=b[h];f=zc(f);f=qd(f);for(i=j=0,s=f.length;j<s;i=++j)i=f[i],this.traverse_node(i,g,e,c,d)}return a},traverse_node:function(b,c,d,e,g){var f,i;i=[];f=0;for(i.push({node:b,tagName:"",
readOnly:!1,parent_id:null});f<i.length;){if((b=i[f].node)&&!td(b)&&!la(b,"noskimwords",!0)&&(!c||!(""!==d&&Gb(b,d)))){i[f].readOnly=!1;if(b.nodeName&&b.nodeName!==ab){i[f].tagName=b.nodeName;if(null!==i[f].parent_id)i[f].readOnly=i[i[f].parent_id].readOnly;if(!i[f].readOnly)if(c&&Gb(b,e))i[f].readOnly=!0;else if(ia(b.nodeName.toLowerCase(),g))i[f].readOnly=!0;if(ia(b.nodeName.toLowerCase(),g))i[f].readOnly=!0}else if(null!==i[f].parent_id)i[f].tagName=i[i[f].parent_id].tagName,i[f].readOnly=i[i[f].parent_id].readOnly;
"msie"===n.browser&&9>n.version&&i[f].readOnly||(b.hasChildNodes()?i=this.add_child_nodes(i[f],f,i):this._add(b,!1,i[f].tagName,i[f].readOnly))}f++}return a},is_traversed:function(){return db},is_good_tag:function(a){return vd("p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section,main".split(","))[a.nodeName.toLowerCase()]?!0:!1},is_html:function(a){return(a=A(a))&&"<"===
a[0]},get_non_colliding_nodes:function(){var b,c,d;d=a;c={};Bc=0;for(b in d)z.call(d,b)&&(c[b]=d[b],Bc++);return c},get_as_hash_node_dict:function(){var b,c,d;c={};for(b in a)d=a[b],a.hasOwnProperty(b)&&(c[b]=d);return c},get_as_pair_array:function(){var b,c;c=[];for(b in a)z.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var d,e,g,f,i,h;f=[];if(!c){c=document.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};c=c[0]}a=a.concat(pd());for(d=e=0,g=a.length;e<
g;d=++e)a[d]=zc(a[d]);e=!1;g="";for(i=0,h=a.length;i<h;i++)d=a[i],sd(c,d,!1)&&f.push(d);f.length&&(e=!0,g=f.join(",").replace("class=","class^="));return{needed:e,selector:g}},length:function(){return dd(a)},reset:function(){a=[];return db=!1},add_child_nodes:function(a,c,d){var e,g,f,i;i=a.node.childNodes;for(g=0,f=i.length;g<f;g++)(e=i[g])&&e.nodeName&&(this._add(e,!1,a.tagName,a.readOnly)||this.is_good_tag(e)&&d.push({node:e,tagName:a.tagName,readOnly:a.readOnly,parent_id:c}));return d},add_node:function(a,
c){return this._add(a,c)},_add:function(b,c,d,e){var g;g=null;b.nodeName===ab&&(g=A(b.nodeValue));c=c||!1;if("msie"===n.browser&&9>n.version&&e)return!1;if("msie"!==n.browser||9<=n.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(f){}if(g&&!this.is_html(g)&&3<=g.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(g,c);if(!c)return!1;a[c]=b}return g?!0:!1},_skim_id_hash:function(a){var c;if(!a)return"";c=A(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,"");c=""+c+":"+a.substring(0,20);return c=
rd(c)}}}();xd=function(a,b,c,d){var e,g,f,i,j,n,k,s,W,m,l;e=document.createDocumentFragment();k=0;s=[];l=b.nodeValue;i=[];j=b.parentNode;d||(d="skimwords-potential");c||(c="-1");if(j){for(W=0,m=a.length;W<m;W++)f=a[W],n=document.createElement("span"),n.className=d,g=document.createTextNode(l.substring(k,f.start)),e.appendChild(g),n.innerHTML=f.text,e.appendChild(n),k={},k.node=n,k.match=f,h(k,"occurrence",f.target_occurrence),s.push(k),k=f.start+f.text.length,i.push(g),Ha.add_node(g,c);a=document.createTextNode(l.substring(k));
i.push(a);e.appendChild(a);Ha.add_node(a,c);j.replaceChild(e,b)}return[s,i]};od=function(a,b,c){var d,e,g;if(na)return!1;d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);g=document.createElement("span");b=document.createDocumentFragment();g.innerHTML=d;if("msie"===n.browser&&9>n.version&&(d=a.previousSibling,e=/^\s/,d&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" "),(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[0])))d.nodeValue=
" "+d.nodeValue;for(;g.firstChild;)g.firstChild.nodeName===ab?(d=b.appendChild(g.firstChild),Ha.add_node(d)):(d=b.appendChild(g.firstChild),null!==d&&!c&&(Cb(d,!0),lb(d,!0)));if(c=a.parentNode)return c.replaceChild(b,a)};ud=function(a,b){10>parseInt(b)&&(b="0"+b);return"3"+a+"0"+b};nd=function(a,b){1E7<a&&6!==b&&(a-=1E7);return a};wd=function(a,b,c){var d,e,g;g=b.phrase;d={};d.w=g.text();d.lp=g.url();if(c)d.t=Cc,e="unlinked";else{if(0===g.limit())return!1;g.dec_limit();R+=1;d.ed=g.is_editor()?1:0;
d.t=ud("02",g.action_type(),g.group_id());e="skimwords";d.pid=0===g.group_id()?0:nd(g.id(),g.action_type())}yd(d,e);od(a,b,c);return!0};var zd,Ad,Bd,Cd,Dd,Ed,yc,Fd,sa,Cc;Cc="500005";Ad=function(a){p(a,"click",F);Za||p(a,"contextmenu",F);Cb(a,!1);return lb(a)};Ed=function(a){a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a);return a.length&&""!==a[0]?!0:!1};Cd=function(a,b,c,d){var e,g;e=Ma(a);g="";H&&(g='target="'+H+'"');b=kb(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+
e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+g+' data-skimwords-word="'+encodeURIComponent(kb(a))+('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:RegExp(e,"i"),repl_regex:RegExp(b,"i"),repl_text:a}};zd=function(){var a,b,c,d,e;b=T("skimlinks-unlinked");e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(Ad(a));return e};yc=function(a){var b,c,d,e;b={};if((c=a.merchant_domains)&&c.length){for(d=0,
e=c.length;d<e;d++)a=c[d],b[a]=!0;for(d=0,e=Db.length;d<e;d++)c=Db[d],a=c.match.domain,b.hasOwnProperty(a)&&wd(c.node,c.match,!0)}Kc(10,function(){return zd("skimlinks-unlinked")});try{return Ga("unlinked")}catch(g){return!0}};Bd=function(a,b){var c,d,e,g,f,i,h,j,k,s,m;if(!a||Ac(a,["span.skimlinks-unlinked"]))return[[],[]];m=a.data;e=[];i=[];for(k=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;d=k.exec(m);)if(c=d[0],"link.phrase"!==c)if(f=d.index,0<A(c).length&&
-1===c.indexOf("/.")&&-1===c.indexOf("..."))g=c,0!==c.indexOf("http")&&0!==c.indexOf("//")&&(g="msie"===n.browser&&6>=n.version?"http://"+c:"//"+c),d=ib(g),j=Gd({OriginalPhrase:""+c,Url:g,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(s=Cd(""+c,g,Cc,"skimlinks-unlinked"))&&i.push({start:f,text:""+kb(c),domain:d,repl_regex:s.repl_regex,replacement:s.repl_text,regex:s.search_regex,phrase:j,link:g}),e.push(d);else break;if(i.length){h=xd(i,a,b,"skimlinks-unlinked");c=h[0];h=h[1];for(k=0,m=c.length;k<
m;k++)i=c[k],Db.push(i)}h||(h=[]);return[e,h]};Fd=function(a){var b,c,d;if(ma.length)for(c=0,d=ma.length;c<d;c++)if(b=ma[c],b===a)return!1;if(da.length){for(c=0,d=da.length;c<d;c++)if(b=da[c],b===a)return!0;return!1}return!0};Dd=function(){var a,b,c,d,e,g,f;c=Ha.get_as_hash_node_dict();d={};for(b in c)if(a=c[b],a.parentNode&&!Ta(a)&&!la(a,"noskimwords")&&!la(a,"noskimlinks")&&!la(a,"noskimw")&&(!a.meta||!a.meta.ReadOnly)){a=Bd(a,b);f=a[0];for(e=0,g=f.length;e<g;e++)a=f[e],!d[a]&&Fd(a)&&(d[a]=!0,v.domains.push(a))}return v.domains.length?
nb(v.domains):Ga("unlinked")};sa=function(){var a;a=document.getElementsByTagName("body");a.length?(a=a[0].textContent||a[0].innerText)&&Ed(a)?Ea?(Ha.traverse([],rc,[]),Dd()):getSkimwordsData("skimwordsSettingsCallback"):v.domains.length&&nb(v.domains):v.domains.length&&nb(v.domains)};f.skimlinksUnlinked=yc;var Hd,Hb,Id,Jd,m,Ia,Kd,Ib,Ld,Md,Nd,Od,Pd,cb,Qd,z={}.hasOwnProperty;m={pag:"",pub:"",guid:"",uc:"",lnks:{}};Ia={};Jd=function(a,b){var c,d,e;e="GBP"===a.currency?"&pound;":"EUR"===a.currency?"&euro;":
"$";d=document.createElement("a");h(d,"href",a.url);h(d,"title",a.title);h(d,"target","_blank");Gc(d,"skimlinks-inline");h(d,"data-skim-creative",b);c=0;Da&&(c=1);h(d,"data-skimlinks-editor",c);c=parseFloat(Math.round(100*a.price)/100).toFixed(2);d.innerHTML=""+a.merchant+" "+e+c;p(d,"mousedown",F);return d};Id=function(a,b,c,d,e){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+e};Kd=function(a,b){var c,d,e,g,f,i,h;c=b.price;if(!c)return"0";d=0;e=1E8;f=0;for(i=0,h=a.length;i<
h;i++)g=a[i],g=parseFloat(g.price),g>d&&(d=g),parseFloat(g)<e&&(e=g),g===c&&f++;return 1<f?"4":c>=d?"3":c<=e?"1":"2"};Qd=function(a,b,c){var d,e,f,h,i;e=!1;for(d=h=0,i=a.length;h<i;d=++h)if(f=a[d],f.url===c){e=d;break}e&&(c=a[e],"beginning"===b?(a[e]=a[0],a[0]=c):"end"===b&&(a[e]=a[a.length-1],a[a.length-1]=c));return a};Pd=function(a){var b,c;if("1"===h(a,"ipc-added")){for(;")"!==(null!=(c=a.nextSibling)?c.textContent.substring(0,1):void 0);)(b=a.nextSibling)&&b.parentNode&&b.parentNode.removeChild(b);
if(a&&a.parentNode&&a.nextSibling)return a.parentNode.removeChild(a.nextSibling)}};Hd=function(a,b,c,d,e,g,j){var i,m,n,k,s,l,u,q,o,p,t,r,v,x;Pd(b);n=!0;s=b;k=!1;c=Qd(c,oc,d);e.hasOwnProperty(d)?(l=e[d],g[l].cnt++):(j[d]={},l={},l.lpid=d,l.cnt=1,l.url=b.href.replace(va,""),l.prd=[],l.ed=Da?1:0,g.push(l),l=g.length-1,e[d]=l);"cross"===Aa?h(b,"style","text-decoration: line-through !important;"):"text"===Aa?null!=b.parentNode&&(e=null!=(q=Tc(b.parentNode,"color"))?q:"#000",h(b,"style","color: "+e+" !important; text-decoration: none !important;")):
"blink"===Aa&&h(b,"style","text-decoration: blink !important;");e=c.length;q=0;if(f.skimlinks_editor)v=b.parentNode,r=document.createElement("span"),t=document.createElement("span"),i=b.cloneNode(!0),r.appendChild(i),r.appendChild(t),r.style.display="inline !important",r.classList.add("sl-select-wrapper"),t.classList.add("sl-select-products"),i.classList.add("sl-select-link");for(i=0,x=c.length;i<x;i++){u=c[i];k=!0;p=u.currency+u.price+u.url+u.title+u.merchant;q+=1;m=Kd(c,u);m=Id(Aa,m,e,a,q);if(!j[d].hasOwnProperty(p))o=
{},o.cur=u.currency,o.mn=u.merchant,o.mid=u.merchant_id,o.pr=u.price,o.ti=u.title,o.pu=u.url.replace(va,""),o.cr=m,g[l].prd.push(o),j[d][p]=!0;u=Jd(u,m);n?(p=document.createTextNode(" ("),n=!1):p=document.createTextNode(" | ");f.skimlinks_editor?(t.appendChild(p),t.appendChild(u)):(s.parentNode.insertBefore(p,s.nextSibling),p.parentNode.insertBefore(u,p.nextSibling));s=u}f.skimlinks_editor&&v.replaceChild(r,b);n||(a=document.createTextNode(") "),s.parentNode.insertBefore(a,s.nextSibling));h(b,"ipc-added",
1);return k};Md=function(a,b,c){var d,e;for(e in b)if(z.call(b,e)&&(d=b[e],e===a&&(0===d.length||ia(c,d))))return!0;return!1};Hb=function(a){var b,c,d,e,f,j,i,m,l,k,n;if(!a)return!1;d={};e=[];j={};c=[];m=!1;for(l in a)if(z.call(a,l)&&Ia.hasOwnProperty(l)&&(i=a[l],i.length)){f=Ia[l];for(k=0,n=f.length;k<n;k++)b=f[k],l=A(b.href),h(b,"rel"),Hd(1,b,i,l,d,e,j)&&(m=!0),c.push({url:l,occurrence:h(b,"data-occurrence"),products:i})}m&&"undefined"!==typeof Jb&&null!==Jb&&Jb(e);"undefined"!==typeof setSelectLinks&&
null!==setSelectLinks&&setSelectLinks(c);return!0};Ld=function(){var a;a="//ipc.skimresources.com/api/select_whitelist.php?callback=selectWhitelistCallback&data="+l(o({pubcode:E,page:B.href}));return ha(a,!1,{},Ib,[])};Nd=function(a){var b,c,d,e,f,h;e="//ipc.skimresources.com/api/select.php?callback=selectCallback&urls=";b="msie"===n.browser?2E3:8E3;c=[];for(f=0,h=a.length;f<h;f++)d=a[f],c.push(d),d=l(o(c)).length,d+e.length>b&&(c=c.slice(0,-1));if(c.length)return e+=l(o(c)),ha(e,!1,{},Hb,!1)};Od=
function(a){var b;b={urls:o(a),debug:1};b=ta(b);(S||!Va("//ipc.skimresources.com/api/select.php",b,Hb))&&Nd(a);return!0};Ib=function(a){var b,c,d,e,f,j,i,l,m,k,n,o,p,q,r;if(!1!==a&&0===a.length)return!1;n=[];j={};i=T();m=0;for(o=0,q=i.length;o<q;o++)if(b=i[o],e=K(b.hostname),k=A(b.href),l=h(b,"rel"),d=b.childNodes,!vb.length||ia(e,vb)){if(d&&d.length){f=!1;for(p=0,r=d.length;p<r;p++)c=d[p],c.nodeName&&"IMG"===c.nodeName.toUpperCase()&&(f=!0);if(f)continue}if(ja(k,e)&&ka(l)&&za(e)&&(j.hasOwnProperty(k)||
(j[k]=0),j[k]++,h(b,"data-occurrence",j[k]),h(b,"data-select-id",m),m++,!a||Md(k,a,j[k])))if(c=h(b,"class"),!c||!(-1!==c.indexOf("skimlinks-inline")||-1!==c.indexOf("skimwords-link")))if("undefined"===typeof Ia[k]&&(Ia[k]=[]),Ia[k].push(b),ia(k,n)||n.push(k),100<=n.length)break}return 0===n.length?!1:Od(n)};cb=function(){return Da?Ld():Ib(!1)};f.selectCallback=Hb;f.selectWhitelistCallback=Ib;f.skimlinksApplySelect=cb;var Gd;Gd=function(a){var b,c,d,e;d=b=null;c=5;a.Limit&&(c=a.Limit);e=function(){return a.Priority||
0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return c-1},limit:function(){return c},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},
id:function(){return d?d:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return d=a}}};var yd,eb,Rd,j,ea,M,Dc,Sd,Td,Ud,Vd,md,Ga,Jb,ra,Kb,Ja,z={}.hasOwnProperty;M="//t.skimresources.com/api/";j={pag:"",phr:[],unl:[],pub:"",
slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uuid:"",sessid:"",uc:"",t:1,slmcid:!1};ea={skimlinks:!0,skimwords:!0,unlinked:!0};Ja=0;Dc=!1;yd=function(a,b){var c,d,e,f;c=!0;if("skimwords"===b){for(e=0,f=Z.length;e<f;e++)if(d=Z[e],c=d.pid?d.pid===a.pid:d.w===a.w)return c;Z.push(a)}else if("unlinked"===b){for(e=0,f=$.length;e<f;e++)d=$[e],d.w===a.w&&(c=!1);c&&$.push(a);Ja++}return c};Ud=function(){var a,b,c,d,e,f;a=8E3;"msie"===n.browser&&(a=2E3);d={};d.guid=t;d.uuid=L;d.sessid=y;d.pub=E;d.pag=B.href;d.tz=
D;d.slmcid=Q;d.dl={};d.typ="l";d.hae=P?1:0;c=""+M+"link?data=";f=0;for(e in q)z.call(q,e)&&(b=q[e],f++,d.dl[e]=b,b=c+l(o(d)),b.length>a&&(f--,delete d.dl[e]));f&&(c+=l(o(d)),ha(c,!1,{async:!0}));return!0};Sd=function(a){for(var b in a)if(z.call(a,b))return!1;return!0};ra=function(){var a;if(bb||Sd(q))return!1;a={};a.guid=t;a.uuid=L;a.sessid=y;a.pub=E;a.pag=B.href;a.dl=q;a.tz=D;a.slmcid=Q;a.typ="l";a.hae=P?1:0;a={data:o(a)};x&&(a.dnt=x);U&&(a.fdnt=1);a=ta(a);if(S||!Va(""+M+"link",a,Kb))return Ud()};
md=function(a){var b,c,d;b=f.pageTracker;d=f.urchinTracker;c="/"+$a+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;f._gaq?(b=f._gaq,b.push(["_trackEvent",$a,"click",a])):f.ga&&f.ga("send","event","click",$a,a);return!1};Td=function(a){var b,c,d,e,f;m.tz=D;m.guid=t;m.uuid=L;m.sessid=y;m.pref=ba;m.lnks=[];m.typ="s";b=8E3;"msie"===n.browser&&(b=2E3);c=""+M+"ipc?data=";for(e=0,f=a.length;e<f;e++)d=a[e],m.lnks.push(d),d=c+l(o(m)),d.length>b&&(m.lnks=m.lnks.slice(0,
-1));m.lnks.length&&(c+=l(o(m)),ha(c,!1,{async:!0}));return!0};Jb=function(a){var b;if(bb)return!1;m.tz=D;m.guid=t;m.uuid=L;m.sessid=y;m.pref=ba;m.lnks=a;m.typ="s";b={data:o(m)};b=ta(b);(S||!Va(""+M+"ipc",b,Kb))&&Td(a);return!0};Kb=function(){return!0};Ga=function(a){var b,c;if(bb||Dc)return!1;ea[a]=!1;a=!0;for(b in ea)if(z.call(ea,b)&&(c=ea[b],!0===c)){a=!1;break}if(a)return Dc=!0,Rd()};eb=function(a){var b,c,d,e,f;if(a instanceof Array){c={};for(b=e=0,f=a.length;e<f;b=++e)d=a[b],c[""+b]=d;return c}return a};
Vd=function(){var a,b,c,d,e;a=(new Date).getTime()-Wb;b=8E3;"msie"===n.browser&&(b=2E3);j.tz=D;j.slc=P;j.swc="undefined"!==typeof R&&null!==R?R:0;j.ulc=null!=Ja?Ja:0;j.jsl=a;j.guid=t;j.slmcid=Q;j.uuid=L;j.sessid=y;j.pref=ba;j.phr=[];j.unl=[];na&&(j.xrf=1);a=""+M+"track.php?";x&&(a=a+"dnt="+x+"&");U&&(a+="fdnt=1&");S&&(a+="abp=1&");a+="data=";for(c=d=0,e=Z.length;d<e;c=++d)c=Z[c],j.phr.push(c),c=a+l(o(j).replace(va,"")),c.length>b&&(j.phr=j.phr.slice(0,-1));for(c=d=0,e=$.length;d<e;c=++d)c=$[c],j.unl.push(c),
c=a+l(o(j).replace(va,"")),c.length>b&&(j.unl=j.unl.slice(0,-1));j.phr=eb(j.phr);j.unl=eb(j.unl);b=a+l(o(j).replace(va,""));ha(b,!1,{async:!0});return qb(1)};Rd=function(){var a;a=(new Date).getTime()-Wb;j.tz=D;j.slc=P;j.swc="undefined"!==typeof R&&null!==R?R:0;j.ulc=null!=Ja?Ja:0;j.jsl=a;j.guid=t;j.slmcid=Q;j.uuid=L;j.sessid=y;j.pref=ba;a=j;a.phr=eb(Z);a.unl=eb($);a={data:o(a)};x&&(a.dnt=x);U&&(a.fdnt=1);a=ta(a);if(S||!Va(""+M+"track.php",a,Kb))return Vd(),!0;null!=f.skimlinks_runner&&(f.skimlinks_runner.tracking=
1);qb(1);return!0};var Wd=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(f.complete&&h.complete&&(e=!0),e&&"0"!=f.width&&"0"==h.width&&(d=!0))}var d=!1,e=!1,f=null,h=null;this.detect=function(a){b(a,250)};(function(){try{var b=navigator.userAgent.toLowerCase();if(-1==b.indexOf("firefox")&&-1==b.indexOf("chrome")){e=!0;d=!1;return}}catch(j){}b=11*Math.random();f=new Image;f.onload=c;f.src=a.replace(/\*/,1).replace(/\*/,
b);h=new Image;h.onload=c;h.src=a.replace(/\*/,2).replace(/\*/,b)})()}("//p.skimresources.com/px.gif?ch=*&rn=*");hc()})(this);
