(function(z){
var JK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.hp),b?-1:-a):a.Ok+(b?-1:1)};var KK=function(a){z.zv.call(this,a);this.Ok=0;this.jd="new"};var LK=function(a,b){a.eW=b};var MK=function(a){return a.get(a.k.op)};
var NK=function(a){return(0,z.P)('\x3cdiv class\x3d"fyre '+(a.fe?"fyre-liveblog ":"")+(a.Yg?"fyre-livechat ":"")+(a.IS?"fyre-bootstrap ":"")+(a.ge?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Ua?"fyre-avatar-disabled":"")+'"\x3e'+(a.Vu?z.im(z.Fs(a)):"")+(0,z.P)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Ua?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.Un?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var OK=function(a){return(0,z.P)('\x3ca href\x3d"'+z.Q(z.R(a.Da))+'" title\x3d"'+z.Q(a.Z)+'" data-id\x3d"'+z.Q(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.Q(a.rS)+'"\x3e\x3cimg src\x3d"'+z.Q(z.R(a.ud))+'" alt\x3d"'+z.Q(a.Z)+'" onerror\x3d"javascript:this.src\x3d\''+z.Q(z.Cm(a.Yb))+"';\" /\x3e\x3c/a\x3e")};
var PK=function(a){return(0,z.P)(z.Qq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.O(a.j.VM)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(a.j.tx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(a.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(a.j.ux)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var QK=function(a){return(0,z.P)('\x3cdiv class\x3d"tooltip"\x3e'+z.O(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var RK=function(){};var SK=function(a){z.Gf.call(this,a);this.OI=new z.Pe({url:[z.w.K.bW,"stats"].join("/"),method:"POST",with_credentials:!1});this.ws=[];this.Bc=z.u.setInterval((0,z.t)(this.ky,this),5E3)};var TK=function(a){return z.Oa(a,function(a){return a.rate?Math.random()<a.rate:!0})};
var UK=function(a){var b={},c=z.Oa(a,function(a){if("counter"!==a.type)return!0;a.metric in b?b[a.metric].value+=a.value:b[a.metric]=a;return!1});z.y(b,function(a){c.push(a)});return c};var VK=function(a,b){z.Ej.call(this,b,a)};var WK=function(a,b){z.AF.call(this,a,b)};var XK=function(a,b){var c=a.d.Fb;c.kh[4]&&(z.Oy(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.nr)},a)),z.Qy(c,4,(0,z.t)(function(a){b.Za(a,"threadBreakout",this.nr)})))};
var YK=function(a,b){var c=[a.Yl,a.Ky];a.sg&&c.push(a.sg);a.Qs&&c.push(a.Qs);a.Ly&&c.push(a.Ly);z.x(c,function(a){z.Io(a,"fyre-stream-sort-selected")});z.Go(b,"fyre-stream-sort-selected")};var ZK=function(a,b){z.AF.call(this,a,b)};var $K=function(a,b){z.rx.call(this,a,b);this.Xg=!1;this.KH=!!this.J.M.LF;this.Fa=new z.zx;this.Fa.pc(this);this.Lt="archiveShowMore"};var aL=function(a,b){z.yF.call(this,a,b)};var bL=function(a,b,c){z.Tt.call(this,a,b,c);this.ez=b||"";this.pg(QK(this.s()))};
var cL=function(a,b,c){z.Nt.call(this,a,b||3,c)};var dL=function(a,b){z.T.call(this,b);this.m=a};var eL=function(a,b){z.T.call(this,b);this.bc=a};var fL=function(a,b){eL.call(this,a,b)};var gL=function(a,b,c,d,f){z.zF.call(this,a,b,c,d,f)};
var hL=function(){var a=z.u.window,b=z.u.document;function c(){var a=C.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){C.KV||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(C,g)}function f(a){var b;if(a.cO)return a;if(C.JV&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.cO=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.CS&&a.CS("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var C={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.JV,shivMethods:!1!==g.KV,type:"default",shivDocument:f};f(b)};var iL=function(a,b){z.IF.call(this,a,b);a.M.WN||hL();var c=a.u.Lb(),d=a.u.v();this.gg=new gL(a,c,a.Bl.Ca,d.Yg()||z.cg);this.D(this.gg);a.M.Ua||(this.nn=new fL(c),this.D(this.nn));this.ur=new z.xF;this.D(this.ur)};var jL=function(a){var b=z.E.cb();return!a.B.fe()||b};var kL=function(a){z.Uy.call(this,a);this.Fm=1};var lL=function(a){z.Is.call(this,a);z.bv(a.u);this.Pb=new iL(a);this.Bq.start();this.pl(this.Pb);z.Ms(this)};
var mL=function(a,b){this.qC=VK;this.JI=lL;z.X.Do(b.strings||{});z.tl.call(this,a,b)};var nL=function(a){a.fk&&(a.fk.p(),delete a.fk)};z.v(KK,z.zv);z.e=KK.prototype;z.e.al=z.l(58);z.e.LE=z.l(60);z.e.ME=z.l(59);z.e.LE=z.K(60,function(a){this.Ia||(this.jo[a]=!1,z.Av(this,a,function(a){a.N(a.xa.Em)}))});
z.e.ME=z.K(59,function(a,b){if(!this.Ia){var c=this.d.u.v(),d=z.yu(a,b),f=c.get(z.U.jt);c.set(z.U.hp,d.TT);z.y(d.ab,(0,z.t)(this.d.T.N,this.d.T,"bootstrap_author_received"));d.content=z.hj(d.content,function(a,b){return!z.Ta(f,b)});z.y(d.content,function(a){z.kb(d.content,z.Cv(this,a))},this);z.kb(this.Cc,z.gj(d.content,z.Cb(a)));this.Td(a,d.content);z.Av(this,a,function(b){b.N(b.xa.tk,{Ed:a});b.set(b.k.af,!0)})}});
z.e.al=z.K(58,function(a,b){this.Ok=a;this.jd=b||this.jd;var c=this.Fd[a]=new z.vv;z.Su.C();var d=this.d.u.v(),f=(0,z.t)(this.ME,this,a),g=(0,z.t)(this.LE,this,a),h=this.d.M.Jm,d=d.get(z.U.Qc),h=z.w.ou(d,h)+String(a)+".json";z.Tu(0,h,f,g);return c});z.dG.prototype.al=z.K(57,function(a,b){this.Dk||(this.Dk=new KK(this.J));var c=this.Dk,d=JK(c,a,b);return c.al(d,a)});z.Su.prototype.Ph=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.K.vd,z.w.Ye,a.na);(new z.Pe({url:a,wa:b,ra:c})).send()});
z.Qv.prototype.Ph=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.Su.C().Ph;z.Rv(this,c,b,a);return a});z.dG.prototype.Ph=z.K(47,function(){z.Wv(this);this.Bi=new z.Qv(this.J,void 0);var a=new z.vv;this.Bi.Ph(a);return a});z.Su.prototype.Lh=z.K(46,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.K.vd,z.w.Ye,a.na,a.PM);(new z.Pe({url:a,wa:b,ra:c})).send({format:"stream"})});z.Qv.prototype.Lh=z.K(45,function(a,b){var c={na:this.d.u.v().id,PM:a},d=z.Su.C().Lh;z.Rv(this,d,c,b);return b});
z.dG.prototype.Lh=z.K(44,function(a){z.Wv(this);this.Bi=new z.Qv(this.J,void 0);var b=new z.vv;this.Bi.Lh(a,b);return b});z.T.prototype.XF=z.K(43,function(){return this.aa});z.Bj.prototype.Un=z.K(42,function(){return this.get(this.k.gp)});z.v(RK,z.zl);z.da(RK);var oL={dX:"attachmentDelegate"};z.kb(oL,z.rG);RK.prototype.Qn=function(a){var b=RK.b.Qn.call(this,a),c=a.attachmentDelegate;c&&(b.XM=c);b.mx=a[oL.MK]||null;return b};z.v(SK,z.Gf);SK.prototype.send=function(a){this.ws=this.ws.concat(a)};SK.prototype.ky=function(){var a=UK(this.ws),a=TK(a);a.length&&this.OI.send(z.kd(a),{"Content-Type":"application/json"});this.ws=[]};SK.prototype.p=function(){(0,window.clearInterval)(this.Bc);this.OI=null;SK.b.p.call(this)};z.v(VK,z.Ej);VK.prototype.vy=function(a){this.wi=new z.Ou(this);this.Xt=new z.Gq(this,a);this.Ic=new z.yi(this);this.bb=new z.kv(this,a);this.Bl=new z.rv(this);this.u=new z.$u(this,a);this.Jb=new z.dG(this,a);new z.rf;this.Go=new z.gw(this,a);this.cW=new SK(this);this.Fb=new z.Ey(this)};z.v(WK,z.AF);z.e=WK.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.hx=b.v().fe();a.QT=!z.E.get(z.E.k.Pd);a.tl=b.tl(z.E.id);a.ZN=2===c.get(z.U.xk);a.YN=3===c.get(z.U.xk);a.j={YS:z.X.get(z.X.g.zt),aT:z.X.get(z.X.g.At),pS:z.X.get(z.X.g.vA),tx:z.X.get(z.X.g.Cp),ux:z.X.get(z.X.g.Dp),zo:z.X.get(z.X.g.xB),Qo:z.X.get(z.X.g.Gp),sW:z.X.get(z.X.g.PB)};return a};
z.e.G=function(a){WK.b.G.call(this,a);a=this.c;var b;b=this.s();var c=z.P,d=z.Qq(b),f;f=b.hx?(0,z.P)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.QT?b.tl?z.O(b.j.aT):z.O(b.j.YS):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(b.j.tx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(b.j.ux)+"\x3c/a\x3e"+(b.ZN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.O(b.j.sW)+"\x3c/a\x3e":"")+(b.YN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.O(b.j.pS)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.$k=this.n("fyre-follow-conversation");this.Qs=this.n("fyre-stream-sort-hot-threads")||
null;this.Ly=this.n("fyre-stream-sort-top-comments")||null;this.sg=this.n("fyre-stream-sort-back");this.Yl=this.n("fyre-stream-sort-newest");this.Ky=this.n("fyre-stream-sort-oldest");this.PH=this.n("fyre-stream-sort-options");this.Zc=this.n("fyre-content-loading");this.Ad()};z.e.l=function(){WK.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Lf,this.Kn,this);a.e(this.c,"click",this.hb);z.x([3,4,5],function(b){z.BF(this,a,b)},this);XK(this,a)};
z.e.hb=function(a){a.preventDefault();a=a.target;if(!z.Mo(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.sg)if(a===this.$k)this.KE();else switch(YK(this,a),this.Xl(),a){case this.Qs:this.CD();break;case this.Ly:this.dispatchEvent({type:"sortTopComments",Tb:(0,z.t)(this.Ad,this)});break;case this.Yl:this.bn("new");break;case this.Ky:this.bn("old")}};z.e.ti=function(a,b){a&&this.wy(b);z.Hn(this.PH,"display",a?"none":"block");z.Hn(this.sg,"display",a?"block":"none")};
z.e.wy=function(a){var b=this.Yl,c=this.bn,d=z.X.get(z.X.g.kt);4===a&&(b=this.Qs,c=this.CD,d=z.X.get(z.X.g.YI));this.sg.innerHTML=d;this.q().uf(this.sg,"click",(0,z.t)(function(a){a.stopPropagation();this.ti(!1);YK(this,b);c.apply(this)},this))};z.e.Hn=function(a){a.stopPropagation();this.ti(!1);YK(this,this.Yl);this.bn()};z.e.nr=function(a){var b=a.Tb;z.kb(a,{Tb:(0,z.t)(function(){b();this.ti(!0,4)},this)})};
z.e.bn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Tb:(0,z.t)(this.Ad,this)})};z.e.CD=function(){this.dispatchEvent({type:"sortHotThreads",Tb:(0,z.t)(this.Ad,this)})};z.e.KE=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.tl(z.E.get(b.X)),a.nj(!b),a=b?z.X.get(z.X.g.zt):z.X.get(z.X.g.At),this.$k.innerHTML=a):z.Qh(this.d.Ic,(0,z.t)(this.KE,this))};
z.e.Kn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.fe()||z.E.get(c.Pd);this.$k&&(b?z.S(this.$k,!1):(a=a.tl(z.E.id)?z.X.get(z.X.g.At):z.X.get(z.X.g.zt),this.$k.innerHTML=a,z.S(this.$k,!0)))};z.e.h=function(){WK.b.h.call(this);z.E.off(null,null,this)};z.v(ZK,WK);ZK.prototype.G=function(a){this.c=a;z.Vl(a,PK,this.s());this.Yl=this.n("fyre-stream-sort-newest");this.Ky=this.n("fyre-stream-sort-oldest");this.PH=this.n("fyre-stream-sort-options");this.Zc=this.n("fyre-content-loading");this.Ad()};ZK.prototype.bn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.eW.stream,direction:a,Tb:(0,z.t)(this.Ad,this)})};
ZK.prototype.s=function(){return{j:{VM:z.X.get(z.X.g.TI),tx:z.X.get(z.X.g.Cp),ux:z.X.get(z.X.g.Dp),zo:z.X.get(z.X.g.xB),Qo:z.X.get(z.X.g.Gp)}}};z.v($K,z.rx);z.e=$K.prototype;z.e.Rm=function(a){this.clear();z.S(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Hd();this.sb={};this.uj=[];for(this.lh=this.Gk=null;this.ma&&0!=this.ma.length;)this.qo(0).p()};z.e.G=function(a){$K.b.G.call(this,a);z.Vl(this.c,z.Rq,this.s());this.Zj=this.n("fyre-stream-content");this.ui=this.n("fyre-stream-more");this.Fa.R(this.ui);z.S(this.ui,!1)};z.e.h=function(){this.Fa&&this.Fa.p();this.Fa=null;$K.b.h.call(this)};
z.e.l=function(){$K.b.l.call(this);this.q().e(this.Fa,"showMore",this.sw)};z.e.vv=function(){return this.J.M.LF};z.e.s=function(){return{Rc:z.w.K.kb,Ou:!!this.Fa,j:{Cy:z.X.get(z.X.g.UI)}}};z.e.uw=function(){this.Fa.Ms();this.Xg=!0};z.e.Mx=function(){this.dispatchEvent({type:this.Lt,direction:this.jd,target:this,GW:this.Xg&&this.KH,Tb:(0,z.t)(this.uw,this),mj:(0,z.t)(this.iF,this)});this.Xg&&(this.KH=!1)};z.e.Tx=function(a){this.Xg||$K.b.Tx.call(this,a)};
z.e.Fo=function(){var a=this.J.Jb.Dk,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.hp),c=!b&&a.Ok>-c;b&&-1>a.Ok||c?this.Fa.show():this.Fa.nb()};z.e.start=function(){this.Xg||this.Mx()};z.v(aL,z.yF);var pL=z.X.g,qL={};qL.comment=[pL.zm,pL.Mf,pL.mm];qL.liveblog=[pL.nL,pL.AK,pL.AA];aL.prototype.hE=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.m.fe()?"liveblog":"comment",c=qL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.tG[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.v(bL,z.Tt);bL.prototype.Io=200;bL.prototype.Rh=function(){return new cL(this.Hc)};bL.prototype.s=function(){var a={};a.message=this.ez;return a};z.v(cL,z.Nt);cL.prototype.Mc=function(a,b,c){var d=z.go(this.element),d=new z.Ah(d.width,d.height+25);b=z.It(this.element,this.Bh,a,b,d,c,9);z.Nn(a.lastChild,0);b&&(d=new z.Ah(0,-5),z.It(this.element,2,a,1,d,c,5),z.Nn(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(dL,z.T);z.e=dL.prototype;z.e.r=function(){this.c=z.Yl(OK,this.s())};z.e.l=function(){dL.b.l.call(this);this.Sa=new bL(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.hb)};z.e.h=function(){dL.b.h.call(this);this.Sa&&this.Sa.p()};z.e.s=function(){var a=z.Wd,b={};b.ud=this.m.get(a.ub);b.Yb=this.m.get(a.lk);b.Z=this.m.get(a.ua);b.id=this.m.id;b.rS=this.m.id.replace(/[@.]/g,"-");b.Da=this.m.get(a.Vb);return b};
z.e.hb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.v(eL,z.T);z.e=eL.prototype;z.e.EA=10;z.e.h=function(){eL.b.h.call(this);delete this.bc};z.e.Q=function(){eL.b.Q.call(this);this.bc.off(null,null,this)};z.e.uE=function(a){a=new dL(a);var b=this.Lc();if(b===this.EA){var c=this.qo(b-1);c&&(c.p(),b--)}0<b?this.xe(a,0,!0):this.D(a,!0)};z.e.vR=function(a){var b;this.Tc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Xh=function(){this.bc.on(this.bc.xa.it,this.uE,this);this.bc.on(this.bc.xa.It,this.vR,this);var a=this.bc.ob.reverse().slice(0,this.EA);z.x(a,this.uE,this)};z.v(fL,eL);z.v(gL,z.zF);gL.prototype.G=function(a){gL.b.G.call(this,a);this.Qj()};gL.prototype.Qj=function(){this.c.innerHTML=z.Uq(this.s())};z.v(iL,z.IF);
iL.prototype.hH=function(a,b){if(!this.Ia){this.B=b;var c=b.get(z.U.uh),d=b.get(z.U.Qd);this.ct=new z.FF(c,d,a.M.Ua);this.D(this.ct);this.lq=new aL(a.u.v());this.D(this.lq);this.Zr=null;b.Un()&&(this.hu=new ZK(a),this.D(this.hu),this.Ek=new $K(a),this.D(this.Ek),LK(this.hu,{stream:this.Ek}));this.ih=new WK(a);this.D(this.ih);this.Rr((0,z.t)(function(a){this.Zb=a;this.D(this.Zb);a=this.Zb;this.aa&&a&&a.R(this.Ce,!0)},this));b.get(z.U.sm)&&!z.cg&&MK(this.B)&&(this.B.Yg()||this.B.fe()||this.Xv())}};
iL.prototype.s=function(){var a=!this.d.M.bq&&!z.w.Mu&&!this.d.M.yD;return{jI:z.w.K.fz,kI:(0,window.encodeURIComponent)(String(window.location.href)),Ua:this.d.M.Ua,Yg:this.B.Yg(),fe:this.B.fe(),ge:z.cg,Vu:a,IS:this.d.M.bq,Un:this.B.Un()}};z.Fx={$W:"fyre-archive-stream",aX:"fyre-archive-stream-header",M_:"fyre-top-content-stream",e0:"fyre-widget",sm:"fyre-featured-content-wrapper"};z.kb(z.Fx,z.uJ);z.e=iL.prototype;
z.e.r=function(){this.c=z.Yl(NK,this.s());var a=this.B.get(z.U.xk);if(1!==a){var b=this.d.Fb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Fy(b,a,c,this)}this.ur.R(this.n(z.Fx.lK));this.Ek&&(b=this.n("fyre-archive-stream-header"),this.hu.R(b),this.Ek.R(this.n("fyre-archive-stream")));this.Ch(1);this.Ce=this.n(z.Fx.sh);b=jL(this);z.S(this.Ce,b)};
z.e.l=function(){iL.b.l.call(this);var a=this.Zb;this.aa&&a&&a.R(this.Ce,!0);this.d.T.So("stream_data_received",this.tQ,this);this.q().e(this,"request_content_context",this.UP).e(this,"request_content_reply",this.yR);this.Ek&&this.Ek.start()};z.e.Xh=function(){this.nn&&this.nn.Xh();this.gg.Xh()};z.e.tQ=function(){var a=this.B,b=a.get(z.U.ok);z.rh||b||(b=(0,z.t)(function(){this.Zr=new z.rL(this.d,a.get(z.U.Qd));this.D(this.Zr,!0)},this),z.uc(z.w.K.kb+z.w.xf.Zr,null,null,b))};
z.e.Xv=function(){var a=new z.qE(this.XF,this);a.KG=(0,z.t)(this.fV,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.uc(z.w.K.kb+z.w.xf.FO,null,null,b)};z.e.fV=function(){var a=this.n("fyre-featured-content-wrapper");this.hv=new z.KJ(this.d);this.D(this.hv);this.hv.R(a);this.hv.Wg()};z.e.Rr=function(a){if(!this.d.M.readOnly){var b=this.d.u.v();z.Bw(z.yw.C(),"main",a,{J:this.d,mi:"new"},b);z.E.on(z.E.hc(z.E.k.X),this.Vc,this)}};z.e.Vc=function(){var a=jL(this);z.S(this.Ce,a)};
z.e.Wh=function(){0<z.xo(this,this.Zb)&&(this.removeChild(this.Zb),this.Zb.p());this.Rr((0,z.t)(function(a){this.Zb=a;this.D(this.Zb);a=this.Zb;this.aa&&a&&a.R(this.Ce,!0);z.S(this.Ce,!0)},this))};z.e.Ug=function(a){null!=a&&(this.d.Fb.gl(1),(0,window.setTimeout)((0,z.t)(function(){this.Ia||z.JF(this,a)},this),3E3))};z.e.UP=function(a){z.JF(this,a.Jk)};z.e.yR=function(a){z.JF(this,a.Jk,function(a){z.xw(a.Ib)})};
z.e.h=function(){iL.b.h.call(this);z.E.off(z.E.hc(z.E.k.X),this.Vc,this);this.B&&(this.B.off(null,null,this),this.B=null)};z.v(kL,z.Uy);z.e=kL.prototype;z.e.ce=function(a,b){kL.b.ce.call(this,a,b);a.e(b,"repliesExpanded",this.HE);a.e(b,"sortHotThreads",this.IR);a.e(b,"sortOrderChanged",this.lF);a.e(b,"sortTopComments",this.JR);a.e(b,"archiveShowMore",this.FP);a.e(b,"archiveSortOrderChanged",this.GP)};
z.e.FP=function(a){var b=a.Tb||z.n,c=(0,z.t)(this.He,this,a.target),d=this.d.Jb;a=a.GW;d.Dk||(d.Dk=new KK(d.J));d=d.Dk;a=a?d.Ok:JK(d);var f=d.me[a];f&&(d.Ok=a);if(f)b(),c(f);else{d=this.d.Jb.al();a=d.k.af;if(d.get(a))b();else d.on(d.hc(a),b,this);z.Vy(this,d,c)}};z.e.Sv=function(a,b){var c=2===b.$c,d=1!==b.$c;switch(b.type){case 0:var f=this.d.u.v(),f=z.tk(b,f),g=f.get(z.Hk),g=this.d.u.ab().get(g);f.set(z.uk,g);a.jw(f,c,d)}};
z.e.dF=function(a){if(1!==this.Fm){var b=this.XV.ih;b.ti(!1);YK(b,b.Yl);z.kb(a,{direction:"new",Tb:z.n});this.lF(a)}};z.e.GP=function(a){z.Wy(this);a.stream.Rm(a.direction);var b=this.d.Jb.al(a.direction,!0),c=(0,z.t)(function(b){a.Tb();this.He(a.stream,b)},this);z.Vy(this,b,c,a.mj)};z.e.lF=function(a){this.d.M.Rn=null;var b=z.Yy(this,1);z.Wv(this.d.Jb);b.Rm(a.direction);var c=z.Vv(this.d.Jb,a.direction),d=(0,z.t)(function(c){a.Tb();this.He(b,c)},this);z.Vy(this,c,d,a.mj)};
z.e.JR=function(a){var b=z.Yy(this,3),c=this.d.Jb.Lh("likes");z.Vy(this,c,(0,z.t)(function(c){a.Tb();z.hb(c)?z.qx(b):this.He(b,c)},this))};z.e.IR=function(a){var b=z.Yy(this,4),c=this.d.Jb.Ph();z.Vy(this,c,(0,z.t)(function(c){a.Tb();z.hb(c)?z.qx(b):this.He(b,c)},this))};z.v(lL,z.Is);z.e=lL.prototype;z.e.c=null;z.e.h=function(){lL.b.h.call(this);this.Ss.p();this.TC.p();this.Pb.aa&&this.Pb.p();this.Kf&&this.Kf.p();delete this.Kf};z.e.pl=function(a){lL.b.pl.call(this,a);this.Ss=new kL(this.d);this.Ss.handle(a);this.TC=new z.Ty(this.d);this.TC.handle(a)};z.e.Sy=function(){this.d.wi.stop()};z.e.dW=function(){this.d.Bl.stop()};z.e.Wj=function(){this.d.wi.start()};z.e.$V=function(){this.d.Bl.start()};
z.e.oa=function(){this.Kf&&this.Kf.p();this.Pb.oa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.IM)z.Ns(this);else{var a=z.Ks(this);this.Pb.Ug(a)}this.d.T.N("render_complete")};z.v(mL,z.tl);mL.prototype.jC=RK.C();mL.prototype.h=function(){mL.b.h.call(this);this.stop();delete this.M;delete this.ha;nL(this);z.yl(this);this.lj&&(this.lj.p(),delete this.lj)};mL.prototype.$y=function(){this.stop();nL(this);mL.b.$y.call(this)};z.lg.main.Eh.ia(mL);})(fyre.conv);
