(function(n,d){var A,E,G,C,F,t,x,w,z,B,D,y;t=function(u){u.a={u:"edge.simplereach.com",ta:"d8rk54i4mohrb.cloudfront.net",Ka:"/n",wb:"/t",W:"/event",qa:"/pixel?bad=true&error=",Ib:"/iframe.html",ua:"/container.html",ja:"000000000000000000000000",ia:"SPR-ERROR: ",za:"100 - Missing url",ib:"__reach_config",sa:"cache_buster",fa:"__srret",ma:"__srui",I:"0",Xa:"1",Ia:"img",Ya:"1px",width:"width",eb:d.location.protocol,f:"undefined",error:"error",Va:"off",info:"info",C:"SPR_DEBUG",ha:"//",T:"string",referrer:"referrer",uid:"uid",
b:"callback",h:"jsonp",url:"url",A:"pid",ga:"s",r:"r",t:"t",e:"e",x:"x",n:"n",Ha:"ignore_errors",cb:"preview",J:"authors",K:"channels",U:"tags",F:"date",Ja:"inframe",Hb:"iframe",wa:"custom_tracking",jb:"reach_tracking",ea:"ref_url",ca:"page_url",Jb:"user_id",Ta:"manual_scroll_depth",fb:"rd",Y:"fb",na:"de",Qa:"li",yb:"tw",$a:"pi",va:"csd",Aa:"api.facebook.com",Cb:"feeds.delicious.com",zb:"cdn.api.twitter.com",Ra:"www.linkedin.com",ab:"partners-api.pinterest.com",gb:"www.reddit.com",Ca:"/restserver.php",
hb:"/api/info.json",Db:"/v2/json/urlinfo/data",Ab:"/1/urls/count.json",Sa:"/countserv/count/share",bb:"/v1/urls/count.json",Ba:"links.getStats",La:"["+this.error+"] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",pb:"[info] sending scrollDepth of: ",ob:"[info] scroll depth not activated, not sending data"};return u}({});A=function(d){d.a={current:{}};return d}({});x=function(d,l){var g=d.a;l.a={mb:function(){return Math.floor(8675309*Math.random())},P:function(c){return Array.isArray?
Array.isArray(c):"[object Array]"===Object.prototype.toString.call(c)},log:function(c){n.console&&console.log(c)},na:function(c){return"[object String]"===Object.prototype.toString.call(c)},H:function(c){var b={},a;for(a in c)c.hasOwnProperty(a)&&(b[a]=c[a]);return b},ba:function(c,b){for(var a in b)b.hasOwnProperty(a)&&(c[a]=b[a]);return c},contains:function(c,b){return-1!==(c.join(",")+",").indexOf(b.toString()+",")},N:function(c){typeof c===g.T&&(c=c.split(","));if(this.P(c)){for(var b=0;b<c.length;b+=
1)typeof c[b]===g.T&&(c[b]=c[b].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return c.join("|")}},w:function(){},Z:function(){return n.location.protocol+"//"}};return l}(t,{});w=function(u,l,g){var c=u.a,b=l.a;g.a={X:!1,info:b.w,error:b.log,c:function(){n[c.C]&&(this.X=!0,n[c.C][c.info]&&(this[c.info]=n[c.C][c.info]),n[c.C][c.error]&&(this[c.error]=n[c.C][c.error]))},reset:function(){this.X=!1;this[c.info]=b.w;this[c.info]=b.log},sb:function(a){var b=d.createElement(c.Ia);b.src=c.eb+c.ha+
c.u+c.qa+a.message;b.setAttribute(c.width,c.Ya);d.body?d.body.appendChild(b):d.head.appendChild(b)},tb:function(a){a===c.info?(this[c.info]=b.log,this[c.error]=b.log):a===c.error?(this[c.info]=b.w,this[c.error]=b.log):(this[c.info]=b.w,this[c.error]=b.w)}};return g}(t,x,{});z=function(u,l,g){var c=u.a,b=l.a,b={f:"undefined",info:"info"};g.a={I:0,s:{x:0,y:0},O:!0,c:function(){function a(){h.O=d[e]?!1:!0}function c(){h.flush();n.removeEventListener("DOMContentLoaded",c,!1)}function f(){/loaded|interactive|complete/.test(d.readyState)&&
(d.detachEvent("onreadystatechange",f),p&&(p=!1,h.flush()))}var h=this,e,q;h.I=0;this.Wa(n,"mousemove",function(a){h.s={x:a.clientX,y:a.clientY}});typeof d.hidden!==b.f?(e="hidden",q="visibilitychange"):typeof d.mozHidden!==b.f?(e="mozHidden",q="mozvisibilitychange"):typeof d.msHidden!==b.f?(e="msHidden",q="msvisibilitychange"):typeof d.webkitHidden!==b.f&&(e="webkitHidden",q="webkitvisibilitychange");typeof d.addEventListener!==b.f&&typeof e!==b.f&&d.addEventListener(q,a,!1);var p=!0;n.addEventListener?
n.addEventListener("DOMContentLoaded",c,!1):d.attachEvent&&d.attachEvent("onreadystatechange",f)},oa:function(a,k){var f=d.createElement("iframe"),h=d.body;f.setAttribute("name","spr");f.src=a;f.setAttribute("height","1");f.setAttribute("width","1");f.setAttribute("visible","false");f.setAttribute("id","spr-iframe-"+k);f.style.display="none";h||(h=this.g("BODY")[0]);h||(h=this.g("HEAD")[0]);c[b.info](a);h.appendChild(f);return f},xa:function(){for(var a=this.g("link"),b=this.g("meta"),f=0;f<a.length;f+=
1)if("canonical"===a[f].rel)return a[f].href;for(;f<b.length;f+=1)if("og:url"===b[f].getAttribute("property"))return b[f].content;return!1},kb:function(a){var b=d.body,f=this.g("BODY")[0],c=this.g("HEAD")[0];b&&b.contains(a)?b.removeChild(a):f&&f.contains(a)?f.removeChild(a):c&&c.contains(a)&&c.removeChild(a)},pa:function(a){var k=this,f=d.createElement("script");f.type="text/javascript";f.setAttribute("async",!0);f.setAttribute("name","spr");f.setAttribute("id","spr-script");f.src=a;c[b.info](a);
this.R(function(){setTimeout(function(){k.g("HEAD")[0].appendChild(f)},1)});return f},i:[],ready:/loaded|interactive|complete/.test(d.readyState),flush:function(){var a=this.i.shift();for(this.ready=!0;a;)a(),a=this.i.shift()},R:function(a){this.ready?(this.i.push(a),this.flush()):d.documentElement.doScroll?n.self===n.top?function(){if(!d.uniqueID&&d.expando)return this.i.push(a);try{d.documentElement.doScroll("left"),a()}catch(b){setTimeout(arguments.callee,0)}}():this.i.push(a):this.i.push(a)},
Wa:function(a,b,f){a.addEventListener?a.addEventListener(b,f,!1):a.attachEvent("on"+b,f);return a},Va:function(a,b,f){a.addEventListener?a.removeEventListener(b,f,!1):a.detachEvent("on"+b,f);return a},G:function(){var a=0,a=n.pageYOffset?n.pageYOffset:d.documentElement?d.documentElement.scrollTop:0;return a-this.I},g:function(a){var b=[],f,c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(d.getElementById(a.substring(1)));break;case ".":f=d.getElementsByTagName("*");
for(e=" "+a.substring(1)+" ";c<f.length;c+=1)a=(" "+f[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(e)&&b.push(f[c]);break;default:b=d.getElementsByTagName(a)}return b}};return g}(w,t,{});B=function(d,l,g){var c=d.a,b=l.a;g.a={encode:function(a,b){var f=[];if(c.P(a))for(var h=0,e;h<a.length;h+=1)e=a[h],/\[\]$/.test(b)?f.push(encodeURIComponent(b)+"="+encodeURIComponent(e)):f.push(this.encode(e,b+"["+("object"===typeof e?h:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)f.push(encodeURIComponent(b)+
"="+encodeURIComponent(a));else for(h in a)Object.prototype.hasOwnProperty.call(a,h)&&(b?f.push(this.encode(a[h],b+"["+h+"]")):f.push(this.encode(a[h],h)));return f.join("&")},decode:function(a){var d={},f=0,h={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");f<a.length;f+=1){var e=a[f].split("="),q=decodeURIComponent(e[0]),p=d,g=0,m=q.split("]["),v=m.length-1;/\[/.test(m[0])&&/\]$/.test(m[v])?(m[v]=m[v].replace(/\]$/,""),m=m.shift().split("[").concat(m),v=m.length-1):v=0;if(2===
e.length)if(e=(e=decodeURIComponent(e[1]))&&!isNaN(e)?+e:e===b.f?void 0:void 0!==h[e]?h[e]:e,v)for(;g<=v;g+=1)q=""===m[g]?p.length:m[g],p=p[q]=g<v?p[q]||(m[g+1]&&isNaN(m[g+1])?{}:[]):e;else c.P(d[q])?d[q].push(e):d[q]=void 0!==d[q]?[d[q],e]:e;else q&&(d[q]=void 0)}return d}};return g}(x,t,{});D=function(u,l){l.a={da:{},$:function(g){var c=d.cookie||"",b=this.da[g];b||(b=g.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),b=new RegExp("(?:^|;)\\s?"+b+"=(.*?)(?:;|$)","i"),this.da[g]=b);return(g=c.match(b))&&
decodeURIComponent(g[1])},S:function(g,c,b){var a="";b&&(a="; expires="+b.toGMTString());d.cookie=g+"="+c+a+"; path=/"},Eb:function(d){this.S(d,"",new Date(1982,5,13))}};return l}(B,{});y=function(d,l,g,c){var b=d.a,a=l.a,k=g.a;c.a={callbacks:{},h:function(f,c,e,d,p){d=d||function(){};p||(p="cb");var g="cb"+k.mb(),m=this;e[p]="SPR.API.callbacks."+g;p=k.Z();"file://"===p&&(p="http://");e=b.encode(e);var v=a.pa(p+f+c+"?"+e);m.callbacks[g]=function(a){setTimeout(function(){v.parentNode.removeChild(v)},
0);d(a);try{delete m.callbacks[g]}catch(b){m.callbacks[g]=null}}}};return c}(B,z,x,{});E=function(u,l,g,c,b,a,k){var f=u.a,h=l.a,e=g.a,q=c.a,p=b.a,H=a.a,m=[25,50,75,100];k.a={D:[],data:{},Lb:null,options:null,Mb:!1,c:function(a,b){this.reset();this.options=b;this.response=a;var f=this;h.current[e.Ta]||H.R(function(){var a=f.Ea();f.height=a;typeof d.addEventListener!==e.f?d.addEventListener("scroll",function(){f.L()},!1):n.attachEvent("onscroll",function(){f.L()});f.L()})},L:function(){var a=Math.min(d.documentElement.clientHeight,
n.innerHeight||0),a=this.Fa()+a,b=0,b=a>=this.height?100:a/this.height*100;97<=b?this.B(100):75<=b?this.B(75):50<=b?this.B(50):25<=b&&this.B(25)},Ea:function(){var a=d.body,b=d.documentElement;return Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight)},Fa:function(){var a="CSS1Compat"===(d.compatMode||""),b=0;return b=void 0!==n.pageYOffset?n.pageYOffset:a?d.documentElement.scrollTop:d.body.scrollTop},B:function(a){this.data={};if(!f.contains(m,a))p[e.error](e.La);
else if(!f.contains(this.D,a))if(this.rb(a),this.response[e.va])this.qb();else p[e.info](e.ob)},rb:function(a){var b,c;for(b=0;b<m.length;b+=1)c=m[b],a>=c&&!f.contains(this.D,c)&&(this.D.push(c),this.data[c]=!0,p[e.info](e.pb+c))},Za:function(){return f.ba({event:"csd",sd:this.data},this.options)},qb:function(){var a=this.Za();q.h(e.u,e.W,a)},reset:function(){this.D=[]}};return k}(x,A,t,y,w,z,{});C=function(d,l,g,c){var b=d.a,a=l.a,k=g.a;c.a={Ua:[{name:a.Y,l:a.Aa,m:a.Ca,b:a.b,v:!1},{name:a.Qa,l:a.Ra,
m:a.Sa,b:a.b,v:!1},{name:a.$a,l:a.ab,m:a.bb,b:a.b,v:!1},{name:a.yb,l:a.zb,m:a.Ab,b:a.b,v:!1},{name:a.fb,l:a.gb,m:a.hb,b:a.h,v:!1}],lb:function(b,c){return b===a.Y?{format:"json",method:a.Ba,urls:c}:{url:c}},vb:function(c,d){return function(e){e={event:a.ga,url:c.url,cid:c.id,pid:c.pid,sn:c.name,data:e};k.ba(e,d);b.h(a.u,a.W,e)}},o:function(a,c){for(var e=this.Ua,d="https://"===k.Z()?!0:!1,g=null,l=0;l<e.length;l+=1){var g=e[l],m=k.H(a);m.name=g.name;!a[g.name]||d&&g.v||b.h(g.l,g.m,this.lb(g.name,
m.url),this.vb(m,c),g.b)}}};return c}(y,t,x,{});G=function(u,l,g,c){var b=u.a,a=l.a,k=g.a;c.a={ra:function(c){var g,e;e=a.H(c);e[b.J]&&(e[b.J]=a.N(e[b.J]));e[b.K]&&(e[b.K]=a.N(e[b.K]));e[b.U]&&(e[b.U]=a.N(e[b.U]));e[b.F]&&typeof e[b.F]!==b.T&&(e[b.F]=e[b.F].toString());e[b.referrer]=c[b.Ja]?e[b.referrer]:e[b.referrer]||d.referrer;e[b.ca]=e[b.ca]||n.location.toString();e[b.uid]?e[b.uid]=e[b.uid]:(g=this.Ga())&&(e[b.uid]=g);e[b.url]&&(e[b.url]=this.nb(e[b.url]),c[b.url]=e[b.url]);return e},Ga:function(){return k.$(b.ma)},
nb:function(a){var b=a;if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))b=decodeURIComponent(a);return b}};return c}(t,x,D,{});C=function(d,l,g,c,b,a,k){var f=d.a,h=l.a,e=g.a,q=c.a,p=b.a,n=a.a;k.a={track:function(a){var b=this;0===a[f.A]&&(a[f.A]=f.ja);e.h(f.u,f.Ka,a,function(c){if(c.error)h[f.error](f.ia+c.error.code+" - "+c.error.message);else c.uid&&b.ub(c.uid),p.c(c,a),n.o(c,a)})},ub:function(a){q.S(f.ma,a,new Date(2042,5,13))}};return k}(t,w,y,D,E,C,{});F=function(d,l,g,c,b){var a=d.a,k=
l.a,f=g.a,h=c.a;b.a={Kb:!1,Gb:!0,j:0,ka:5E3,xb:12E5,interval:null,reset:function(){k.I=k.G();n.clearInterval(this.interval)},track:function(b){var c=this,d;c.interval=setInterval(function(){k.O&&(c.j+=c.ka);c.la()&&(c.j=0);d=f.H(b);d[a.t]=c.j;d[a.e]=c.Ma()?5E3:0;d[a.ga]=k.G();0===d[a.A]&&(d[a.A]=a.ja);k.O&&!c.la()&&c.Bb(d)&&0<d[a.e]&&(c.j=0,h.h(a.u,a.wb,d));c.Oa=k.s.x;c.Pa=k.s.y;c.Na=k.G()},c.ka)},Ma:function(){return!0!==this.Da?this.Da=!0:this.Oa!==k.s.x||this.Pa!==k.s.y||this.Na!==k.G()?!0:!1},
la:function(){return this.j>=this.xb},Bb:function(b){return b[a.url]&&b[a.A]}};return b}(t,z,x,y,{});A=function(d,l,g,c,b,a,k,f){var h=d.a;d=l.a;var e=b.a,n=a.a,p=k.a;f.a={Reach:{collect:function(a){h.o(a)}},QS:{decode:d.decode},debug:e,setLogLevel:function(a){e.tb(a)},API:c.a,collect:function(a){h.o(a)},decode:d.decode,c:function(){h.c()},iframeCollect:function(){},stop:function(){p.reset()},scrollDepthReached:function(a){n.B(a)}};return f}(function(u,l,g,c,b,a,k,f,h,e,q){var p=u.a,t=l.a,m=g.a,v=
c.a,x=b.a,w=a.a,r=k.a,z=f.a,y=h.a,A=e.a;q.a={Fb:{},M:{},c:function(){try{w.c(),p.$(r.fa)?this.aa=!0:this.aa=!1,p.S(r.fa,r.Xa,new Date(2042,5,13)),t.current=n[r.ib],this.M=v.H(t.current),this.M[r.r]=this.aa,this.o(this.M)}catch(a){w.R(function(){m.sb(a)})}},o:function(a){var b={};if(a)if(m.c(a[r.Ha]),a[r.url]=a[r.url]||w.xa(),a[r.url])y.reset(),b=z.ra(a),b[r.cb]||(!1!==a[r.jb]&&(A.track(b),y.track(b)),!1!==a[r.wa]&&this.ya(b));else m[r.error](r.ia+r.za);else m[r.error]("Params not passed to collect")},
ya:function(a){a[r.ea]=a[r.ea]||d.referrer;a[r.sa]=(new Date).getTime();a=x.encode(a);this.V&&w.kb(this.V);this.V=w.oa(r.ha+r.ta+r.ua+"?"+a,r.x)}};return q}(D,A,w,x,B,z,t,G,F,C,{}),B,z,y,w,E,F,{});n.SPR=A.a;n.SPR.c()})(window,document);
