(function(d,e){var h,m;h=function(d){d.a={A:"edge.simplereach.com",B:"d8rk54i4mohrb.cloudfront.net",X:"/n",Ba:"/t",Qa:"/event",u:"/pixel?bad=true&error=",U:"/iframe.html",D:"/container.html",Aa:"000000000000000000000000",wa:"SPR-ERROR: ",Pa:"100 - Missing url",na:"__reach_config",s:"cache_buster",ra:"__srret",Ia:"__srui",i:"0",da:"1",F:"img",M:"1px",width:"width",N:e.location.protocol,c:"undefined",error:"error",J:"off",info:"info",h:"SPR_DEBUG",O:"//",l:"string",referrer:"referrer",uid:"uid",v:"callback",Z:"jsonp",url:"url",
ia:"pid",ta:"s",r:"r",t:"t",e:"e",x:"x",n:"n",V:"ignore_errors",ja:"preview",m:"authors",C:"channels",ya:"tags",Ca:"date",W:"inframe",T:"iframe",za:"custom_tracking",pa:"reach_tracking",qa:"ref_url",ea:"page_url",Ja:"user_id",ca:"manual_scroll_depth",ka:"rd",Ra:"fb",Ea:"de",$:"li",Da:"tw",fa:"pi",xa:"csd",P:"api.facebook.com",Ha:"feeds.delicious.com",Fa:"cdn.api.twitter.com",aa:"www.linkedin.com",ga:"partners-api.pinterest.com",la:"www.reddit.com",S:"/restserver.php",ma:"/api/info.json",La:"/v2/json/urlinfo/data",
Ga:"/1/urls/count.json",ba:"/countserv/count/share",ha:"/v1/urls/count.json",R:"links.getStats",Y:"["+this.error+"] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",va:"[info] sending scrollDepth of: ",ua:"[info] scroll depth not activated, not sending data"};return d}({});m=function(e,k){var g=e.a;k.a={C:function(){return Math.floor(8675309*Math.random())},I:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){d.console&&
console.log(a)},v:function(a){return"[object String]"===Object.prototype.toString.call(a)},D:function(a){var b={},f;for(f in a)a.hasOwnProperty(f)&&(b[f]=a[f]);return b},B:function(a,b){for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b.toString()+",")},m:function(a){typeof a===g.l&&(a=a.split(","));if(this.I(a)){for(var b=0;b<a.length;b+=1)typeof a[b]===g.l&&(a[b]=a[b].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},
g:function(){},s:function(){return d.location.protocol+"//"}};return k}(h,{});h=function(e,d){var g=e.a;d.a={fetchContainer:function(a){g.o("//edge.simplereach.com/x?"+a,"x")}};return d}(function(h,k,g){var a=h.a,b=k.a,b={c:"undefined",info:"info"};g.a={i:0,w:{x:0,y:0},H:!0,G:function(){function f(){l.H=e[g]?!1:!0}function a(){l.flush();d.removeEventListener("DOMContentLoaded",a,!1)}function c(){/loaded|interactive|complete/.test(e.readyState)&&(e.detachEvent("onreadystatechange",c),k&&(k=!1,l.flush()))}
var l=this,g,h;l.i=0;this.K(d,"mousemove",function(f){l.w={x:f.clientX,y:f.clientY}});typeof e.hidden!==b.c?(g="hidden",h="visibilitychange"):typeof e.mozHidden!==b.c?(g="mozHidden",h="mozvisibilitychange"):typeof e.msHidden!==b.c?(g="msHidden",h="msvisibilitychange"):typeof e.webkitHidden!==b.c&&(g="webkitHidden",h="webkitvisibilitychange");typeof e.addEventListener!==b.c&&typeof g!==b.c&&e.addEventListener(h,f,!1);var k=!0;d.addEventListener?d.addEventListener("DOMContentLoaded",a,!1):e.attachEvent&&
e.attachEvent("onreadystatechange",c)},o:function(f,n){var c=e.createElement("iframe"),d=e.body;c.setAttribute("name","spr");c.src=f;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id","spr-iframe-"+n);c.style.display="none";d||(d=this.b("BODY")[0]);d||(d=this.b("HEAD")[0]);a[b.info](f);d.appendChild(c);return c},sa:function(){for(var f=this.b("link"),a=this.b("meta"),c=0;c<f.length;c+=1)if("canonical"===f[c].rel)return f[c].href;for(;c<a.length;c+=
1)if("og:url"===a[c].getAttribute("property"))return a[c].content;return!1},Ka:function(f){var a=e.body,c=this.b("BODY")[0],b=this.b("HEAD")[0];a&&a.contains(f)?a.removeChild(f):c&&c.contains(f)?c.removeChild(f):b&&b.contains(f)&&b.removeChild(f)},oa:function(f){var d=this,c=e.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id","spr-script");c.src=f;a[b.info](f);this.L(function(){setTimeout(function(){d.b("HEAD")[0].appendChild(c)},
1)});return c},f:[],ready:/loaded|interactive|complete/.test(e.readyState),flush:function(){var a=this.f.shift();for(this.ready=!0;a;)a(),a=this.f.shift()},L:function(a){this.ready?(this.f.push(a),this.flush()):e.documentElement.doScroll?d.self===d.top?function(){if(!e.uniqueID&&e.expando)return this.f.push(a);try{e.documentElement.doScroll("left"),a()}catch(b){setTimeout(arguments.callee,0)}}():this.f.push(a):this.f.push(a)},K:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+
b,c);return a},J:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},Ma:function(){var a=0,a=d.pageYOffset?d.pageYOffset:e.documentElement?e.documentElement.scrollTop:0;return a-this.i},b:function(a){var b=[],c,d=0,g;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(e.getElementById(a.substring(1)));break;case ".":c=e.getElementsByTagName("*");for(g=" "+a.substring(1)+" ";d<c.length;d+=1)a=(" "+c[d].className+" ").replace(/[\n\t\r]/g,
" "),-1<a.indexOf(g)&&b.push(c[d]);break;default:b=e.getElementsByTagName(a)}return b}};return g}(function(h,k,g){var a=h.a,b=k.a;g.a={j:!1,info:b.g,error:b.log,G:function(){d[a.h]&&(this.j=!0,d[a.h][a.info]&&(this[a.info]=d[a.h][a.info]),d[a.h][a.error]&&(this[a.error]=d[a.h][a.error]))},reset:function(){this.j=!1;this[a.info]=b.g;this[a.info]=b.log},Na:function(b){var d=e.createElement(a.F);d.src=a.N+a.O+a.A+a.u+b.message;d.setAttribute(a.width,a.M);e.body?e.body.appendChild(d):e.head.appendChild(d)},
Oa:function(d){d===a.info?(this[a.info]=b.log,this[a.error]=b.log):d===a.error?(this[a.info]=b.g,this[a.error]=b.log):(this[a.info]=b.g,this[a.error]=b.g)}};return g}(h,m,{}),h,{}),{});d.SPR=h.a})(window,document);
