/* JS */ gapi.loaded_1(function(_){var window=this;
_.e("gapi.plusone.render",_.pG);_.e("gapi.plusone.go",_.qG);
var od,qd,sd,rd;od=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};qd="inline bubble none only pp vertical-bubble".split(" ");sd=["left","right"];_.pd=function(a){return od(a,qd)};rd=function(a){return od(a,sd)};_.td=function(a){a.source=[null,"source"];a.expandTo=[null,"expandTo"];a.align=[rd];a.annotation=[_.pd];a.origin=[_.md]};

_.Sm.po("ytsubscribe",function(a,c){var f=_.Sm.Ld;f&&_.Sm.Ei({role:"ytsubscribe",iframe:f,data:c},{role:"ytrelay",iframe:a})},void 0,_.Vz);
_.xw=function(a,c){c||(c={});var f=window,g;a instanceof _.su?g=_.Ls(a):g="undefined"!=typeof a.href?a.href:String(a);var h=c.target||a.target,l=[],n;for(n in c)switch(n){case "width":case "height":case "top":case "left":l.push(n+"="+c[n]);break;case "target":case "noreferrer":break;default:l.push(n+"="+(c[n]?1:0))}l=l.join(",");if(_.wk()&&f.navigator&&f.navigator.standalone&&h&&"_self"!=h)l=f.document.createElement("A"),l.setAttribute("href",g),l.setAttribute("target",h),c.noreferrer&&l.setAttribute("rel",
"noreferrer"),g=window.document.createEvent("MouseEvent"),g.initMouseEvent("click",!0,!0,f,1),l.dispatchEvent(g),f={};else if(c.noreferrer){if(f=f.open("",h,l))_.Vi&&-1!=g.indexOf(";")&&(g="'"+g.replace(/'/g,"%27")+"'"),f.opener=null,g=_.He(g),g=_.uk('<META HTTP-EQUIV="refresh" content="0; url='+g+'">',null),f.document.write(_.OG(g)),f.document.close()}else f=f.open(g,h,l);return f};

_.nW=function(){var a=_.We;return!!a&&0<=a.indexOf("CriOS")};_.oW=function(){var a=_.We;return!!a&&0<=a.indexOf("iPhone")&&0<=a.indexOf("Safari")&&-1==a.indexOf("CriOS")};_.NA=function(a,c){var f=/^https:\/\/([^\/]+\.google\.com)\//.exec(a);f&&-1!=["plus.google.com","plus.sandbox.google.com"].indexOf(f[1])&&(f=c||{},f.noreferrer=!0,(f=_.xw(a,f))&&f.focus())};

var QL,RL;
(function(){var a=null,c=null,f={0:"comments"};f[1]={href:[_.Zc],view_type:[null],query:[null],width:[null],pinned_comment:[null],owner_id:[null],first_party_property:[null],legacy_comment_moderation_url:[null]};var g=function(a,f,g){var h=_.sg(_.kg(c)).y;f&&_.oW()&&(h-=60);var l=_.ig().height,A=_.Jf(window.document).y;a=h+a;if(a<A||a>A+l||g)g=a,f&&(g-=l),_.Kf(window.document).scrollTop=g};f[3]={onfirsttimeplusonepromo:!0,onallcommentsclicked:!0,onfirsttimecommenter:!0,onhidefirsttimecommenterpromo:!0,ontimestampclicked:!0,
onshareboxopen:!0,onshownotification:!0,onthumbsup:!0,onupgradeaccount:!0,scroll:function(){return g},openwindow:function(){return _.nW()?_.NA:void 0}};var h=function(){if(c){var a=window.document.getElementById(c);a&&a.parentNode&&a.parentNode.parentNode&&(a.style.width=a.parentNode.parentNode.offsetWidth+"px")}},l=function(){a&&(a.U&&a.U(),c=a=null,window.removeEventListener?window.removeEventListener("resize",h):window.detachEvent&&window.detachEvent("onresize",h))};f[5]=function(f,g){"e"==f&&
(l(),a=g[5],c=a.Hh(),window.addEventListener?window.addEventListener("resize",h):window.attachEvent&&window.attachEvent("onresize",h))};_.iC(f);QL=l;RL=function(c){a.send("createComment",{content:c},null,_.Vz)}})();_.e("gapi.comments.createComment",RL);_.e("gapi.comments.dispose",QL);

_.V.qj("bubble",function(a){(0,_.At)("iframes-styles-bubble",a)});
_.V.qj("slide-menu",function(a){(0,_.At)("iframes-styles-slide-menu",a)});
var dd={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}},cd=function(a){return"string"==typeof a&&dd[a.toLowerCase()]?a.toLowerCase():"standard"},$c=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a},ed=function(a,c){return"tall"==cd(c)?"true":null==a||$c(a)?
"true":"false"},bd=function(a){if($c(a))return"true"},ad=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return String(c)},xv={width:180,height:35},hd={href:[_.Zc,"url"],width:[ad],size:[cd],resize:[bd],autosize:[bd],count:[function(a,c){return ed(c.count,c.size)}],db:[_.fd],ecp:[_.gd],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[bd],recommendations:[],fu:[],ad:[bd],cr:[ad],ag:[ad],"fr-ai":[],"fr-sigh":[]},wv=function(a,c,f){a=_.pd(a);c=cd(c);if(""!=
a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:dd[c]["false"].height};if("bubble"!=a){if("none"==a)return dd[c]["false"];if("pp"==a)return xv}}return dd[c]["true"]},gO=function(a,c){return dd[cd(a)][ed(c,a)]};
(function(){var a={0:"plusone"},c=_.P("iframes/plusone/preloadUrl");c&&(a[7]=c);_.td(hd);a[1]=hd;a[2]={width:[function(a,c){return c.annotation?wv(c.annotation,c.size,c).width:gO(c.size,c.count).width}],height:[function(a,c){return c.annotation?wv(c.annotation,c.size,c).height:gO(c.size,c.count).height}]};a[3]={onPlusOne:{Kg:function(a){return"on"==a.state?"+1":null},Qh:"callback"},onstartinteraction:!0,onendinteraction:!0,onpopup:!0};a[4]=["div","button"];a=_.iC(a);_.qG=a.go;_.pG=a.S})();

});
// Google Inc.
