var cbs_gamification=function(){"use strict";var pub={};var app_id='',widget={},user={},widget_actions_list=['visit','read_article','read_sports'],actions_list=['visit','read_article','read_sports','newsletter','view_gallery'],stats_widget_id='#sessionm-stats-widget',unclaimed_widget_id='#sessionm-unclaimed-widget',button_widget_id='#sessionm-button-widget';var button_text={read_article:{1:["You've Earned Points for Reading!","Claim points in our Reward Center, and earn more tomorrow."],3:["Like Our Articles? Love Our Stations!","Stream your favorite<br />stations to earn more.","http://radio.com/station-directory/","Listen Live"],20:["You’ve Hit Your Daily Reading Goal","Claim points in our Reward Center, and earn more tomorrow."],},read_sports:{1:["You've Earned Points for Reading!","Claim points in our Reward Center, and earn more tomorrow."],3:["Hey Sports Fan,<br />Heard Our Stations?","Stream your favorite sports<br />stations to earn more.","http://radio.com/station-directory/","Listen Live"],20:["You’ve Hit Your Daily Reading Goal","Claim points in our Reward Center, and earn more tomorrow."],},newsletter:{1:["Sign Up Achievement: You've Earned Points!","Claim points in our Reward Center, and earn more tomorrow."]},view_gallery:{1:["Gallery Achievement: You've Earned Points!","Claim points in our Reward Center, and earn more tomorrow."]}};var loaded=function(){widget=new sessionm.widget({appID:app_id,style:"custom"});widget.init(function(){});sessionm.addEventListener("userUpdated",function(new_user){user=new_user;pub.refresh_widgets();});};var unclaimed_widget=function(){if(jQuery(unclaimed_widget_id).length<1)return;jQuery(unclaimed_widget_id)
.empty()
.html('<a href="javascript:sessionm.openPortal();"><strong>CBS Local Rewards</strong><span class="count no-underline">'+user.getUnclaimedAchievementCount()+'</span></a>');};var stats_widget=function(){if(jQuery(stats_widget_id).length<1)return;var html,progress;if(user.isLoggedIn()){var achievements=user.getAchievements();html='<div class="disclosure">Earn more points with each visit.</div>';html+='<div class="achievements">';for(i=0;i<achievements.length;i++){if(widget_actions_list.indexOf(achievements[i].action)<0)continue;progress=achievements[i].fullDistance-achievements[i].distance;html+='<div class="achievement">';html+='<strong>'+achievements[i].name+'</strong>';html+='<span>('+progress+' of '+achievements[i].fullDistance+')</span>';html+='<div class="progress"><div class="bar" style="width:'+progress*100/achievements[i].fullDistance+'%"></div></div>';html+='</div>';}
html+='</div>';}else{html='<div class="disclosure">Earn points for great prizes by enjoying our articles, galleries, and newsletters.</div>';}
var rewards=sessionm.getRewards();var reward=rewards[Math.floor(Math.random()*rewards.length)];if(reward){html+='<div>Featured Reward</div>';html+='<img src="'+cbs_lib.escape_html(reward.getImageSrc())+'">';}
html+='<a href="javascript:sessionm.openPortal();">See Prizes</a>';html+='<div class="learn-more">';html+='<a href="https://sessionm.zendesk.com/hc/en-us/articles/201820539-CBS-Local-Websites" target="_blank">Learn more </a>';html+='about CBS Local Rewards</div>';jQuery(stats_widget_id)
.empty()
.append(html);};var action_complete_callback=function(action,earned,achievement){if(earned){pub.completed_action(action,Math.abs(achievement.fullDistance));}};pub.init=function(in_app_id){app_id=in_app_id;if(window.sessionm){loaded();}else if(window.addEventListener){window.addEventListener("sessionm.loaded",loaded);}};pub.do_action=function(action_name){if(actions_list.indexOf(action_name)<0)return;widget.sendAction(action_name,{throttleByUrlUniqueness:true,callback:action_complete_callback});};pub.completed_action=function(action_name,action_stage){if(actions_list.indexOf(action_name)<0||typeof button_text[action_name]=="undefined"||typeof button_text[action_name][action_stage]=="undefined")return;if(jQuery(button_widget_id).length<1)return;var html='<span class="icon"></span>';html+='<strong>'+button_text[action_name][action_stage][0]+'</strong>';html+='<em>'+button_text[action_name][action_stage][1]+'</em>';if(button_text[action_name][action_stage][2]!=null&&button_text[action_name][action_stage][3]!=null){html+='<a href="'+button_text[action_name][action_stage][2]+'">'+button_text[action_name][action_stage][3]+'</a>';}else{html+='<a href="javascript:sessionm.openPortal();">Claim Points</a>';}
jQuery(button_widget_id)
.empty()
.addClass('gamification-achievement-button')
.addClass(action_name+'_'+action_stage)
.html('<div class="wrapper">'+html+'</div>');};if(cbs_lib.get_browser()=="ie"){jQuery(stats_widget_id).hide();}else{pub.set_stats_widget_id=function(in_stats_widget_id){stats_widget_id=in_stats_widget_id;stats_widget();};}
pub.refresh_widgets=function(){unclaimed_widget();stats_widget();};return pub;};