(function(){function u(a,b){return-1<a.indexOf("?")?a+"&"+b:a+"?"+b}function r(a,b){return document.defaultView&&document.defaultView.getComputedStyle?document.defaultView.getComputedStyle(a,null)[b]:a.currentStyle?a.currentStyle[b]:a.style[b]}function v(a){a=a.getBoundingClientRect();return-1E3<=a.bottom&&0<=a.right&&a.top<=(window.innerHeight||document.documentElement.clientHeight)+1E3&&a.left<=(window.innerWidth||document.documentElement.clientWidth)}function J(a,b){var c=a.getAttribute("data-max-width");
c&&(b["max-width"]=c);if(b&&(c=a.parentNode,!("DIV"!==c.nodeName||1<c.childNodes.length))){var d=c.parentNode;"DIV"!==d.nodeName||1<d.childNodes.length||(a.removeAttribute("style"),c.removeAttribute("style"),d.removeAttribute("style"),d.style.width="100%",b&&b.height&&b.width&&!b["aspect-ratio"]?(a.setAttribute("width",b.width),a.setAttribute("height",b.height)):(a.style.top=0,a.style.left=0,a.style.width="100%",a.style.height="100%",a.style.position="absolute",c.style.left=0,c.style.width="100%",
c.style.height=0,c.style.position="relative",b.height||b["aspect-ratio"]||(c.style["padding-bottom"]="75%"),b["aspect-ratio"]?c.style["padding-bottom"]=Math.round(1E5/b["aspect-ratio"])/1E3+"%":(b.height&&(c.style.height=b.height+"px"),b.width&&(c.style.width=b.width+"px")),(b["max-width"]||b["min-width"])&&["max-width","min-width"].forEach(function(a){b[a]&&(d.style[a]=b[a]+"px")}),"undefined"!==typeof n&&n()))}}function K(a){if(a=a.match(/\?(.+)/i)){a=a[1];a=a.split("&");for(var b={},c=0;c<a.length;c++){var d=
a[c].split("=");b[d[0]]=decodeURIComponent(d[1])}return b}}function L(a){var b=document.createElement("span"),c=document.createElement("a");a.appendChild(b);a.appendChild(c);var d={span:{"font-family":r(b,"font-family")},a:{"font-family":r(c,"font-family"),color:r(c,"color")}};a.removeChild(b);a.removeChild(c);return d}var h=window.iframely=window.iframely||{},e=h.widgets=h.widgets||{},s=h.events=h.events||{},D=e._iframes=e._iframes||[],E=e._global_iframes=e._global_iframes||[],t=e._lazy_iframes=
e._lazy_iframes||[],l,F,w,x,y,G,q;e.load||(h.load=e.load=function(){if(0===arguments.length){for(var a=document.querySelectorAll("[data-iframely-url]"),b=1===a.length&&v(a[0]),c=0;c<a.length;c++)e.createWidget(a[c],{preventLazyLoad:b});a=document.querySelectorAll(".iframely-embed-button");for(c=0;c<a.length;c++)e.createEmbedButton(a[c])}else 1===arguments.length?e.createWidget(arguments[0]):2===arguments.length&&e.createWidgetInContainer(arguments[0],arguments[1])});e.createWidgetInContainer||(e.createWidgetInContainer=
function(a,b){var c=document.createElement("a");c.setAttribute("href",b);c.textContent=b;a.appendChild(c);e.createWidget(c)});e.createWidget||(e.createWidget=function(a,b){var c=a.getAttribute("href"),d=a.getAttribute("data-iframely-url"),g=d&&d.match(/^((?:https?:)?\/\/[^\/]+)\/\w+/i),g=g&&g[1];if(!a.getAttribute("data-iframely-loading")){a.setAttribute("data-iframely-loading",!0);var e=a.parentNode,k=a.getAttribute("data-max-width"),f=a.getAttribute("data-template");if(f&&d&&g)if("inline"===f)d=
u(d,"app=1"),b&&b.preventLazyLoad||(d=u(d,"lazy=1")),"auto"===k&&(g=e.clientWidth)&&(d=u(d,"maxwidth="+g));else{c="";"general"===f&&(c="&general_promo=1");"general-summary"===f&&(f="general");var M=JSON.stringify(L(a.parentNode),null,0),d=g+"/widget/"+f+"#id="+encodeURIComponent(d)+"&styles="+encodeURIComponent(M)+c}else k=k||G,d="/api/iframe?app=1&url="+encodeURIComponent(c),b&&b.preventLazyLoad||(d+="&lazy=1"),d=x?q+d+"&key="+x:w?q+d+"&api_key="+w:"http://open.iframe.ly"+d,y&&(d+="&"+y);g=d.match(/^(https?:)?\/\//i);
g[1]||"file:"!==document.location.protocol||(d="http:"+d);g=document.createElement("div");g.innerHTML='<div style="width: 100%; position: relative; padding-bottom: 75%;"><iframe frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" style="width: 100%; height: 100%; position: absolute;"></iframe></div>';f=g.querySelector("iframe");k&&parseInt(k)?(g.setAttribute("style","width: 100%; max-width: "+k+"px;"),f.setAttribute("data-max-width",k)):g.setAttribute("style",
"width: 100%;");D.push({iframe:f,iframeContainer:g,link:a});t.push({iframe:f});a.setAttribute("style","display: none;");e.insertBefore(g,a);f.setAttribute("src",d);s.trigger("rendered")}});e.createEmbedButton||(e.createEmbedButton=function(a){if(!a.getAttribute("data-iframely-binded")){a.setAttribute("data-iframely-binded",!0);var b=a.getAttribute("data-url")||document.location.href,c=a.getAttribute("data-promo")||"",d=a.getAttribute("data-iframely-api-key")||"";a.addEventListener("click",function(a){a.preventDefault();
F=r(document.body,"overflow");document.body.style.overflow="hidden";l=document.createElement("iframe");l.setAttribute("style","position: fixed; z-index: 999999; top: 0; left: 0; width: 100%; height: 100%; border: 0; margin: 0; padding: 0; display: block");l.setAttribute("src",q+"/widget/embed#url="+encodeURIComponent(b)+"&promo="+encodeURIComponent(c)+"&api_key="+encodeURIComponent(d));document.body.appendChild(l)})}});if(!s.bind){var z={};s.bind=function(a,b){(z[a]=z[a]||[]).push(b)};s.trigger=function(a,
b){(z[a]||[]).forEach(function(a){a(b)})}}e.ready||(e.ready=function(a){"function"===typeof a&&a()});for(var A=function(){return{postMessage:function(a,b,c){a=JSON.stringify(a);c=c||window.parent;window.postMessage&&c.postMessage(a,(b||"*").replace(/([^:]+:\/\/[^\/]+).*/,"$1"))},receiveMessage:function(a){function b(b){var d;try{d=JSON.parse(b.data)}catch(e){}a(b,d)}if(window.postMessage)if(window.addEventListener)window[a?"addEventListener":"removeEventListener"]("message",b,!1);else window[a?"attachEvent":
"detachEvent"]("onmessage",b)}}}(),h=document.querySelectorAll("script"),H=/https?:\/\/[^\/]+/,B=0;B<h.length&&!q;B++){var p=h[B].getAttribute("src");if(p&&p.match(/iframely\d?\.js|embed\.js/)){var m=K(p);if(m){w=m.api_key;x=m.key;G=m.maxwidth;delete m.api_key;var I=[],C;for(C in m)I.push(C+"="+encodeURIComponent(m[C]));y=I.join("&")}q=(p=p.match(H)||document.location.href.match(H))&&p[0]||"https://iframe.ly"}}if(!e.lazyLoadCheckRegistered){e.lazyLoadCheckRegistered=!0;var n=function(){t.forEach(function(a){!a.lazyShown&&
v(a.iframe)&&(a.lazyShown=!0,A.postMessage({method:"showLazyLoad"},"*",a.iframe.contentWindow))})};window.addEventListener?(addEventListener("scroll",n,!1),addEventListener("resize",n,!1)):window.attachEvent&&(attachEvent("onscroll",n),attachEvent("onresize",n))}e.receiveMessageRegistered||(e.receiveMessageRegistered=!0,A.receiveMessage(function(a,b){if(b&&b.method){var c=null,d=null;D.forEach(function(b){b.iframe.contentWindow===a.source&&(c=b.iframe,d=b)});E.forEach(function(b){b.contentWindow===
a.source&&(c=b)});if(!c)for(var e=document.querySelectorAll("iframe"),h=0;h<e.length;h++){var k=e[h];E.push(k);k.contentWindow===a.source&&(c=k)}if(c&&"registerLazyLoad"===b.method){var f;t.forEach(function(b){b.iframe.contentWindow===a.source&&(f=b)});f||(f={iframe:c},t.push(f));v(c)&&(f.lazyShown=!0,A.postMessage({method:"showLazyLoad"},"*",c.contentWindow))}(c&&"setIframelyWidgetSize"===b.method||"resize"===b.method||"setIframelyEmbedData"===b.method)&&J(c,b.data&&b.data.media||{height:b.height});
d&&"cancelWidget"===b.method&&(e=d.link,e.removeAttribute("style"),e.setAttribute("target","_blank"),h=e.textContent.replace(/^\s+|\s+$/g,""),e.textContent=h||e.getAttribute("href").replace(/^https?:\/\//i,""),e.parentNode.removeChild(d.iframeContainer));"closeEmbedPreview"===b.method&&(l&&l.parentNode.removeChild(l),document.body.style.overflow=F)}}));e.load();(e._e||[]).forEach(function(a){"function"===typeof a&&a()})})();
