(function(window) {var c=!0,n=!1,p=window,s=n,t=n,u={"0":"http://mads.advertising.com",1:"http://mads.advertising.com",2:"http://madseu.advertising.com",3:"http://sr.mads.advertising.com"},v={"0":"https://mads.advertising.com",1:"https://mads.advertising.com",2:"https://madseu.advertising.com",3:"https://mads.advertising.com"};
function w(){var j=p.navigator.plugins,h;if("undefined"!==typeof j&&"object"===typeof j["Shockwave Flash"]){var a=navigator.mimeTypes;if((h=j["Shockwave Flash"].description)&&!("undefined"!==typeof a&&a["application/x-shockwave-flash"]&&!a["application/x-shockwave-flash"].enabledPlugin))return h=h.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),h.replace(/^(.*)\..*$/,"$1")}else if("undefined"!==typeof p.ActiveXObject)try{if(a=new p.ActiveXObject("ShockwaveFlash.ShockwaveFlash"))if(h=a.GetVariable("$version"))return h=
h.split(" ")[1].split(","),h[0]}catch(m){}return"0"}
(p.madserver={}).requestAd=function(j,h){var a={},m;for(m in j)j.hasOwnProperty(m)&&(a[m.toLowerCase()]=j[m]);var f,q,r,e,g,k,l;m=(new Date).getTime();p.screen&&(p.screen.width&&p.screen.height)&&(f=p.screen.width,q=p.screen.height);p.devicePixelRatio&&(r=p.devicePixelRatio);e="undefined"!=typeof p.onorientationchange;g=-1<p.navigator.userAgent.toLowerCase().indexOf("mobile");var b=n;l=c;try{p.top!==p.self&&(b=c),t=0<=p.location.href.indexOf("https://"),k=p.top.location.href.toString()}catch(x){}if(!k||
"undefined"===k)b=c,l=n;k={a:b,b:l,c:t};l=w();b={};b.mpid=a.mobileplacementid;b.rettype=a.calltype||"js";b.ismob=e||g?"1":"0";b.kvmflash=("0"!==l?c:n)?"true":"false";b.fv=l;b.r=parseInt(a.region)&&a.region in u?parseInt(a.region):0;e=new Date;g=e.getHours();b.wkhr=24*e.getDay()+g;b.hr=g;b.optn="1";e="";p.mraid&&(g=p.mraid.getVersion(),l=g.indexOf("."),0<l&&(g=g.substring(0,l),"1"==g?e+="3:":"2"==g&&(e+="5:")));p.ormma&&(e+="4:");(e=0<e.length?e.substring(0,e.length-1):"")&&(b.apifw=e);m&&(b.random=
(m%999999999+1).toString());q&&f&&(b.swh=f+"x"+q,b.screenWidth=f,b.screenHeight=q);r&&(b.sd=r,b.screenDensity=r);k&&(b.f=a.f||(k.a?k.b?"1":"2":"0"),b.aolexp=a.hasOwnProperty("aolexp")?a.aolexp:"0"===b.f.toString()||"1"===b.f.toString()?"1":"0");Number(a.height)&&parseInt(a.height)&&(b.height=a.height);Number(a.width)&&parseInt(a.width)&&(b.width=a.width);a.mobileapplicationuuid&&(b.appguid=a.mobileapplicationuuid);a.limitadtracking&&(b.limitadtracking=a.limitadtracking);a.mobileapplicationname&&(b.kvappn=
a.mobileapplicationname);a.latitude&&(b.lat=a.latitude);a.longitude&&(b["long"]=a.longitude);a.age&&(b.kvua=a.age);a.gender&&(b.kvug=a.gender);a.sourcetype&&(b.source=a.sourcetype);a.mobilecarrier&&(b.kvmsdkcarrier=a.mobilecarrier);a.adtechmobilesdkversion&&(b.kvmversion=a.adtechmobilesdkversion);f=a.host?a.host:t?b.r?v[b.r]:v[0]:b.r?u[b.r]:u[0];f+=a.endpoint?a.endpoint:"/adcall?";for(var d in b)b.hasOwnProperty(d)&&(f+=d+"="+b[d]+";");a.extra&&(d=a.extra,f+=d+(";"===d.charAt(d.length-1)?"":";"));
a.dref&&(d=f+="dref="+escape(escape(a.dref).replace(/\//g,"%2F")),2076<d.length&&(d=d.substr(0,2076),-1!==d.substr(d.length-4).indexOf("%")?d=d.substr(0,d.lastIndexOf("%")):-1!==d.substr(d.length-7).indexOf("%25u")&&(d=d.substr(0,d.lastIndexOf("%25u")))),f=d);d='<script language="javascript1.1" src="'+f+'">\x3c/script>';if(!d)return n;h||p.document.write(d);"0"!=a.exchmap&&(k&&!k.c&&33>=Math.floor(100*Math.random())+1&&!p.madserver.PIXEL_SERVER_SYNC_FIRED&&!s)&&(p.madserver.PIXEL_SERVER_SYNC_FIRED=
c,a=function(){var a=p.document.createElement("iframe");a.id="MADSERVER_PIXEL_SERVER_SYNC";a.src="http://cmap.uac.ace.advertising.com/um.ashx?site=876993";a.width=0;a.height=0;a.style.width="0px";a.style.height="0px";a.style.display="none";p.document.body.appendChild(a)},p.addEventListener?p.addEventListener("load",a,n):p.attachEvent&&p.attachEvent("onload",a));return d};if(p.mraid||p.ormma&&(p.mraid||p.ormma).open)s=c,p.open=function(j){(p.mraid||p.ormma).open(j)};})(window);
